/* LotPrism · доводка 2 · графики, Research, вид администратора, запуск */
(function(){
'use strict';
const LP=window.LP,{D,$,$$,esc,T,eur,fdt,K,IC,av,acc,REG,E4,S}=LP;
const CH=LP.CH={};
const f2=v=>{const n=v<0;let [a,b]=Math.abs(v).toFixed(2).split('.');a=a.replace(/\B(?=(\d{3})+(?!\d))/g,' ');return (n?'−':'')+a+','+b};
const fi=n=>String(n).replace(/\B(?=(\d{3})+(?!\d))/g,'\u202F');
/* подсказка — Chart Tooltip (uiable): заголовок, строки «индикатор · серия · значение» табличными цифрами */
const tipH=(h,rows,foot)=>`<p class="tip-h">${h}</p>${rows.map(r=>`<p class="tip-r"><i class="ti ti-${r[0]||'0'}" aria-hidden="true"></i><span>${r[1]}</span><b>${r[2]}</b></p>`).join('')}${foot?`<p class="tip-f">${foot}</p>`:''}`;LP.tipH=tipH;
const ms=iso=>Date.parse(iso.length===10?iso+'T00:00:00+02:00':iso);
/* ── общая обвязка графика: наведение, фокус ←/→, касание; подсказка 350 мс, соседняя — сразу ── */
function chartWrap(id,q,out,meta,svg,tbl,note){return `<figure class="fig" aria-labelledby="${id}-q"><div class="fig-h"><div><p class="q" id="${id}-q">${q}</p><p class="out">${out}</p></div></div><p class="fig-meta">${meta}</p>
<div class="chart" data-ch="${id}" tabindex="0" role="group" aria-label="${esc(q)} — стрелки ← → перебирают значения">${svg}</div>${note?`<div class="fig-n">${note}</div>`:''}
<div class="vt">${acc('t-'+id,'Таблица значений',tbl)}</div></figure>`}
function mountCharts(root){$$('.chart[data-ch]',root).forEach(el=>{if(el._m)return;el._m=1;const id=el.dataset.ch;const tip=document.createElement('div');tip.className='tip';tip.hidden=true;tip.setAttribute('role','status');el.appendChild(tip);let cur=-1,tm=null;
 const show=(i,now)=>{const P=CH[id];if(!P||!P.pts.length)return;i=Math.max(0,Math.min(P.pts.length-1,i));const go=()=>{cur=i;const p=P.pts[i],svg=$('svg',el),k=svg.getBoundingClientRect().width/P.W;$$('.pt',el).forEach(g=>g.dataset.on=g.dataset.i==i?'1':'0');tip.innerHTML=T(p.t);tip.hidden=false;const x=p.x*k,y=p.y*k;if(x<el.scrollLeft+16||x>el.scrollLeft+el.clientWidth-16)el.scrollLeft=x-el.clientWidth/2;const sl=el.scrollLeft,tw=tip.offsetWidth,th=tip.offsetHeight;const ch=el.clientHeight;let L=Math.max(sl+4,Math.min(sl+el.clientWidth-tw-4,x-tw/2)),Tp;if(y-th-12>=0)Tp=y-th-12;else if(y+14+th<=ch)Tp=y+14;else{Tp=Math.max(0,Math.min(ch-th,y-th/2));L=x+14+tw<=sl+el.clientWidth?x+14:Math.max(sl+4,x-14-tw)}tip.style.left=L+'px';tip.style.top=Tp+'px'};clearTimeout(tm);if(now||!tip.hidden)go();else tm=setTimeout(go,350)};
 const hide=()=>{clearTimeout(tm);tip.hidden=true;cur=-1;$$('.pt',el).forEach(g=>g.dataset.on='0')};
 const near=e=>{const P=CH[id],svg=$('svg',el),b=svg.getBoundingClientRect(),k=b.width/P.W,x=(e.clientX-b.left)/k,y=(e.clientY-b.top)/k;let bi=0,bd=1e9;P.pts.forEach((p,i)=>{const d=P.xOnly?Math.abs(p.x-x):Math.hypot(p.x-x,p.y-y);if(d<bd){bd=d;bi=i}});return bi};
 el.addEventListener('pointermove',e=>{if(e.pointerType==='mouse')show(near(e))});
 el.addEventListener('pointerleave',e=>{if(e.pointerType==='mouse')hide()});
 el.addEventListener('pointerdown',e=>{if(e.pointerType!=='mouse')show(near(e),true)});
 el.addEventListener('focus',()=>show(cur<0?(CH[id].start||0):cur,true));if(CH[id]&&CH[id].scrollFirst&&el.scrollWidth>el.clientWidth){const k=$('svg',el).getBoundingClientRect().width/CH[id].W;el.scrollLeft=Math.max(0,CH[id].pts[0].x*k-48)}el.addEventListener('blur',hide);
 el.addEventListener('keydown',e=>{if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();show((cur<0?0:cur)+(e.key==='ArrowRight'?1:-1),true)}else if(e.key==='Home'){e.preventDefault();show(0,true)}else if(e.key==='End'){e.preventDefault();show(CH[id].pts.length-1,true)}else if(e.key==='Escape'&&!tip.hidden){e.stopPropagation();hide()}})});
 $$('[data-pi]',root).forEach(el=>{if(!el._m){el._m=1;piBind(el)}});
 $$('.tbl[data-sort]',root).forEach(t=>{if(!t._m){t._m=1;initTableSort(t)}})}
LP.mountCharts=mountCharts;
/* ── сортировка таблицы: Origin UI, перенос; неизвестное — последним ── */
function initTableSort(table){table.querySelectorAll('thead th').forEach((th,col)=>{const btn=th.querySelector('.sort');if(!btn)return;btn.addEventListener('click',()=>sortBy(table,th,col))})}
function sortBy(table,th,col){const dir=th.getAttribute('aria-sort')==='ascending'?'descending':'ascending';table.querySelectorAll('thead th').forEach(h=>h.hasAttribute('aria-sort')&&h.setAttribute('aria-sort','none'));th.setAttribute('aria-sort',dir);
 const rows=[...table.tBodies[0].rows];const val=r=>{const c=r.cells[col];const g=c&&c.querySelector('[data-v]');return g?parseFloat(g.dataset.v):null};
 rows.sort((a,b)=>{const x=val(a),y=val(b);if(x==null&&y==null)return 0;if(x==null)return 1;if(y==null)return -1;return dir==='ascending'?x-y:y-x});rows.forEach(r=>table.tBodies[0].append(r))}
/* ── история цены ── */
LP.priceChart=function(){const E=D.charts.E1_price_buybox,W=860,H=280,ml=44,mr=110,mt=28,mb=28;
 const t0=ms('2026-07-03'),now=ms('2026-10-01T10:00:00+02:00'),tE=ms('2026-09-30T18:05:00+02:00')+30*864e5,g1a=ms('2026-08-11'),g1b=ms('2026-08-18');
 const x=t=>ml+(t-t0)/(tE-t0)*(W-ml-mr),y=v=>mt+(26.8-v)/(26.8-22.5)*(H-mt-mb);
 const P=E.points.map(p=>({t:ms(p.t),v:p.price_new/100,b:p.buybox==null?null:p.buybox/100,o:p.offers_new,iso:p.t}));
 let dn=`M${x(P[0].t).toFixed(1)} ${y(P[0].v).toFixed(1)}`,db='',pen=false;
 for(let i=0;i<P.length-1;i++){const a=P[i],b=P[i+1];if(a.t<g1a&&b.t>=g1b)dn+=`H${x(g1a).toFixed(1)}M${x(b.t).toFixed(1)} ${y(b.v).toFixed(1)}`;else dn+=`H${x(b.t).toFixed(1)}V${y(b.v).toFixed(1)}`}
 for(let i=0;i<P.length;i++){const a=P[i],b=P[i+1];if(a.b==null){pen=false;continue}if(!pen){db+=`M${x(a.t).toFixed(1)} ${y(a.b).toFixed(1)}`;pen=true}if(!b)break;const end=(a.t<g1a&&b.t>=g1b)?g1a:b.t;db+=`H${x(end).toFixed(1)}`;if(end!==b.t||b.b==null){pen=false;continue}db+=`V${y(b.b).toFixed(1)}`}
 const F=E.forecast,xn=x(now),xe=x(tE),lp=x(P[P.length-1].t);
 let s=`<svg width="${W}" height="${H+8}" viewBox="0 0 ${W} ${H+8}" role="img" aria-labelledby="pc-t pc-d"><title id="pc-t">Цена листинга NEW и Buy Box, amazon.de, 90 дней</title><desc id="pc-d">Ступенчатая линия 03.07–30.09, 64 наблюдения, от 23,90 до 25,90 € с НДС. Разрывы: 11.08–17.08 и с 30.09 18:05. Прогноз модели P10–P90 22,90–26,40 € после 30.09, на вывод не влияет.</desc><defs><pattern id="hp" width="5" height="5" patternUnits="userSpaceOnUse" patternTransform="rotate(45)"><rect width="1.6" height="5" fill="rgba(255,216,74,.28)"></rect></pattern></defs>`;
 [23,24,25,26].forEach(v=>s+=`<path d="M${ml} ${y(v).toFixed(1)}H${W-mr+60}" stroke="#1F2737"></path><text x="0" y="${(y(v)+4).toFixed(1)}">${v} €</text>`);
 s+=`<rect x="${x(g1a).toFixed(1)}" y="${mt-8}" width="${(x(g1b)-x(g1a)).toFixed(1)}" height="${H-mt-mb+8}" fill="none" stroke="#AAB2C2" stroke-dasharray="3 3"></rect><text class="l" x="${((x(g1a)+x(g1b))/2).toFixed(1)}" y="${mt-12}" text-anchor="middle">нет наблюдений провайдера</text>`;
 s+=`<rect x="${lp.toFixed(1)}" y="${mt-8}" width="${(xn-lp).toFixed(1)}" height="${H-mt-mb+8}" fill="none" stroke="#AAB2C2" stroke-dasharray="2 2"></rect>`;
 s+=`<path d="${dn}" fill="none" stroke="#2FD1BE" stroke-width="3" stroke-linejoin="round"></path><path d="${db}" fill="none" stroke="#E6EAF0" stroke-width="1.5" stroke-dasharray="5 3"></path>`;
 s+=`<path d="M${xn.toFixed(1)} ${y(24.9).toFixed(1)}L${xe.toFixed(1)} ${y(F.p90/100).toFixed(1)}V${y(F.p10/100).toFixed(1)}Z" fill="url(#hp)" stroke="#FFD84A" stroke-opacity=".5" stroke-width="1" stroke-dasharray="4 3"></path><path d="M${xn.toFixed(1)} ${y(24.9).toFixed(1)}L${xe.toFixed(1)} ${y(F.p50/100).toFixed(1)}" stroke="#FFD84A" stroke-opacity=".5" stroke-width="1" stroke-dasharray="2 3"></path>`;
 s+=`<path d="M${xn.toFixed(1)} 4V${H-mb}" stroke="#F2F4F8" stroke-dasharray="3 3"></path><text class="l" x="${(xn+6).toFixed(1)}" y="12">сейчас · 01.10 10:00</text><text class="l" x="${(xn+6).toFixed(1)}" y="26">← обновление не удалось с 30.09 18:05</text>`;
 s+=`<text x="${(xe+6).toFixed(1)}" y="${(y(F.p90/100)+4).toFixed(1)}">P90 26,40 €</text><text x="${(xe+6).toFixed(1)}" y="${(y(F.p10/100)+4).toFixed(1)}">P10 22,90 €</text><text class="l" x="${(xe+6).toFixed(1)}" y="${(y(24.6)+4).toFixed(1)}">на вывод не влияет</text>`;
 [['2026-07-03','03.07'],['2026-08-01','01.08'],['2026-09-01','01.09'],['2026-10-01','01.10'],['2026-10-30','30.10']].forEach(([d,l],i)=>s+=`<text x="${x(ms(d)).toFixed(1)}" y="${H+4}" text-anchor="${i===0?'start':i===4?'end':'middle'}">${l}</text>`);
 const pts=P.map((p,i)=>({x:x(p.t),y:y(p.v),t:tipH(fdt(p.iso),[['n','NEW',f2(p.v)+' € с НДС'],['b','Buy Box',p.b==null?'не определён':f2(p.b)+' € с НДС'],['','Продавцов NEW',String(p.o)]],K.FACT+' · Keepa')}));
 pts.push({x:xe,y:y(F.p50/100),t:tipH('Прогноз на 30.10',[['p','P10–P90','22,90–26,40 € с НДС'],['p','P50 (демо)','24,60 € с НДС']],K.FORECAST+' · прогноз модели · на вывод не влияет')});
 pts.forEach((p,i)=>s+=`<g class="pt" data-i="${i}"><circle cx="${p.x.toFixed(1)}" cy="${p.y.toFixed(1)}" r="${i===pts.length-1?4:2.5}" fill="${i===pts.length-1?'#FFD84A':'#2FD1BE'}" stroke="transparent" stroke-width="8"></circle></g>`);
 s+='</svg>';CH.pc={W,pts,xOnly:true,start:P.length-1};
 const tbl=`<div class="tbl-wrap" tabindex="0" role="region" aria-label="Таблица значений: история цены"><table class="tbl" data-density="dense"><thead><tr><th scope="col">Дата и время</th><th scope="col" class="num">NEW, € с НДС</th><th scope="col" class="num">Buy Box, € с НДС</th><th scope="col" class="num">Продавцов NEW</th><th scope="col">Вид знания</th></tr></thead><tbody>${E.points.map(p=>`<tr><td>${fdt(p.t)}</td><td class="num">${f2(p.price_new/100)}</td><td class="num">${p.buybox==null?'<span class="ms u">не определён</span>':f2(p.buybox/100)}</td><td class="num">${p.offers_new}</td><td>${K.FACT}</td></tr>`).join('')}
${E.gaps.map(g=>`<tr><td>${fdt(g.from)} – ${fdt(g.to)}</td><td colspan="3"><span class="ms u">разрыв</span> · ${esc(g.reason)}</td><td>${K.UNKNOWN}</td></tr>`).join('')}<tr><td>01.10 – 30.10</td><td colspan="3">P10 22,90 · P50 24,60 (демо) · P90 26,40</td><td>${K.FORECAST}</td></tr></tbody></table></div>`;
 return chartWrap('pc','Насколько устойчива цена, от которой посчитан предел?','90 дней цена держалась в 23,90–25,90 €; последнее изменение — 26.09 07:40.','NEW и Buy Box · € с НДС · amazon.de через Keepa · 03.07–30.09.2026, 64 наблюдения · данные на 30.09 18:05',s,tbl,`<div class="lgd"><span><i class="ti ti-n"></i>NEW ${K.FACT}</span><span><i class="ti ti-b"></i>Buy Box ${K.FACT}</span><span><i style="width:18px;height:10px;border:1px dashed var(--mute)"></i>разрыв: нет данных</span><span class="lg-q"><i class="ti ti-p"></i>прогноз модели · исследовательский режим · на вывод не влияет ${K.FORECAST}</span></div>`)};
/* ── сравнение предложений: прямые подписи у маркеров; без цены — отдельной строкой, не на шкале ── */
LP.cmpChart=function(id){const mob=innerWidth<=760,W=mob?600:Math.max(560,Math.min(860,innerWidth-(innerWidth>=1440?620:590))),ml=mob?136:150,mr=mob?176:200,rows=[['S1','прайс оптовика','Чехия',7.60,'f','код совпал','код совпал · проверено · от 60 шт.'],['S2','оптовая площадка','Польша',8.10,'y','условно','кода нет · упаковка не указана · условно'],['S3','розница','Германия',16.72,'r','только сравнение','только сравнение: цена розницы не становится ценой закупки']];
 const rh=40,top=30,H=rows.length*rh+top+26,x0=ml,x1=W-mr,x=v=>x0+(v-6)/12*(x1-x0);
 let s=`<svg width="${W}" height="${H}" viewBox="0 0 ${W} ${H}" role="img" aria-labelledby="${id}-t ${id}-d"><title id="${id}-t">Предложения поставщиков относительно предела</title><desc id="${id}-d">Шкала 6–18 € без НДС. S1 Чехия 7,60 € — код совпал; S2 Польша 8,10 € — условно; S3 Германия 16,72 € — только сравнение. Предел 9,60 € при 30 %; при 20 / 10 / 0 % — 10,40 · 11,35 · 12,49 €. Без цены — Китай и ручной ввод, ниже графика.</desc>`;
 [[10.40,0],[11.35,0],[12.49,0],[9.60,1]].forEach(([v,m])=>s+=`<path d="M${x(v).toFixed(1)} ${top-6}V${H-22}" stroke="${m?'#F2F4F8':'#4A5468'}" ${m?'stroke-width="1.5"':'stroke-dasharray="3 3"'}></path>`);
 s+=`<text class="dl" x="${(x(9.60)+6).toFixed(1)}" y="14">предел 9,60 € · РАСЧЁТ</text>`;
 s+=`<text class="l" x="${x1+16}" y="14">прямые подписи</text>`;
 const pts=[];rows.forEach((r,i)=>{const cy=top+i*rh+rh/2,cx=x(r[3]);s+=`<text class="l" x="0" y="${cy+4}">${r[0]} · ${esc(r[1])}</text><path d="M${x0} ${cy}H${x1}" stroke="#1F2737"></path><path d="M${(cx+8).toFixed(1)} ${cy}H${x1+8}" stroke="#2A3446" stroke-dasharray="1 3"></path>`;
  pts.push({x:cx,y:cy,t:tipH(`${r[0]} · ${r[2]}, ${esc(r[1])}`,[[r[4]==='f'?'mf':r[4]==='y'?'my':'mr','Цена, без НДС',f2(r[3])+' €']],(r[4]==='y'?K.COND:r[4]==='r'?'<span class="kx">сравнение</span>':K.FACT)+' · '+esc(r[6]))});
  s+=`<g class="pt" data-i="${i}">`+(r[4]==='f'?`<circle cx="${cx}" cy="${cy}" r="6" fill="#F2F4F8"></circle>`:r[4]==='y'?`<circle cx="${cx}" cy="${cy}" r="6" fill="#0E131D" stroke="#F2F4F8" stroke-width="1.5"></circle><path d="M${cx-6} ${cy}a6 6 0 0 1 6-6v12a6 6 0 0 1-6-6z" fill="#F2F4F8"></path>`:`<circle cx="${cx}" cy="${cy}" r="6" fill="#0E131D" stroke="#AAB2C2" stroke-width="1.5" stroke-dasharray="2 2"></circle>`)+`</g>`;
  s+=`<text class="dl" x="${x1+16}" y="${cy+4}">${r[2]} · ${f2(r[3])} € · ${r[5]}</text>`});
 [6,9,12,15,18].forEach(v=>s+=`<text x="${x(v).toFixed(1)}" y="${H-4}" text-anchor="middle">${v} €</text>`);s+='</svg>';CH[id]={W,pts,scrollFirst:true};
 const lim=`<p class="lim-l">Пунктир — пределы при доходности 20 / 10 / 0 %: <span class="n">10,40 · 11,35 · 12,49 €</span> ${K.CALC}</p>`;
 const nop=`<ul class="nop"><li><span>S4 · Китай, производитель</span><span class="ms u">цена неизвестно</span><span class="t2">каталог за регистрацией</span></li><li><span>Ручной ввод · Томас Вебер, 30.09</span><span><span class="n">7,40 €</span> ${K.CLAIM}</span><span class="t2">со слов поставщика · не проверено · вне экономики</span></li></ul>`;
 const tbl=`<div class="tbl-wrap" tabindex="0" role="region" aria-label="Таблица значений: предложения"><table class="tbl" data-density="dense"><thead><tr><th scope="col">Источник</th><th scope="col" class="num">Цена, € без НДС</th><th scope="col">Проверка</th><th scope="col" class="num">До предела 30 %, €</th></tr></thead><tbody>
${D.charts.E6_suppliers.rows.map(r=>`<tr><td>${esc(r.source)}<span class="sub">${esc(r.authority)}</span></td><td class="num">${f2(r.price_net.cents/100)}</td><td>${r.verification==='confirmed'?K.FACT:K.COND} <span class="kx">${esc(r.pack)}</span></td><td class="num">${r.class==='retailer_observation'?'<span class="kx">не считается</span>':f2(r.vs_ceiling.cents/100)}</td></tr>`).join('')}
<tr><td>S4 Китай, производитель</td><td class="num"><span class="ms u">неизвестно</span></td><td>${K.UNKNOWN}</td><td class="num"></td></tr><tr><td>Ручной ввод · Томас Вебер, 30.09</td><td class="num">7,40</td><td>${K.CLAIM} <span class="kx">документа нет</span></td><td class="num"><span class="kx">вне экономики</span></td></tr></tbody></table></div>`;
 return chartWrap(id,'Какие предложения сопоставимы и где они относительно предела?','Ниже предела при 30 % — два; без оговорок не сопоставимо ни одно.','одна единица · EUR · без НДС · одна база доставки · исследование 21.09–24.09 и ручной ввод 30.09 · победителя нет',s,tbl,lim+'<p>30 % — значение по умолчанию, как порог не утверждено. Шкала 6–18 €.</p>'+nop)};
/* ── панель «Как посчитано»: каскад (Recharts computeWaterfallData, перенос) и влияние цены ── */
function computeWaterfall(start,items){let run=start;const steps=[];for(const it of items){if(it.state==='known'&&typeof it.value==='number'){const top=run,bottom=run-it.value;steps.push({...it,bottom,top,len:it.value});run=bottom}else steps.push({...it,bottom:run,top:run,len:null})}
 const known=items.filter(i=>i.state==='known'),unknown=items.filter(i=>i.state==='unknown'),na=items.filter(i=>i.state==='not_applicable');return {steps,leftAfterKnown:run,knownCount:known.length,unknownNames:unknown.map(i=>i.name),notApplicable:na}}
LP.computeWaterfall=computeWaterfall;
LP.pCalc=function(id,adm){if(id!=='P01'){const e=E4[id];return e?`<div class="sg"><h3 class="h3">Пределы</h3><table class="tbl" data-density="comfortable"><tbody><tr><th scope="row">Предел при 30 %</th><td class="num">${e.ceiling_30.display}</td><td>${K.CALC}</td></tr><tr><th scope="row">Предел при 0 %</th><td class="num">${e.ceiling_0.display}</td><td>${K.CALC}</td></tr>${adm?'':`<tr><th scope="row">Предложение</th><td class="num">${e.offer.display}</td><td>${e.conditional?K.COND:K.FACT}</td></tr>`}</tbody></table></div><p class="nodata">Каскад и влияние цены для этой карточки: в демоданных нет.</p>`:`<p class="nodata">Расчёт для этой карточки: в демоданных нет.</p>`}
 const E5=D.charts.E5_costs;const items=E5.items.filter(i=>!(adm&&i.name==='Закупочная цена')).map(i=>({...i,value:i.value.cents}));
 const wf=computeWaterfall(E5.price.cents,items);const sc=v=>(v/E5.price.cents*100).toFixed(2)+'%';const col={FACT:'var(--teal)',CALC:'var(--lem)',SCENARIO:'var(--yel)'};
 let rows=`<div class="wf-row"><span class="op"></span><span class="nm">Цена листинга, с НДС</span><span class="bx"><i style="left:0;width:100%;--c:var(--teal)"></i></span><span class="vv">${f2(E5.price.cents/100)}</span></div>`;let sub=false;
 wf.steps.forEach(s=>{if(s.name==='Закупочная цена'&&!sub){sub=true;rows+=`<div class="wf-row tot"><span class="op">=</span><span class="nm">Остаётся до закупки · предел при 0 %<small>${K.CALC}</small></span><span class="bx"><i style="left:0;width:${sc(s.top)};--c:var(--lem)"></i></span><span class="vv">${f2(s.top/100)}</span></div>`}
  if(s.state==='known')rows+=`<div class="wf-row"><span class="op">−</span><span class="nm">${esc(s.name)}<small>${K[s.kind]}${s.note?' '+esc(s.note):''}</small></span><span class="bx"><i style="left:${sc(s.bottom)};width:${sc(s.len)};--c:${col[s.kind]}"></i></span><span class="vv">${f2(s.len/100)}</span></div>`;
  else if(s.state==='unknown')rows+=`<div class="wf-row"><span class="op">−</span><span class="nm">${esc(s.name)}<small>${esc(s.value===null?s.why||'':'')}</small></span><span class="bx"><span class="unkb" style="left:calc(${sc(s.bottom)} - 56px)" aria-hidden="true"></span></span><span class="vv"><span class="kx">неизвестно</span></span></div>`;
  else rows+=`<div class="wf-row"><span class="op"></span><span class="nm">${esc(s.name)}<small>не применимо: ${esc(E5.items.find(i=>i.name===s.name).value.why)}</small></span><span class="bx"></span><span class="vv"></span></div>`});
 rows+=`<div class="wf-row tot"><span class="op">=</span><span class="nm">${adm?'Остаётся до закупки':'По известным статьям'}<small>${K.CALC}</small></span><span class="bx"></span><span class="vv">${f2(wf.leftAfterKnown/100)}</span></div>`;
 const ttbl=`<table class="tbl" data-density="comfortable"><thead><tr><th scope="col">Статья</th><th scope="col" class="num">€ за 1 шт.</th><th scope="col">Вид знания</th></tr></thead><tbody>${E5.items.filter(i=>!(adm&&i.name==='Закупочная цена')).map(i=>`<tr><th scope="row">${esc(i.name)}</th><td class="num">${i.value.cents==null?`<span class="kx">${i.value.display}</span>`:f2(i.value.cents/100)}</td><td>${K[i.kind]||''}</td></tr>`).join('')}</tbody></table>`;
 const cas=`<figure class="fig"${av('prod')}><div class="fig-h"><div><p class="q">Из чего складывается предел?</p><p class="out">${adm?'Из 24,90 € до закупки остаётся 12,49 € — это предел при доходности 0 %.':'Из 24,90 € после известных статей и закупки 7,60 € остаётся 4,89 €.'}</p></div></div><p class="fig-meta">€ за 1 шт. · цена с НДС, статьи после НДС — без НДС · amazon.de, Keepa 30.09 18:05${adm?'':' · прайс 25.09'}</p><div>${rows}</div>
<div class="fig-n">по известным статьям: ${f2(wf.leftAfterKnown/100)} € · не учтено: ${wf.unknownNames.map(n=>n[0].toLowerCase()+n.slice(1)).join(', ')} — длины нет${adm?'':' · это не прибыль'}</div><div class="vt">${acc('t-wf','Таблица значений',ttbl)}</div></figure>`;
 const lv=`<div class="sg"><h3 class="h3">Пределы при доходности</h3><table class="tbl" data-density="comfortable"><tbody>${['0','10','20','30'].map(k=>`<tr${k==='30'?' aria-selected="true"':''}><th scope="row">${k} %${k==='30'?' · по умолчанию, как порог не утверждено':''}</th><td class="num">${D.P01_offer_economics.ceilings[k].display}</td><td>${K.CALC}</td></tr>`).join('')}</tbody></table></div>`;
 return cas+lv+priceImpact(adm)};
function piCalc(p){const pc=Math.round(p*100);const lvl=pc<=960?'проходит 30 %':pc<=1040?'проходит 20 %':pc<=1135?'проходит 10 %':pc<=1249?'проходит 0 %':'не проходит ни один уровень';return {d:960-pc,g:60*pc,r:(1249-pc)*60,lvl}}
LP.piCalc=piCalc;
function priceImpact(adm){const W=520,H=96,ml=8,mr=16,x=v=>ml+v/17*(W-ml-mr),p=S.price;
 let s=`<svg width="${W}" height="${H}" viewBox="0 0 ${W} ${H}" role="img" aria-labelledby="pi-t"><title id="pi-t">Закупочная цена на шкале пределов</title>`;
 const LV=[[12.49,'0 %'],[11.35,'10 %'],[10.40,'20 %'],[9.60,'30 %']];
 LV.forEach(([v,l],i)=>s+=`<path d="M${x(v).toFixed(1)} 14V70" stroke="${i===3?'#F2F4F8':'#8C95A7'}" ${i===3?'':'stroke-dasharray="3 3"'}></path>${i===0||i===3?`<text x="${x(v).toFixed(1)}" y="10" text-anchor="middle">${l}</text>`:''}`);
 s+=`<path d="M${ml} 44H${W-mr}" stroke="#2A3446"></path>`;
 const pts=[[7.60,'Предложение S1 · 7,60 € · '+K.FACT,'f'],[8.10,'Предложение S2 · 8,10 € · '+K.COND,'y'],[16.72,'Розница S3 · 16,72 € · сравнение, разница не считается','r']];
 if(!adm)pts.forEach((q,i)=>s+=`<g class="pt" data-i="${i}"><circle cx="${x(q[0]).toFixed(1)}" cy="44" r="5" fill="${q[2]==='f'?'#F2F4F8':'#0E131D'}" stroke="#F2F4F8" stroke-width="1.5" ${q[2]==='r'?'stroke-dasharray="2 2"':''}></circle></g>`);
 const pv=adm||p==null||isNaN(p)?null:p;
 if(pv!=null)s+=`<g class="pt" data-i="3"><rect x="${(x(pv)-5).toFixed(1)}" y="${44-5-14}" width="10" height="10" transform="rotate(45 ${x(pv).toFixed(1)} ${44-14})" fill="none" stroke="#F1FFCB" stroke-width="1.5"></rect></g>`;
 [0,4,8,12,16].forEach(v=>s+=`<text x="${x(v).toFixed(1)}" y="${H-6}" text-anchor="middle">${v} €</text>`);s+='</svg>';
 CH.pi={W,pts:adm?LV.map(([v,l])=>({x:x(v),y:44,t:'Предел при '+l+' · <b>'+f2(v)+' €</b> · '+K.CALC})):pts.map(q=>({x:x(q[0]),y:44,t:q[1]})).concat(pv!=null?[{x:x(pv),y:30,t:'Ваша цена · <b>'+f2(pv)+' €</b> · '+K.ASSUMED}]:[])};
 if(adm)return `<figure class="fig"${av('none')}><div class="fig-h"><div><p class="q">Какую доходность проходит цена и что остаётся?</p><p class="out">Расчётные пределы при доходности 0 / 10 / 20 / 30 %: 12,49 · 11,35 · 10,40 · 9,60 €.</p></div></div><p class="fig-meta">€ без НДС за 1 шт. · вертикали — расчётные пределы, не пороги решения</p><div class="chart" data-ch="pi" tabindex="0" role="group" aria-label="Шкала пределов — стрелки ← → перебирают значения">${s}</div><p class="why">ввод цены отключён в виде администратора</p></figure>`;
 const dis=adm?' disabled aria-disabled="true"':'';
 return `<figure class="fig" data-pi${av('none')}><div class="fig-h"><div><p class="q">Какую доходность проходит цена и что остаётся?</p><p class="out" id="pi-out1"></p></div></div><p class="fig-meta">€ без НДС за 1 шт. · вертикали — расчётные пределы, не пороги решения; 9,60 € — доходность 30 % — значение по умолчанию, как порог не утверждено</p>
<div class="chart" data-ch="pi" tabindex="0" role="group" aria-label="Шкала цены — стрелки ← → перебирают точки">${s}</div>
<div class="pi-ctl"><label class="t2" for="pi-n">Ваша цена, € без НДС</label><button class="btn btn-s sm" type="button" data-pd="-0.1" aria-label="Минус 0,10 €"${dis}>−</button><input id="pi-n" type="text" inputmode="decimal" autocomplete="off" value="${pv==null?'':pv.toFixed(2).replace('.',',')}"${dis}><button class="btn btn-s sm" type="button" data-pd="0.1" aria-label="Плюс 0,10 €"${dis}>+</button><input type="range" id="pi-r" min="0.1" max="16.7" step="0.1" value="${pv==null?7.6:pv}" aria-label="Цена, ползунок по 0,10 €"${dis}></div>
${adm?'<p class="why">ввод цены отключён в виде администратора: это действие над объектом клиента</p>':''}
<p class="t2">${K.ASSUMED} ваша цена · не записывается · результат — ${K.SCENARIO}</p><div class="pi-out" id="pi-o" aria-live="polite"></div><p class="t2">до доставки и неучтённых расходов — не прибыль · 7,40 € (ручное) в экономику не входит</p></figure>`}
function piBind(el){const n=$('#pi-n',el),r=$('#pi-r',el),o=$('#pi-o',el),o1=$('#pi-out1',el);
 const upd=()=>{const v=n.value===''?null:parseFloat(n.value.replace(',','.'));if(v==null||isNaN(v)){o.innerHTML='<div><span>Ваша цена</span><b>введите цену</b></div>';o1.textContent='Введите цену, чтобы увидеть уровень.';return}
  const p=Math.min(16.72,Math.max(0.01,v));S.price=p;const c=piCalc(p);
  o.innerHTML=T(`<div><span>Разница до предела при 30 %</span><b>${c.d<0?'−'+f2(-c.d/100)+' € · выше предела':f2(c.d/100)+' €'}</b></div><div><span>Товар при 60 шт.</span><b>${f2(c.g/100)} €</b></div><div><span>Результат по учтённой стоимости</span><b>${f2(c.r/100)} €</b></div><div><span>Уровень</span><b style="font-family:Onest">${c.lvl}</b></div>`);
  o1.innerHTML=T(`При ${f2(p)} € цена ${c.lvl}.`);r.value=p;
  const c2=el.querySelector('.chart');const svg=LP.$('svg',c2);const tmp=document.createElement('div');tmp.innerHTML=priceImpact(S.view==='admin');svg.replaceWith(tmp.querySelector('svg'))};
 n.addEventListener('input',upd);r.addEventListener('input',()=>{n.value=parseFloat(r.value).toFixed(2).replace('.',',');upd()});
 $$('[data-pd]',el).forEach(b=>b.addEventListener('click',()=>{if(b.disabled)return;const v=parseFloat((n.value||'7,6').replace(',','.'))+parseFloat(b.dataset.pd);n.value=Math.min(16.72,Math.max(0.01,v)).toFixed(2).replace('.',',');upd()}));upd()}
/* ── дашборд: предложение / предел ── */
LP.d1Chart=function(){const ids=['P01','P16','P13','P08','P07','P03'];const nm={P01:'Чайник',P16:'Салатница',P13:'Хлебница',P08:'Термокружка',P07:'Ножеточка',P03:'Мельница для перца'};const M=12;
 const note={P13:'данные рынка на 19.09 21:00',P08:'ваше решение «Одобрить покупку» 10.09 — решение не разрешает тратить капитал',P07:'условно: за штуку или за упаковку — не подтверждено',P03:'выше предела'};
 const rows=ids.map(i=>{const e=E4[i];return `<button class="pr-row" type="button" data-go="#/p/${i}" aria-label="${nm[i]}: предложение ${e.offer.display}, предел ${e.ceiling_30.display}, разница ${e.headroom.display}${note[i]?', '+note[i]:''}"><span>${nm[i]}</span><span class="trk" aria-hidden="true"><i class="ax"></i><i class="of${e.conditional?' y':''}" style="width:${(e.offer.cents/100/M*100).toFixed(2)}%"></i><i class="cl" style="left:${(e.ceiling_30.cents/100/M*100).toFixed(2)}%"></i></span><span class="pr-v">${f2(e.offer.cents/100)} / ${f2(e.ceiling_30.cents/100)} · ${f2(e.headroom.cents/100)}${note[i]?`<small>${note[i]}</small>`:''}</span></button>`}).join('');
 const tbl=`<div class="tbl-wrap" tabindex="0" role="region" aria-label="Таблица значений"><table class="tbl" data-density="dense" data-sort><thead><tr><th scope="col">Товар</th><th scope="col" class="num" aria-sort="none"><button class="sort" type="button">Предложение, €</button></th><th scope="col" class="num" aria-sort="none"><button class="sort" type="button">Предел при 30 %, €</button></th><th scope="col" class="num" aria-sort="none"><button class="sort" type="button">Разница, €</button></th><th scope="col">Вид знания</th></tr></thead><tbody>${ids.map(i=>{const e=E4[i];return `<tr><td>${nm[i]}</td><td class="num"><span data-v="${e.offer.cents}">${f2(e.offer.cents/100)}</span></td><td class="num"><span data-v="${e.ceiling_30.cents}">${f2(e.ceiling_30.cents/100)}</span></td><td class="num"><span data-v="${e.headroom.cents}">${f2(e.headroom.cents/100)}</span></td><td>${e.conditional?K.COND:K.FACT} · ${K.CALC}</td></tr>`}).join('')}</tbody><tfoot><tr><th scope="row" colspan="5">Отклонены правилом и не показаны: Сковорода 18,20 / 13,43 / −4,77; Овощерезка 4,20 / 5,39 — разницу карточка не даёт</th></tr></tfoot></table></div>`;
 return `<figure class="fig" aria-labelledby="d1q"${av('dev')}><div class="fig-h"><div><p class="q" id="d1q">У каких товаров предложение ниже расчётного предела — и насколько?</p><p class="out">Ниже предела — у пяти из шести; у Мельницы для перца предложение выше на 0,87 €.</p></div><div class="lgd"><span><i style="width:18px;height:8px;background:var(--lem);border-radius:2px"></i>предложение</span><span><i style="width:18px;height:8px;background:repeating-linear-gradient(135deg,var(--lem) 0 3px,var(--p1) 3px 6px)"></i>условно</span><span><i style="width:2px;height:16px;background:var(--ink)"></i>предел при 30 %</span></div></div>
<p class="fig-meta">€ без НДС за единицу продажи · предложение / предел · разница · текущие версии карточек · строка открывает карточку</p><div>${rows}<div class="pr-row" style="cursor:default" aria-hidden="true"><span></span><span class="scale">${[0,2,4,6,8,10,12].map(v=>`<span style="left:${(v/M*100).toFixed(2)}%">${v} €</span>`).join('')}</span><span></span></div></div>
<div class="fig-n"><span>до подготовки, хранения, возвратов и рекламы</span><span>доходность 30 % — значение по умолчанию, как порог не утверждено; комиссия 15 % — по умолчанию; доставка до склада 0,50 € — сценарий по умолчанию</span><span>данные рынка на 30.09 18:05; у Хлебницы — на 19.09 21:00; у Термокружки — на 01.10 06:00</span></div>
<div class="vt">${acc('t-d1','Таблица значений',tbl)}</div></figure>`};
/* ── Research ── */
const RS=D.research,B=RS.main_batch;
const lotRows=[{id:'BT-01',img:'../assets/img/q16.jpg',ru:'Складские остатки кухонных товаров',src:B.title_source,at:B.found.at,u:'партия / паллета от 2',m:'XLSX, 14 строк, EAN у 13',c:'новые, повреждено 84',t:'ЕС',loc:'Польша, Познань',pr:'3 480,00 €',pru:'за партию',prs:'средняя 2,90 € за ед.',prk:'CALC',dl:'08.10 18:00',fit:[['y','да'],['y','да; 84 ед. с повреждённой упаковкой — заявлено'],['y','да: PL'],['y','да: 3 480,00 — ФАКТ'],['y','да: от 2 паллет']],sum:'все условия, с оговоркой'}].concat(RS.other_batches.map(b=>({id:b.id,img:b.id==='BT-03'?'../assets/img/q36.jpg':null,gl:b.id==='BT-02'?'Т':'Т',ru:b.title,src:b.title_source,at:b.found_at,u:b.four_conditions[0].value,m:b.four_conditions[1].value,c:b.four_conditions[2].value,t:b.four_conditions[3].value,loc:b.location,...(m=>m?{pr:m[1]+' €',pru:m[2]}:{pr:b.price.value,pru:''})(b.price.value.replace(/\sбез НДС$/,'').match(/^(.+?)\s€\s(.*)$/)),prs:b.price.per_unit.display==='неизвестно'?'за ед. — неизвестно':'',dl:b.terms.match(/до (\d\d\.\d\d)/)[1],fit:{'BT-02':[['c','условно: бытовая техника'],['n','нет: C-Ware'],['y','да: DE'],['u','неизвестно: цена за кг, вес не назван'],['u','неизвестно: единица — кг']],'BT-03':[['y','да'],['y','да: A-Ware'],['n','нет: NL'],['y','да: 2 400 шт. × 0,68 € = 1 632,00 — РАСЧЁТ'],['u','неизвестно: единица — штука, от 600 шт.']],'BT-04':[['y','да: кухонный текстиль'],['p','частично: часть B-Ware'],['y','да: DE'],['n','нет: 9 800,00 — ФАКТ'],['y','да: 33 паллеты']]}[b.id],sum:{'BT-02':'не соответствует: состояние','BT-03':'не соответствует: страна','BT-04':'не соответствует: бюджет, состояние'}[b.id]})));
const MT={y:'mt y',n:'mt n',p:'mt p',c:'mt c',u:'mt u'};
const fitK=s=>esc(s).replace(' — ФАКТ',' '+K.FACT).replace(' — РАСЧЁТ',' '+K.CALC).replace(' — заявлено',' '+K.CLAIM);
const LH=['Кухня и дом','Новые','PL, DE','≤ 5 000,00 €','От 1 паллеты'];
function rsBlock(){return S.view==='admin'?`<main class="main"><h1 class="h1">LotPrism Research</h1><p class="adm-note">Это демонстрация вида. Разграничение доступа выполняется сервером и в продукте не реализовано; скрытая кнопка в макете не означает запрета</p><p class="hide">Партии, покупатели и обращения клиента — частные данные пространства скрыты.</p></main>`:null}
LP.rsEntry=function(){const a=rsBlock();if(a)return a;
 const fitN=l=>l.fit.filter(f=>f[0]==='y').length;
 return `<main class="main"${av('hyp')}><div class="pg-h"><h1 class="h1">Партии и покупатели</h1><p class="t2">LotPrism Research · Demo-Handel GmbH · на 01.10.2026 10:00</p></div>
<div class="ent"><section class="en2"><span class="eyebrow">Вход 1</span><h2 class="h2">Найти партию для перепродажи</h2><p class="t2">Текущий запрос</p><div class="chips"><span>кухня и дом</span><span>новые</span><span>Польша, Германия</span><span>до 5 000,00 € без НДС</span><span>от 1 паллеты</span></div>
<p class="t2 ink">Поиска по запросу пользователя в продукте нет: эти партии нашла задача команды LotPrism 29–30.09.</p><div style="display:flex;gap:12px;align-items:center;flex-wrap:wrap"><button class="btn btn-p" type="button" aria-disabled="true" aria-describedby="srch-w">Искать по запросу</button><span class="why" id="srch-w">недоступно: поиска по запросу пользователя в продукте нет</span></div></section>
<section class="en2"><span class="eyebrow">Вход 2</span><h2 class="h2">Оценить предложение и найти покупателей</h2><p class="t2">Для того, у кого уже есть предложение партии: прайс, манифест или ссылка.</p><div style="display:flex;gap:8px;flex-wrap:wrap"><button class="btn btn-s" type="button" data-act="na" data-what="Выбрать файл" data-msg="в прототипе не загружается">Выбрать файл</button><button class="btn btn-s" type="button" data-act="na" data-what="Вставить ссылку" data-msg="в прототипе не загружается">Вставить ссылку</button><button class="btn btn-s" type="button" data-act="na" data-what="Ввести вручную" data-msg="в прототипе не загружается">Ввести вручную</button></div><p class="t2">В прототипе ничего не загружается. При ручном вводе теряются упаковка, минимальный заказ, доставка, единица продажи и состояние.</p></section></div>
<section class="sec"><div class="sec-h"><h2 class="h2">Найдено по текущему запросу · 4</h2><p class="t2">порядок — по времени, когда партия найдена; общего «подходит» и вердикта нет · строка открывает партию</p></div>
<ul class="rows lots">${lotRows.map(l=>`<li class="lot2" data-go="#/research/${l.id}">${l.img?`<img class="th" src="${l.img}" alt="Иллюстрация" width="56" height="70">`:`<span class="ph th" role="img" aria-label="Заглушка: ${esc(l.ru)}"></span>`}<div class="lot2-c"><p class="lot2-t"><a href="#/research/${l.id}"${l.id==='BT-01'?'':' aria-describedby="lot-na"'}>${esc(l.ru)}</a> <span class="code">${l.id.replace('-','')}</span></p><p class="t2" lang="de">«${esc(l.src)}» · найдена ${fdt(l.at)}</p>
<dl class="lot2-f"><div><dt>Цена без НДС</dt><dd><span class="n">${esc(l.pr)}</span> ${esc(l.pru||'')}${l.prs?`<span class="kx">${esc(l.prs)}${l.prk?' '+K[l.prk]:''}</span>`:''}</dd></div><div><dt>Срок</dt><dd class="n">до ${esc(l.dl)}</dd></div><div><dt>Единица</dt><dd>${esc(l.u)}</dd></div><div><dt>Манифест</dt><dd>${esc(l.m)}</dd></div><div><dt>Состояние · заявлено</dt><dd>${esc(l.c)}</dd></div><div><dt>Территория · место</dt><dd>${esc(l.t)} · ${esc(l.loc)}</dd></div></dl>
<div class="lot2-m">${acc('fit-'+l.id,`<span class="sq">совпадает с запросом: ${fitN(l)} из ${LH.length} условий</span><span class="tot">${esc(l.sum)}</span>`,`<ul class="fitl">${LH.map((h,i)=>`<li><span class="fit-c">${h}</span><span class="${MT[l.fit[i][0]]}">${fitK(l.fit[i][1])}</span></li>`).join('')}</ul>`)}</div></div></li>`).join('')}</ul>
<p class="t2" id="lot-na">Подробно в прототипе открыта только партия из Познани; остальные открывают ту же страницу партии с данными, которые есть.</p></section></main>`};
K.HYP='<span class="k hy">ГИПОТЕЗА</span>';
const rg=(lo,hi)=>lo<0||hi<0?`${f2(lo/100)} … ${f2(hi/100)} €`:`${f2(lo/100)}–${f2(hi/100)} €`;
const hyp=s=>esc(s).replace(/\s*\(ГИПОТЕЗА\)/g,' '+K.HYP);
LP.rsLot=function(id){const a=rsBlock();if(a)return a;if(id!=='BT-01'){const l=lotRows.find(x=>x.id===id);return `<main class="main"><a href="#/research">← Партии по запросу</a><h1 class="h1">${esc(l.ru)}</h1><p class="t2" lang="de">«${esc(l.src)}»</p><p class="nodata">Подробная страница этой партии: в демоданных нет. ${esc(RS.other_batches.find(b=>b.id===id).fit)}</p></main>`}
 const R=RS.routes,X=D.charts.E10_delivery_scenario.batch,BY={};RS.buyers.forEach(b=>BY[b.id]=b);
 const path=['Партия','Состав и условия','Варианты сбыта','Экономика и неизвестные','Покупатели','Следующий шаг'];
 /* Partition Bar (8starlabs): сегмент ∝ единицам по манифесту; вид — основание сбыта */
 const units={'RT-1':[[1200,'asm','вся партия · цена — ваше допущение · покупатель не подтверждён']],'RT-2':[[460,'int','лот А · паллеты 1, 3 · необязывающий интерес, количество не названо'],[380,'asm','лот Б · паллеты 2, 4 · ваше допущение'],[360,'asm','лот В · паллеты 5, 6 · ваше допущение']],'RT-3':[[668,'asm','FBA · 9 позиций · по ценам листингов 30.09 · СЦЕНАРИЙ · продаж нет'],[532,'asm','остаток одним лотом · ваше допущение']],'RT-4':[[1150,'asm','2 сети остатков · ваше допущение'],[50,'out','поз. 13 без EAN · вне маршрута']]};
 const PBK={fact:'состав по манифесту',asm:'ваше допущение',int:'необязывающий интерес',out:'вне маршрута'};
 const dist=R.map(r=>`<div class="pb-r"><p class="pb-n">${esc(r.name)}</p><ul class="pbar" aria-label="${esc(r.name)}: ${esc(units[r.id].map(u=>fi(u[0])+' ед. — '+PBK[u[1]]+': '+u[2]).join('; '))}">${units[r.id].map(u=>`<li class="pb-${u[1]}" style="flex:${u[0]} 1 0"></li>`).join('')}</ul><ul class="pb-l" aria-hidden="true">${units[r.id].map(u=>`<li><i class="pb-${u[1]}"></i><b class="n">${fi(u[0])} ед.</b><span>${esc(u[2])}</span></li>`).join('')}</ul></div>`).join('');
 const xi=S.x,xv=X.x_values[xi];const lo=-1000,hi=1300,P=v=>((v-lo)/(hi-lo)*100).toFixed(2);
 const rng=X.rows.map(r=>{const v=r.values[xi];const a=v.low.cents/100,b=v.high.cents/100;return `<div class="out-row"><span>${esc(r.name)}${!r.affected?'<span class="t2" style="display:block">применимость доставки неизвестна: согласие на самовывоз третьим лицом не спрашивали</span>':''}</span><span class="rng" role="img" aria-label="${esc(r.name)}: ${v.low.display} … ${v.high.display}"><i class="ax"></i><i class="z0" style="left:${P(0)}%"></i><i class="rn" style="left:${P(a)}%;width:${(P(b)-P(a))}%"></i></span><span class="pr-v">${rg(v.low.cents,v.high.cents)}</span></div>`}).join('');
 const pos=B.positions;
 const comp=`<div class="tbl-wrap" tabindex="0" role="region" aria-label="Состав партии"><table class="tbl" data-density="dense" data-sort><caption class="sr-only">Состав партии · 14 позиций</caption><thead><tr><th scope="col">Поз.</th><th scope="col">Название</th><th scope="col" class="num" aria-sort="none"><button class="sort" type="button">шт.</button></th><th scope="col" class="num">повр.</th><th scope="col" class="num">паллета</th><th scope="col" class="num" aria-sort="none"><button class="sort" type="button">Листинг, € с НДС</button></th><th scope="col" class="num" aria-sort="none"><button class="sort" type="button">Предел 30 %, €</button></th><th scope="col">Отбор шорт-листа — скрипт команды, не вердикт</th></tr></thead><tbody>
${pos.map(p=>`<tr><td class="code">${p.id.slice(-2)}</td><td>${esc(p.title_ru)}</td><td class="num"><span data-v="${p.qty}">${p.qty}</span></td><td class="num">${p.damaged_pack_declared}</td><td class="num">${p.pallet}</td><td class="num">${p.amazon?`<span data-v="${p.amazon.price_gross.cents}">${f2(p.amazon.price_gross.cents/100)}</span>`:p.ean_state==='no_ean'?`<span class="ms na">${IC.na}не применимо: нет EAN</span>`:`<span class="kx">не найдено этим поиском на 01.10</span>`}</td><td class="num">${p.amazon?`<span data-v="${p.amazon.ceilings['30'].cents}">${f2(p.amazon.ceilings['30'].cents/100)}</span>`:''}</td><td>${p.amazon?(p.amazon.shortlist_gate?'прошла':'не прошла: '+esc(p.amazon.gate_fail_reason)):`<span class="ms na">${IC.na}не применимо</span>`}</td></tr>`).join('')}</tbody><tfoot><tr><th scope="row" colspan="2">Всего</th><td class="num">${B.units}</td><td class="num">${B.damaged_total_declared}</td><td class="num">${B.pallets_count}</td><td colspan="3"><span class="t2">цена позиции — неизвестно: продавец продаёт партией или паллетами</span></td></tr></tfoot></table></div>`;
 /* сравнение маршрутов — originui Table, раскладка Comparison 02: маршруты в столбцах, без выделенного столбца и призыва */
 const byShort=id=>{const b=BY[id];return `${esc(b.name.split(':')[0].replace(' (демо)',''))} · ${esc(b.region.split(',')[0])}<span class="sub">${esc(b.confirmation.label)}</span>`};
 const CR=[['Форма сделки',r=>esc(r.form)],['Покупатели и подтверждение',r=>`<ul class="cmp-l">${r.buyers.map(b=>`<li>${byShort(b)}</li>`).join('')}</ul>`],['Поступления',r=>`<span class="n">${rg(r.revenue.low.cents,r.revenue.high.cents)}</span> ${K.SCENARIO}`],['Известные расходы',r=>`<span class="n">${r.known_costs_total.display}</span><span class="sub">${esc(r.known_costs.map(k=>k.what).join('; '))}</span>`],['Неизвестные расходы',r=>{const u=r.unknown_costs.filter(x=>x.kind==='UNKNOWN'),na=r.unknown_costs.filter(x=>x.kind==='NOT_APPLICABLE');return `<b class="n">${u.length}</b> неизвестно<ul class="cmp-l">${u.map(x=>`<li>${esc(x.what)}${x.amount&&x.amount.why?`<span class="sub">${esc(x.amount.why)}</span>`:''}</li>`).join('')}</ul>${na.length?`<p class="cmp-na">не применимо: ${na.map(x=>esc(x.what)+(x.amount&&x.amount.why?' — '+esc(x.amount.why):'')).join('; ')}</p>`:''}`}],['Результат до неизвестных',r=>`<span class="n">${rg(r.result_before_unknown.low.cents,r.result_before_unknown.high.cents)}</span> ${K.SCENARIO}`],['Пик денег',r=>`<span class="n">${r.cash_need.peak.display}</span> ${K.CALC}<span class="sub">${esc(r.cash_need.peak.note||'')}</span>`],['Срок',r=>hyp(r.timing)],['Остаток',r=>`<span class="n">${fi(r.remainder.units)} ед.</span><span class="sub">${esc(r.remainder.note)}</span>`],['Риски',r=>`<ul class="cmp-l">${r.risks.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`]];
 const cmpT=`<div class="tbl-wrap cmp-w" tabindex="0" role="region" aria-label="Сравнение вариантов сбыта"><table class="tbl cmp" data-density="comfortable"><caption class="sr-only">Варианты сбыта в столбцах, свойства в строках; лучшего варианта нет</caption><thead><tr><th scope="col"><span class="sr-only">Свойство</span></th>${R.map(r=>`<th scope="col">${esc(r.name)}</th>`).join('')}</tr></thead><tbody>${CR.map(([n,f])=>`<tr><th scope="row">${n}</th>${R.map(r=>`<td>${f(r)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
 /* покупатели на шкале подтверждения (buyer_ladder) */
 const lvl=b=>b.confirmation.level==='indicative_interest'?2:b.match_basis.kind==='published_request'?1:0;
 const byAct=b=>b.id==='BY-1'?`<button class="btn btn-s sm" type="button" data-act="draft">Открыть черновик</button>`:b.contact_basis.kind==='cold'?`<span class="why">e-mail не предлагается: без согласия запрещён и в B2B</span>`:`<button class="btn btn-s sm" type="button" data-act="na" data-what="Подготовить обращение" data-msg="в прототипе не создаётся, ничего не отправляется">Подготовить обращение</button>`;
 const byCard=b=>`<li class="by"><p class="by-n"><b>${esc(b.name.split(':')[0].replace(' (демо)',''))}</b> · ${esc(b.region)}<span class="t2"> · ${esc(b.type)}</span></p><p class="t2">${esc(b.match_basis.label)} · ${esc(b.match_basis.detail)}</p>${b.confirmation.level==='indicative_interest'?`<p class="by-q">${esc(b.confirmation.statement)} <span class="t2">· ${fdt(b.confirmation.received_at)}</span></p><p class="by-p"><span class="n">${esc(R[1].lots[0].price_range)}</span> за ед. · ориентировочно <span class="k y">НЕОБЯЗЫВАЮЩЕ</span></p>`:`<p class="t2">запрос или профиль: ${esc(b.interest)}</p>`}<p class="by-a"><span class="t2">канал: ${esc(b.contact_basis.allowed_channels.join('; '))}</span>${byAct(b)}</p></li>`;
 const lad=`<ol class="lad">${RS.buyer_ladder.map((s,i)=>{const bs=RS.buyers.filter(b=>lvl(b)===i);return `<li class="lad-s${bs.length?'':' lad-e'}"><p class="lad-h"><span class="lad-i">${i+1}</span>${esc(s)}<span class="t2 nw">&nbsp;·&nbsp;${bs.length}</span></p>${bs.length?`<ul class="by-l">${bs.map(byCard).join('')}</ul>`:`<p class="lad-0">нет</p>`}</li>`}).join('')}</ol>`;
 const O=RS.outreach[0];
 return `<main class="main rs-lot" style="gap:32px"${av('hyp')}><a href="#/research">← Партии по запросу</a>
<nav class="rs-path" aria-label="Путь по партии">${path.map((p,i)=>`<button type="button" data-act="jump" data-to="st${i+1}"><i>${i+1}</i>${p}</button>`).join('')}</nav>
<section id="st1" class="sec"><div style="display:grid;grid-template-columns:72px minmax(0,1fr);gap:16px;align-items:start" class="cd-h"><figure><img class="pic" style="width:72px;height:90px" src="../assets/img/q16.jpg" alt="" width="72" height="90"><figcaption class="illu">иллюстрация</figcaption></figure><div class="ttl"><span class="eyebrow">1 · Партия <span class="code">BT01</span></span><h1 class="h1">Складские остатки кухонных товаров, Познань</h1><p class="orig" lang="de" title="${esc(B.title_source)}">«${esc(B.title_source)}»</p><p>${esc(B.seller.type)}, ${esc(B.seller.city)} · ${B.positions_count} позиций, ${B.pallets_count} паллет, ${fi(B.units)} ед. · найдена ${fdt(B.found.at)}</p><p class="t2">вердикта нет · ниже — что известно о сбыте и что держит сделку</p></div></div>
<div class="z5 z2"><section><span class="eyebrow">Что важно</span><p class="big">${B.price.lot_net.display}</p><span>${K.FACT} <span class="kx">без НДС за партию</span></span><ul><li>срок до 08.10 18:00</li><li>предоплата 100 %, возврат не принимается, гарантия исключена</li><li>84 ед. с повреждённой упаковкой (7,0 %) — ${K.CLAIM}</li><li>фото 2 из 6 паллет</li></ul></section>
<section><span class="eyebrow">Чего не хватает</span><ul><li>${K.UNKNOWN} доставка</li><li><span class="ms chk">ещё не проверен</span> поставщик партии</li><li>${K.UNKNOWN} документы происхождения</li><li>НДС: сценарий А — 0 %, номер в VIES не подтверждён; «счёт с НДС» указывает на сценарий Б, ставка неизвестна</li><li>Твёрдых цен покупатели не называли: у Баварии — необязывающий ориентир 3,40–3,60 € к паллетам 1 и 3, остальные цены — ${K.ASSUMED}</li></ul></section></div>
<p class="step-to"><button class="lnk" type="button" data-act="jump" data-to="st6">Следующий шаг →</button></p></section>
<section id="st2" class="sec"><div class="sec-h"><span class="st-n">2</span><h2 class="h2">Состав и условия</h2></div><p class="fig-meta">шт. · повр. · паллета — ${K.CLAIM} по манифесту · листинг — ${K.FACT} amazon.de, 30.09 · предел 30 % — ${K.CALC}</p>${comp}<p class="t2">Паллеты: ${B.pallets.map(p=>p.pallet+' — '+p.units+' ед.').join(' · ')}</p>
<div class="tbl-wrap" tabindex="0" role="region" aria-label="Условия закупки"><table class="tbl tbl-st" data-density="dense"><tbody>${B.terms.map(t=>`<tr><th scope="row">${esc(t.what)}</th><td>${typeof t.value==='string'?esc(t.value):`<span class="ms u">${esc(t.value.display)}</span> <span class="kx">${esc(t.value.why||'')}</span>`}</td><td>${K[t.kind]||''}</td></tr>`).join('')}<tr><th scope="row">6 паллет поштучно</th><td>${B.price.six_pallets_by_pallet.display} · ${esc(B.price.six_pallets_by_pallet.basis)}</td><td>${K.CALC}</td></tr><tr><th scope="row">Заявленная розничная стоимость</th><td>${B.price.declared_retail_value.display} · якорь продавца, не цена перепродажи</td><td>${K.FACT}</td></tr></tbody></table></div></section>
<section id="st3" class="sec"><div class="sec-h"><span class="st-n">3</span><h2 class="h2">Варианты сбыта · 4 способа на равных</h2><p class="t2">числа — ${K.SCENARIO}, € без НДС, до неизвестных расходов и до доставки из Познани · допущения цен — ваше допущение · Томас Вебер · экономика v2, 01.10 08:40 · общего балла и «лучшего» варианта нет</p></div>
<figure class="fig"><div class="fig-h"><div><p class="q">Как партия расходится по вариантам сбыта?</p><p class="out">Предполагаемое распределение — продаж и подтверждённого спроса нет.</p></div><div class="lgd">${Object.entries(PBK).map(([k,v])=>`<span><i class="pb-k pb-${k}"></i>${v}</span>`).join('')}</div></div><p class="fig-meta">1 200 ед. по манифесту на каждый вариант · длина сегмента — число единиц ${K.CLAIM} · вид — основание сбыта</p><div class="dist2">${dist}</div></figure>
${cmpT}</section>
<section id="st4" class="sec"><div class="sec-h"><span class="st-n">4</span><h2 class="h2">Экономика и неизвестные</h2></div>
<figure class="fig"><div class="fig-h"><div><p class="q">Что даёт каждый вариант до неизвестных и как зависит от доставки?</p><p class="out">При доставке Познань → склад = ${xv.display} · диапазоны ${K.SCENARIO}</p></div><div class="seg" role="radiogroup" aria-label="Доставка Познань → склад, X">${X.x_values.map((v,i)=>`<button type="button" role="radio" aria-checked="${i===xi}" tabindex="${i===xi?0:-1}" data-act="xset" data-i="${i}">${v.display.replace(',00','')}</button>`).join('')}</div></div>
<p class="fig-meta">результат, € без НДС · ось −1 000…1 300 €, линия — 0 € · значения из данных, не пересчитываются · цена доставки неизвестна; X — для сравнения, не оценка</p><div class="rng-w">${rng}<div class="out-row" aria-hidden="true" style="min-height:20px"><span></span><span class="rng-scale">${[-1000,-500,0,500,1000].map(v=>`<span style="left:${P(v)}%">${v<0?'−':''}${fi(Math.abs(v))} €${v===0?' · ноль':''}</span>`).join('')}</span><span></span></div></div>
<div class="vt">${acc('t-rng','Таблица значений',`<div class="tbl-wrap" tabindex="0" role="region" aria-label="Таблица значений: результат при доставке X"><table class="tbl" data-density="dense"><thead><tr><th scope="col">Способ</th>${X.x_values.map(v=>`<th scope="col" class="num">X = ${v.display}</th>`).join('')}</tr></thead><tbody>${X.rows.map(r=>`<tr><td>${esc(r.name)}</td>${r.values.map(v=>`<td class="num">${rg(v.low.cents,v.high.cents)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`)}</div></figure>
<div class="sg"${av('none')}><h3 class="h3">Препятствия</h3><ul class="lm"><li><span class="lt">${K.UNKNOWN} доставка</span></li><li><span class="lt">фото 4 паллет — нет</span></li><li><span class="lt"><span class="ms chk">не проверен</span> поставщик партии</span></li><li><span class="lt">${K.UNKNOWN} документы происхождения</span></li><li><span class="lt">НДС — сценарий А или Б</span></li><li><span class="lt"><span>регистрации для продажи в Германии: VerpackG / LUCID; у поз.&nbsp;<span class="code">04</span> — ElektroG, вероятно BattG · применимость неизвестна</span></span></li><li><span class="lt">возврат не принимается</span></li></ul></div></section>
<section id="st5" class="sec"><div class="sec-h"><span class="st-n">5</span><h2 class="h2">Потенциальные покупатели</h2><p class="t2">компании, гипотеза · каждый стоит на своей ступени подтверждения · отправки из LotPrism нет</p></div>
${lad}
<div class="sg" id="draft"${S.draft?'':' hidden'}><h3 class="h3">Черновик обращения · Дортмунд</h3><p class="t2" id="draft-st">черновик · юристом не проверен · ${S.sent?'отмечено вами как отправленное · сейчас':'не отправлен'}</p><p class="t2 ink"><b style="font-weight:600">Внимание:</b> паллеты 1 и 3 предложены двум покупателям · OUT-1 — вся партия; Бавария — интерес к паллетам 1 и 3 (30.09)</p><p class="t2">${esc(O.subject_de)}</p><div class="draft" lang="de">${esc(O.body_de)}</div><p class="t2">Не попадает в текст: ${O.excluded.join(', ')}.</p><div id="sent-ctl" style="display:flex;gap:8px;flex-wrap:wrap;align-items:center">${S.sent?'':`<button class="btn btn-s" type="button" data-act="sent" id="sent-btn" data-state="idle" aria-describedby="send-rule" style="min-width:min(340px,100%)">Отметить отправленным вами</button>`}</div><span class="why" id="send-rule">${esc(O.send_rule)}</span></div></section>
<section id="st6" class="sec"${av('des')}><div class="sec-h"><span class="st-n">6</span><h2 class="h2">Следующий шаг</h2><p class="t2">из данных партии · действия выполняете вы, LotPrism ничего не отправляет</p></div><ul class="nx-l"><li class="nx">Выбрать способ доставки и запросить цену для 6 паллет</li><li class="nx">Запросить фото паллет 1, 3, 5, 6</li></ul></section></main>`};
/* ── вид администратора ── */
LP.adminDash=function(){const A=D.admin,k=A.sources.keepa;
 const vis=[['да',A.errors_24h.filter(e=>e.user_visible.startsWith('да'))],['нет',A.errors_24h.filter(e=>e.user_visible==='нет'&&!/429/.test(e.what))],['не ошибка',A.errors_24h.filter(e=>/429/.test(e.what))]];
 const ev=(e,i)=>`<li><button class="ev" type="button" data-act="acc" data-id="ev${i}" aria-expanded="${S.open['ev'+i]?'true':'false'}" aria-controls="acc-ev${i}"><span class="tm">${fdt(e.at)}</span><span><b style="font-weight:500">${esc(e.where)}</b> · ${esc(e.what)}</span><span class="chev" aria-hidden="true">${IC.chv}</span></button><div class="acc-b ev-b" id="acc-ev${i}" ${S.open['ev'+i]?'':'hidden'}>${esc(e.detail_policy||'')}${e.where.startsWith('DS1')?' · у клиентов: «обновление данных рынка не удалось», данные на 30.09 18:05 · лимит исследователя исчерпан до 03.10 09:00 — что станет с заданиями клиентов, не определено':''}</div></li>`;
 let n=0;
 return `<main class="main"${av('hyp')}><div class="pg-h"><h1 class="h1">Состояние платформы</h1><p class="t2">на 01.10.2026 10:00 · период ${fdt(A.period.from)}–${fdt(A.period.to)}</p></div><p class="adm-note">Это демонстрация вида. Разграничение доступа выполняется сервером и в продукте не реализовано; скрытая кнопка в макете не означает запрета</p>
<section class="sec"${av('svc')}><h2 class="h2">Сводка сервисов</h2><div class="svc">${A.services.map(s=>`<div><b style="font-weight:500">${esc(s.name)}</b><span>${s.state==='неизвестно'?'<span class="ms u">неизвестно</span>':esc(({available:'доступен','commercial_freeze снят':'заморозка коммерческих задач снята'})[s.state]||s.state)}</span><span class="mono">${esc(s.detail||'')}</span></div>`).join('')}</div></section>
<section class="sec"${av('svc')}><h2 class="h2">Требует внимания</h2><p class="t2">первая группировка — «видно клиентам»; цвета «работает / сбой» нет</p>${vis.map(([h,l])=>`<h3 class="eyebrow" style="margin-top:8px">Видно клиентам · ${h}</h3><ul class="rows">${l.map(e=>ev(e,n++)).join('')}</ul>`).join('')}
<ul class="rows"><li><button class="ev" type="button" data-act="acc" data-id="evq" aria-expanded="${S.open.evq?'true':'false'}" aria-controls="acc-evq"><span class="tm">до 03.10 09:00</span><span><b style="font-weight:500">Лимит исследователя исчерпан</b> · видно клиентам: да</span><span class="chev" aria-hidden="true">${IC.chv}</span></button><div class="acc-b ev-b" id="acc-evq" ${S.open.evq?'':'hidden'}>${esc(A.sources.llm_researcher.quota)} · раундов за период ${A.sources.llm_researcher.rounds_period} · стоимость — неизвестно · что станет с заданиями клиентов, не определено</div></li></ul></section>
<section class="sec"${av('svc')}><h2 class="h2">Ёмкость Keepa</h2><p><span class="big">${k.tokens_left_now}</span> <span class="t2">из ${fi(k.bucket)} токенов сейчас · пополнение ${k.refill_per_minute} в минуту</span></p><p class="t2">За период: израсходовано ${fi(k.spend_total)} из ${fi(k.refill_period)}; не использовано ${fi(k.unused_period)} · расход по клиентам — неизвестно: ${esc(k.per_client.why)}</p></section>
<section class="sec"><h2 class="h2">Что администратор не видит</h2><ul class="lm">${A.private_data.does_not_see.map(d=>`<li><span class="lt">${esc(d.what)}</span><p>${esc(d.basis)}</p></li>`).join('')}</ul><h3 class="h3">Только состояние, переключателей нет</h3><table class="tbl" data-density="dense"><tbody>${A.read_only_switches.map(s=>`<tr><th scope="row">${esc(s.what)}</th><td>${esc(s.state)}</td></tr>`).join('')}</tbody></table></section></main>`};
LP.adminCard=function(id){const r=REG[id],sg=id==='P01'?D.P01_explanation_v1:null;
 return `<main class="cd" id="cd"${av('hyp')}><p class="adm-note">Это демонстрация вида. Разграничение доступа выполняется сервером и в продукте не реализовано; скрытая кнопка в макете не означает запрета</p>
<div class="cd-h" style="grid-template-columns:minmax(0,1fr) auto"><div class="ttl"><span class="eyebrow">Общая карточка рынка · без владельца</span><h1 class="h1" id="cd-h1" style="font-size:var(--f22)">${esc(r.title_ru)}</h1><p class="t2" lang="de">${esc(r.title_listing)}</p></div><div class="acts"><button class="btn btn-s sm" type="button" data-act="panel" data-tab="calc" data-pf="calc-btn">Как посчитано</button></div></div>
<section class="hero"><div><span class="eyebrow">Рынок</span><dl class="kv">${sg?sg.signals.filter(s=>s.section!=='economics'&&s.section!=='ml').map(s=>`<div><dt>${esc(s.line)}</dt><span class="kd">${K[s.kind]}<span class="kx">${esc(s.source)}</span></span><dd>${esc(s.value)}</dd></div>`).join(''):'<div><dt>Показания</dt><span class="kd"></span><dd><span class="kx">в демоданных нет</span></dd></div>'}</dl><p class="t2">источник ${esc(r.freshness.source)} · ответ провайдера ${fdt(r.freshness.provider_answered_at)}</p></div>
<div${av('svc')}><span class="eyebrow">Качество данных</span><ul class="lm"><li><span class="lt"><span class="ms nu">${IC.clkd}ошибка источника с 30.09 23:40</span></span><p>DS1 Keepa · кухня · данные частичные: новые наблюдения не приходят</p></li><li><span class="lt">Свежесть</span><p>${esc(r.freshness.engine_gate.id)} ${esc(r.freshness.engine_gate.test)} · ${String(r.freshness.engine_gate.value_days).replace('.',',')} дн. · ${r.freshness.engine_gate.outcome==='held'?'держится':'не держится'}</p></li></ul>
${sg?`<span class="eyebrow">Ворота рынка</span><div class="tbl-wrap" tabindex="0" role="region" aria-label="Ворота рынка"><table class="tbl" data-density="dense"><tbody>${sg.decision.gates.map(g=>`<tr><td class="mono" style="font-size:var(--f13);word-break:break-all">${esc(g.id)}</td><td class="num">${esc(String(g.value))}${g.unit?' '+esc(g.unit):''}</td><td>${esc(g.test==='not on the listing'?'нет на листинге':g.test)}</td><td>${g.outcome==='held'?'держится':esc(g.outcome)}</td></tr>`).join('')}</tbody></table></div>`:''}
<span class="eyebrow">Состояние платформы для этого товара</span><p>Лимит исследователя исчерпан до 03.10 09:00; что будет с заданиями — не определено.</p>
<span class="eyebrow">Ошибки</span><p class="t2">30.09 23:40 · DS1 Keepa · кухня · синхронизация failed · текст ошибки в браузер не отдаётся</p>
<div style="display:flex;gap:12px;align-items:center;flex-wrap:wrap"><button class="btn btn-s" type="button" data-act="na" data-what="Повторить обновление источника">Повторить обновление источника</button><span class="why">расход неизвестен</span></div></div></section>
<p class="hide">Частные данные пространства скрыты: предложение поставщика и его экономика, ворота предложения, статусы проверки предложений, итог и содержимое задания, решение, мнения, список «Перепродажа · 13».</p>
<div style="display:flex;gap:12px;align-items:center;flex-wrap:wrap"><button class="btn btn-p" type="button" aria-disabled="true" aria-describedby="adm-w">Записать решение</button><button class="btn btn-s" type="button" aria-disabled="true" aria-describedby="adm-w">Запустить анализ</button><span class="why" id="adm-w">недоступно в виде администратора: действия над объектами клиента отключены</span></div></main>`};
/* ── действия Research ── */
Object.assign(LP.ACT,{
 route:b=>{S.route=b.dataset.id;LP.route();const f=$(`[data-act=route][data-id="${S.route}"]`);f&&f.focus()},
 xset:b=>{S.x=+b.dataset.i;LP.route();const f=$(`[data-act=xset][data-i="${S.x}"]`);f&&f.focus()},
 jump:b=>{const t=$('#'+b.dataset.to);if(t){const pth=b.closest('.rs-path');if(pth){LP.setStep&&LP.setStep(b.dataset.to,true)}scrollTo({top:t.getBoundingClientRect().top+scrollY-(document.querySelector('.rs-path')?128:80)});const h=t.matches('h1,h2')?t:($('h1,h2',t)||t);h.tabIndex=-1;h.focus({preventScroll:true})}},
 draft:()=>{S.draft=true;const d=$('#draft');d.hidden=false;scrollTo({top:d.getBoundingClientRect().top+scrollY-120});$('h3',d).tabIndex=-1;$('h3',d).focus({preventScroll:true})},
 sent:b=>{if(b.dataset.state!=='confirm'){b.dataset.state='confirm';b.textContent='Подтвердить: отправлено вами вне LotPrism';const c=document.createElement('button');c.type='button';c.className='btn btn-s';c.dataset.act='sentx';c.textContent='Отмена';b.after(c);clearTimeout(S.sentT);S.sentT=setTimeout(sentReset,8000);return}
  clearTimeout(S.sentT);S.sent=true;$('#sent-ctl').innerHTML='';$('#draft-st').textContent='черновик · юристом не проверен · отмечено вами как отправленное · сейчас';LP.announce('Отмечено вами как отправленное. Из LotPrism ничего не отправлено');const h=$('#draft h3');h.tabIndex=-1;h.focus()},
 sentx:()=>{sentReset();const b=$('#sent-btn');b&&b.focus()}
});
function sentReset(){clearTimeout(S.sentT);const b=$('#sent-btn');if(!b)return;b.dataset.state='idle';b.textContent='Отметить отправленным вами';const c=$('[data-act=sentx]');c&&c.remove()}
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&$('#sent-btn[data-state=confirm]')){sentReset();$('#sent-btn').focus()}});
/* текущий шаг пути Research — по видимости раздела, без анимации */
let io=null;
let lock=0;
function pathObs(){io&&io.disconnect();io=null;removeEventListener('scroll',endChk);const nav=$('.rs-path');if(!nav||!('IntersectionObserver' in window))return;const ids=['st1','st2','st3','st4','st5','st6'];
 const set=(id,force)=>{if(lock&&!force)return;let cur=null;$$('button',nav).forEach(x=>{if(x.dataset.to===id){x.setAttribute('aria-current','step');cur=x}else x.removeAttribute('aria-current')});if(cur){const l=cur.offsetLeft,r=l+cur.offsetWidth;if(l<nav.scrollLeft)nav.scrollLeft=l-8;else if(r>nav.scrollLeft+nav.clientWidth)nav.scrollLeft=r-nav.clientWidth+8}};
 LP.setStep=(id,f)=>{set(id,true);if(f){lock=1;clearTimeout(S.stT);S.stT=setTimeout(()=>lock=0,600)}};
 set('st1');const seen=new Map();io=new IntersectionObserver(es=>{es.forEach(e=>seen.set(e.target.id,e.isIntersecting));if(innerHeight+scrollY>=document.documentElement.scrollHeight-4){set('st6');return}const f=ids.find(i=>seen.get(i));if(f)set(f)},{rootMargin:'-140px 0px -55% 0px'});ids.forEach(i=>{const el=$('#'+i);el&&io.observe(el)});
 endChk._set=set;addEventListener('scroll',endChk,{passive:true})}
function endChk(){if(innerHeight+scrollY>=document.documentElement.scrollHeight-4&&endChk._set)endChk._set('st6')}
const _r2=LP.route;LP.route=function(){_r2();pathObs()};
LP.route();
})();
