/* LotPrism · доводка 10 · Research по концепции CTO: дело по сделке Постановка → Смета → Оплата → Работа → Результат → Документ.
   Оболочка и навигация — P8/P9. Числа кейса TopDown — из cto/report.html (30.09.2026), без новых. Цены — гипотезы пилота (FD-21). */
(function(){
'use strict';
const LP=window.LP,{$,$$,esc,T,REG}=LP;
const ss={get:k=>{try{return JSON.parse(sessionStorage.getItem(k)||'null')}catch(e){return null}},set:(k,v)=>{try{sessionStorage.setItem(k,JSON.stringify(v))}catch(e){}}};
const RM=()=>matchMedia('(prefers-reduced-motion: reduce)').matches;
const P9=()=>LP.p9||{};
const pad=n=>String(n).padStart(2,'0');
const nowT=()=>{const d=new Date();return pad(d.getDate())+'.'+pad(d.getMonth()+1)+' '+pad(d.getHours())+':'+pad(d.getMinutes())};
const nowIso=()=>{const d=new Date();return d.getFullYear()+'-'+pad(d.getMonth()+1)+'-'+pad(d.getDate())+'T'+pad(d.getHours())+':'+pad(d.getMinutes())};
const plus14=iso=>{const m=String(iso).match(/^(\d{4})-(\d\d)-(\d\d)/);if(!m)return '';const d=new Date(Date.UTC(+m[1],+m[2]-1,+m[3]+14));return pad(d.getUTCDate())+'.'+pad(d.getUTCMonth()+1)+'.'+d.getUTCFullYear()};
const todayIso=()=>{const d=new Date();return d.getFullYear()+'-'+pad(d.getMonth()+1)+'-'+pad(d.getDate())};
const say=t=>{const l=$('#live');if(l){l.textContent='';setTimeout(()=>l.textContent=t,30)}};

/* ══ словарь ══ */
const KC={conf:'Подтверждено',seller:'Заявление продавца',comp:'Сигнал конкуренции',calc:'Расчёт',ass:'Допущение',unk:'Неизвестно',cf:'Противоречие',pend:'Не проверено'};
const kk=(k,doc)=>`<span class="kk" data-k="${k}"><i aria-hidden="true"></i>${KC[k]}</span>${doc?`<span class="kk-d">в отчёте: ${esc(doc)}</span>`:''}`;
const GN={G01:'Товар и состав',G02:'Условия закупки',G03:'Спрос',G04:'Исполнение и затраты',G05:'Право продажи и требования',G06:'Экономика и цели',G07:'Неблагоприятный случай',G08:'Актуальность и конфликты',G09:'Программные проверки',G10:'Проверка'};
const GW={pend:'не проверено',unk:'неизвестно',pass:'пройдена',fail:'не пройдена',na:'неприменимо'};
const gt=(g,s)=>`<span class="gt" data-g="${s}"><i aria-hidden="true"></i><b>${g}</b> ${GW[s]}</span>`;
const UNK=t=>`<span class="hz">${esc(t)}</span>`;
const DEMO_LINE='Демонстрация на историческом кейсе TopDown (30.09.2026). Модели не вызываются, письма не отправляются, деньги не списываются.';
const NOT_BUY='Оплата исследования — не разрешение на закупку.';
const PRICE_NOTE='гипотеза пилотного тарифа, не действующая цена';
const STEPS=['Постановка','Смета','Оплата','Работа','Результат','Документ'];

/* ══ кейс TopDown: значения из cto/report.html ══ */
const TD={id:'R-R7K2',title:'Палета детских лицензионных футболок TopDown',short:'Палета детских футболок TopDown',
 url:'https://www.topdowntrading.co.uk/pound-wholesale-kids-licensed-t-shirts-pallet.html',
 text:'Палета детских лицензионных футболок, по словам продавца 1 500 шт. за £1 665 с доставкой. Хочу продавать тройками на eBay.',
 rep:'LPR-R7K2-9QXM',memo:'LPR-M4TB-2WVE',date:'30.09.2026',until:'07.10.2026',order:'LPO-2610-0001',pdf:'LPR-R7K2-9QXM-v1.pdf'};
const EXAMPLE=TD.url+'\n'+TD.text;
const FL=[['qty','Количество','G01'],['comp','Состав: размеры и дизайны','G01'],['access','Страница продавца','G01'],['price','Цена закупки','G02'],['stock','Наличие','G02'],['seller','Продавец: реестр и санкции','G02'],['demand','Спрос: продажи троек','G03'],['rivals','Конкуренты','G03'],['post','Отправка Royal Mail','G04'],['weight','Вес упакованной тройки','G04'],['prep','Склад: публичный прайс','G04'],['kit','Сортировка, сборка троек, фото, листинг','G04'],['fees','Комиссии eBay UK','G05'],['rights','Право продажи лицензии','G05'],['vat','VAT на продажу','расчёт'],['cost','Себестоимость остатка','расчёт'],['tax','Налоговый резерв','расчёт'],['vatreg','VAT-регистрация компании','расчёт'],['goals','Ваши пределы и цели','G06 · G07']];
const EV=[
 {t:'Карточка лота TopDown Trading',ev:'ev-01',src:'topdowntrading.co.uk · снимок страницы',acc:'дата снимка неизвестна · доступ есть',what:'Только заявления продавца: £1 665 с доставкой, «No VAT», 1 500 шт., «In stock». Размеры и дизайны не публикуются.',set:[['price','seller','£1 665 за палету с доставкой по UK mainland, «No VAT»','Допущение'],['qty','seller','1 500 шт. — со страницы продавца','Неизвестно'],['stock','unk','«In stock» — дата наблюдения неизвестна','Неизвестно'],['comp','unk','не публикуются; бирки и упаковка — «у большинства»','Неизвестно']]},
 {t:'Повторный запрос страницы продавца',ev:'ev-02',src:'та же страница · независимая проверка',acc:'30.09.2026 · ответ 403, нет доступа',what:'Страница не прочитана. Это причина неизвестности, а не факт.',set:[['access','unk','30.09 — ответ 403, страница не прочитана','Нет доступа']],g:{G01:'unk'}},
 {t:'Поисковый фрагмент о том же лоте',ev:'ev-03',src:'поисковая выдача',acc:'30.09.2026 · доступ есть',what:'£1 665 и 1 200 шт. Количество расходится со страницей продавца: противоречие CG-01. Не скрыто и не усреднено.',set:[['qty','cf','1 500 на странице продавца · 1 200 в поисковом фрагменте','Неизвестно · CG-01']],g:{G08:'unk'},cf:1,pause:1},
 {t:'Конкуренты: активные предложения',ev:'ev-04 · ev-05',src:'Character.com · H&M GB (поисковая карточка)',acc:'30.09.2026',what:'Только активные предложения других наборов. Состоявшихся продаж сопоставимых троек нет.',set:[['rivals','comp','Character.com 3-pack £14.95 + доставка £4.95; H&M £11 вместо £17.99','только конкуренция'],['demand','unk','состоявшихся продаж сопоставимых троек нет','Неизвестно']],g:{G03:'unk'}},
 {t:'Комиссии eBay UK',ev:'ev-06',src:'ebay.co.uk · тариф бизнес-продавца',acc:'30.09.2026 · действует до 07.10.2026',what:'Одежда: 11.9% + 0.35% regulatory + £0.40 за заказ. В расчёте с запасом 13.25% + £0.40.',set:[['fees','conf','11.9% + 0.35% + £0.40 за заказ; ограничения категории не проверены','Подтверждено']]},
 {t:'Тарифы Royal Mail',ev:'ev-07',src:'Royal Mail · прайс октябрь 2026',acc:'30.09.2026 · доступ есть',what:'Tracked 48 до 2 кг — £3.75 с VAT с 05.10.2026, сбор £0.50. Вес упакованной тройки не измерен.',set:[['post','conf','Tracked 48 до 2 кг — £3.75 с VAT, сбор £0.50','Подтверждено'],['weight','unk','вес и размер не измерены','Неизвестно']]},
 {t:'Прайс склада',ev:'ev-08',src:'Complete Prep · публичный прайс',acc:'30.09.2026 · доступ есть',what:'Первый pick £1, доп. единица £0.40. Это не котировка партии: сортировка, сборка, фото — без цены.',set:[['prep','ass','pick £1, доп. единица £0.40','Допущение'],['kit','unk','цены нет','Неизвестно']],g:{G04:'unk'}},
 {t:'Нормы HMRC: VAT на детскую одежду',ev:'ev-09',src:'HMRC VAT Notice 714',acc:'30.09.2026 · доступ есть',what:'Нулевая ставка зависит от размера и представления товара; размеры партии неизвестны.',set:[['vat','ass','нулевая ставка; к партии без размеров не проверить','Допущение']]},
 {t:'Нормы HMRC: запасы и налог компании',ev:'ev-10 · ev-11 · ev-12',src:'HMRC BIM33135 · GOV.UK Corporation Tax · профиль компании',acc:'30.09.2026',what:'Остаток — по закупке и прямым затратам: £1.41 за шт. Налог компании — резерв 25% по допущению. VAT-регистрация — со слов Founder.',set:[['cost','calc','£1.41 за шт. = (1 665 + 450) / 1 500, на допущениях','Рассчитано на допущениях'],['tax','ass','резерв 25%; применимость ставки к компании неизвестна','Допущение'],['vatreg','ass','UK VAT — со слов Founder; номер не проверен','Допущение']]},
 {t:'Продавец и право продажи',ev:'—',src:'проверок в материалах нет',acc:'—',what:'Проверки продавца по реестру и санкциям нет. Подлинность лицензии не подтверждена: нет инвойса.',set:[['seller','unk','реестр и санкционные списки не проверены','Неизвестно'],['rights','unk','нет инвойса и подтверждения подлинности','Неизвестно']],g:{G02:'unk',G05:'unk'}},
 {t:'Расчёт: три сценария и чувствительность',ev:'расчёт v1',src:'входы — допущения a1–a10',acc:'GBP · до пенса',what:'Экономика не определена: неизвестны три статьи затрат и состав. Сценарии — условные, не прогноз.',g:{G06:'unk',G07:'unk'}},
 {t:'Программные и независимая проверки',ev:'G09 · G10',src:'арифметика, единицы, тождество запасов; проверка в отдельном контексте',acc:'открытых существенных замечаний нет',what:'G09 пройдена. G10: машинная — пройдена; человеком — не запрашивается.',g:{G09:'pass',G10:'pass'}}];
const GTXT={G01:['Размеры и дизайны не подтверждены; количество 1 500 против 1 200 — открытое противоречие; страница продавца при проверке — 403.','Manifest этой партии или письменная котировка с количеством и составом'],G02:['Цена, VAT и наличие — только со страницы продавца; письменной котировки нет.','Письменная котировка с VAT по строкам и сроком'],G03:['Только активные предложения; набор Character.com исключён как аналог; состоявшихся продаж сопоставимых троек нет.','Состоявшиеся продажи точного аналога на eBay UK; порог до ратификации (FD-18): 10 продаж, 3 продавца, 90 дней'],G04:['Сортировка, сборка троек, фото и листинг не оценены; остальные операции — по публичному прайсу, не по котировке.','Письменная котировка 3PL на эти операции для этой партии'],G05:['Право перепродажи лицензионного товара и ограничения канала не подтверждены.','Инвойс и подтверждение подлинности от продавца; проверка ограничений eBay для аккаунта'],G06:['Экономика не определена; цели не заданы.','Закрытие G01, G03, G04 и ваши цели с базой'],G07:['Предел убытка не задан; неблагоприятный сценарий есть только на допущениях.','Ваш предел убытка и подтверждённые входы сценариев'],G08:['Открытое противоречие количества; существенные неизвестные.','Письменное количество от продавца и свежие данные по закрытым полям'],G09:['Арифметика, единицы, тождество запасов (куплено = продано + остаток), одна валюта GBP; ни одно неизвестное не превращено в ноль.','—'],G10:['Независимая проверка в отдельном контексте не оставила открытых существенных замечаний; исторически Claude пришёл к тому же выводу. Человек: не запрашивается.','Человек проверяет только решения «Готово к проверке решения»']};
const RULES=[['R1','Подтверждённого провала проверки нет — отказа нет.'],['R2','Покрытие «Поддерживается» — ограничения покрытия нет.'],['R3','Не скрининг.'],['R4','Не все G01–G09 пройдены — к проверке человеком не передаётся.'],['R5','Пилот не запрашивался. И при запросе невозможен: G01, G02, G04 блокируются не только спросом.'],['R6','«Не покупать сейчас — нужны данные» со списком того, что изменит вывод.']];
const APXA=[['ev-01','Карточка лота TopDown Trading','дата неизвестна · доступ есть','seller','Допущение (цена); Неизвестно (наличие, количество)','Только заявления продавца: £1 665 с доставкой по UK mainland, «No VAT», 1 500 новых детских лицензионных футболок, «In stock». Размеры и дизайны не публикуются.'],['ev-02','Та же страница, запрос независимой проверки','30.09.2026 · 403','unk','Нет доступа','Ничего. Страница не прочитана и как прочитанная не цитируется.'],['ev-03','Поисковый фрагмент о том же лоте','30.09.2026 · доступ есть','cf','открывает противоречие','£1 665 и 1 200 шт. Ни одно поле не закрывает; количество расходится с ev-01.'],['CG-01','Противоречие количества','открыто','cf','Неизвестно','1 500 (ev-01) против 1 200 (ev-03). Разрешает только письменное количество продавца или manifest.'],['ev-04','Character.com, Minecraft T-shirts 3-pack','30.09.2026','comp','только конкуренция','Тройка £14.95, доставка £4.95 для заказа до £40. Другой набор: цену и скорость продаж палеты не доказывает.'],['ev-05','H&M GB, Minecraft 3-pack','30.09.2026 · поисковая карточка','comp','сигнал, не закрывает','Акция £11 вместо £17.99; наличие по размерам не проверено.'],['ev-06','eBay UK, комиссии бизнес-продавца','30.09.2026 · до 07.10.2026','conf','Подтверждено','Одежда B2C: 11.9% + 0.35% regulatory + £0.40 за заказ. Спрос и прибыль не подтверждает.'],['ev-07','Royal Mail, online price guide, октябрь 2026','30.09.2026','conf','Подтверждено (тариф); Неизвестно (применимость)','С 05.10.2026 Tracked 48 Small Parcel до 2 кг — £3.75 с VAT; сбор £0.50. Вес тройки не измерен.'],['ev-08','Complete Prep, публичный прайс','30.09.2026','ass','Допущение','Первый pick £1, доп. единица £0.40. Не котировка этой партии.'],['ev-09','HMRC VAT Notice 714','30.09.2026','ass','норма Подтверждено; к партии Неизвестно','Нулевая ставка — для подходящей детской одежды; размеры партии неизвестны.'],['ev-10','HMRC BIM33135, стоимость запасов','30.09.2026','calc','основание расчёта','Остаток по £1.41 за шт. = (1 665 + 450) / 1 500, на допущениях.'],['ev-11','GOV.UK, ставки Corporation Tax','30.09.2026','ass','норма Подтверждено; к компании Неизвестно','Основная ставка 25%, small profits rate 19% — поэтому только резерв по допущению.'],['ev-12','Заявление Founder: компания зарегистрирована по UK VAT','профиль компании','ass','Допущение','Обычный учёт VAT с возмещением входящего. Номер не проверен в реестре HMRC.'],['—','Отсутствуют','—','unk','Неизвестно','Manifest партии; письменная котировка продавца; котировка 3PL; состоявшиеся продажи сопоставимых троек; инвойс и подтверждение подлинности лицензии.']];
const APXB=[['a1','400 троек продаются по £16.95 за 90 дней; 300 футболок не входят в выручку','Состоявшиеся продажи точного аналога'],['a2','Из партии собирается нужное число троек разных дизайнов одного размера','Manifest по размеру и дизайну'],['a3','Продажа облагается VAT по нулевой ставке','Размеры из manifest и условия Notice 714'],['a4','Обычный учёт VAT с возмещением входящего, не Flat Rate Scheme','Проверка VAT-номера и схемы'],['a5','£750 — предел бюджета: подготовка £450, фото и листинги £150, хранение, страхование и вывоз остатка £100, учёт £50','Письменная котировка 3PL'],['a6','Отправка £4.85 без VAT за заказ: тройка — один pick, до 2 кг, Royal Mail Small Parcel','Котировка 3PL и замер упакованной тройки'],['a7','Комиссии 13.25% от суммы заказа + £0.40; реклама 3%; резерв претензий 3%','Фактические данные аккаунта'],['a8','Налоговый резерв 25% от прибыли по проданному','Годовой налоговый контекст компании'],['a9','Время владельца: 10 часов по £15 = £150','Ваши часы и ставка'],['a10','Пятёрки по £24.99 — дополнительная ценовая гипотеза','Продажи точного аналога']];
const PLAN=[['Запрос продавцу о составе','TopDown Trading','(1) фактический состав партии по дизайну, лицензии и размеру, свежие фото товара и бирок; (2) общее количество, состояние, доля без бирок и упаковки, дефекты; (3) подтверждение £1 665 как итоговой цены с доставкой, VAT по строкам, прочие сборы; (4) подтверждение подлинности лицензионного товара с инвойсом и ограничения каналов; (5) число паллет и коробок, размеры, вес, порядок при расхождении. Запрос информационный — не заказ и не бронь.','G01 · G02 · G05','подготовлен, не отправлен',1],['Котировка склада','3PL, например Complete Prep','Письменная цена с VAT и минимумами: приёмка и пересчёт; сортировка по размеру и дизайну; сборка до 500 запечатанных троек одного размера; фото комбинаций; тройка как один pick, упаковка, измеренный вес и размер; хранение 90 и 180 дней; возвраты; вывоз остатка; страхование.','G04','подготовлен, не отправлен',1],['Состоявшиеся продажи','вы, в интерфейсе eBay','Проданные — не активные — объявления на eBay UK за 90 дней: тройка новых детских лицензионных футболок одного размера, цена с доставкой и дата. Выгрузку или снимки загрузите в исследование.','G03','ждёт вас',0],['Задать пределы','вы','Сколько готовы потерять в худшем случае; предел капитала; цель прибыли с указанием базы; срок возврата денег. Пересчёт без нового анализа.','G06 · G07','ждёт вас',0],['Обновить исследование','после ответов','Повторяются только затронутые проверки; будет новая версия решения, эта станет заменённой. Цена обновления — в смете.','все','после 1–4',0]];
const CHANGE=[['Manifest показывает другой товар или состояние, чем в предложении','G01 не пройдена → «Отказаться от сделки»'],['Продавец письменно подтверждает, что лот снят','G02 не пройдена → «Отказаться от сделки»'],['Подтверждён запрет продажи для опознанного товара или канала','G05 не пройдена → «Отказаться от сделки»'],['Убыток неблагоприятного сценария на подтверждённых входах выше вашего предела','G07 не пройдена → отказ для запрошенного объёма; отчёт покажет допустимый объём'],['G01–G09 пройдены, экономика на подтверждённых входах соответствует целям','«Готово к проверке решения» → после проверки «Можно рассмотреть закупку на указанных условиях». Покупка — отдельное решение.']];
const MISS=[['Manifest с размерами и дизайнами','продавец · G01'],['Письменная котировка: количество и цена','продавец · G01, G02'],['Котировка 3PL: сортировка, сборка, фото, исполнение','склад · G04'],['Продажи сопоставимых троек на eBay UK','выгрузка · G03'],['Ваш предел убытка и цели','вы · G06, G07']];
const SC=[['Базовый','400 × £16.95',1586.25,563.29,413.29,300,'423.00'],['Неблагоприятный','300 × £15.25',687.56,-467.58,-617.58,600,'846.00'],['Благоприятный','500 × £16.95',2057.81,1289.11,1139.11,0,'0.00']];
const SENS=[['База: 400 × £16.95',413.29,563.29],['Только цена: 400 × £15.25',6.56,156.56],['Только продажи: 300 × £16.95',-312.53,-162.53],['Налоговый резерв 19% вместо 25%',508.46,658.46],['Пятёрки 240 × £24.99 (гипотеза)',575.31,725.31],['Пятёрки 200 × £21.99 (гипотеза)',-294.45,-144.45]];
const COST=[['Отправка £4.85 × 400',1940.00,'ass'],['Закупка всей партии',1665.00,'seller'],['Комиссии eBay 13.25% + £0.40',1058.35,'ass'],['Бюджет: подготовка, фото, хранение, учёт',750.00,'ass'],['Налоговый резерв 25%',396.56,'ass'],['Реклама 3%',203.40,'ass'],['Резерв претензий 3%',203.40,'ass'],['Время владельца 10 ч × £15',150.00,'ass']];
const gbp=v=>{const n=v<0,a=Math.abs(v).toFixed(2).split('.');return (n?'−':'')+'£'+a[0].replace(/\B(?=(\d{3})+(?!\d))/g,' ')+'.'+a[1]};
const gb=v=>`<span class="n${v<0?' neg':''}">${gbp(v)}</span>`;

/* ══ задачи и цены ══ */
const TASKS=[['check','Проверить товар, предложение или партию','ссылка, код товара, manifest, инвойс или фото','решение по рынку, экономика в трёх представлениях, проверки G01–G10, план действий','полный отчёт · 9 листов A4 и меморандум «Краткое решение»'],
 ['find','Найти товар или направление под ваши условия','категория или «помогите выбрать», рынок, капитал или «пока не определён»','до 20 кандидатов, 3 финалиста с полной проверкой и сравнением','отчёт исследования · макета для этой задачи нет'],
 ['import','Проверить импортный маршрут','предложение поставщика, страна отправки, рынок продажи','маршрут и его покрытие, кандидаты кода HS с доказательствами, расходы до склада','отчёт исследования · макета для этой задачи нет'],
 ['memo','Подготовить меморандум по готовому исследованию','версия исследования, адресат, язык','краткое решение, инвестиционный, отказ или пробелы — с теми же цифрами и статусом','меморандум «Краткое решение» · 2 листа; инвестиционный — формат описан, макета нет'],
 ['refresh','Обновить исследование','прежнее исследование и новые данные','новая версия решения; повторяются только затронутые проверки','обновление · формат описан (1–2 листа), макета нет']];
const TASKN=Object.fromEntries(TASKS.map(t=>[t[0],t[1]]));
const MORE=[['Исследовать товар','check','single'],['Проверить гипотезу','check','single'],['Найти поставщиков','find',''],['Сравнить предложения','check','single'],['Проверить партию','check','mixed']];
function price(c){if(c.task==='find')return ['C5','поиск направления',149];if(c.task==='import')return ['C4','импортный товар',149];
 if(c.task==='memo')return ['M0','меморандум: до трёх включено в каждое платное C2–C5, далее',3];if(c.task==='refresh')return ['C0','обновление до 3 источников',5];
 if(c.depth==='screen')return ['C1','скрининг',9];return c.sub==='single'?['C2','полное исследование товара',49]:['C3','полное исследование партии',79]}
const MK={GB:['Великобритания, без Северной Ирландии','GBP',['eBay UK','Amazon UK']],XI:['Северная Ирландия','GBP',['eBay UK','Amazon UK']],DE:['Германия','EUR',['amazon.de','eBay DE']]};
function cover(c){if(c.goal==='personal')return ['ro','Только исследование','личная покупка: найдём и сравним, без закупочного одобрения'];
 if(c.task==='import')return ['ro','Только исследование','импорт в GB — до этапа S2 без закупочного одобрения'];
 if(c.mk==='DE')return ['ro','Только исследование',`${(c.ch||[]).join(', ')||'amazon.de'}: пока не подтверждены DE VAT, EPR и ответственное лицо GPSR`];
 return ['ok','Поддерживается','GB · закупка внутри GB · '+((c.ch||[]).join(', ')||'канал не выбран')+' — так только при подписанном налоговом пакете GB-VAT/1 (FD-14)']}
function best(c){const cv=cover(c);if(c.depth==='screen')return '«Проверить полностью» или «Не продолжать» — скрининг закупочного решения не даёт';
 if(cv[0]==='ro')return 'Не покупать сейчас — нужны данные';return 'При подтверждённых данных — «Готово к проверке решения»; положительный статус не гарантирован'}

/* ══ состояние ══ */
function seed(){const R06=REG.P06.research,R15=REG.P15.research;return {n:0,prof:'founder',cases:{
 'R-P01':{id:'R-P01',kind:'card',sk:'item:P01',hist:1,code:REG.P01.research.brief,stage:'result',run:{st:'done'},at:'2026-09-21',fin:'2026-09-24',dirty:0},
 'R-D02':{id:'R-D02',kind:'card',sk:'hyp:P06',hist:1,code:R06.brief,stage:'work',run:{st:'input'},at:R06.updated_at,dirty:0},
 'R-D04':{id:'R-D04',kind:'card',sk:'hyp:P15',hist:1,code:R15.brief,stage:'work',run:{st:'wait'},at:R15.updated_at,dirty:0}},
 ev:[{at:fdt5(R06.updated_at),t:'Требуется уточнение: «'+((P9().DEMO||{q:{}}).q['hyp:P06']||{q:'Подтвердите состав набора'}).q+'»',href:'#/research/R-D02',id:'R-D02'},{at:fdt5(R15.updated_at),t:'Ждём внешний ответ: '+(REG.P15.title_ru||'Баночки для специй'),href:'#/research/R-D04',id:'R-D04'}]}}
function fdt5(iso){return LP.fdt(iso)}
let ST=ss.get('lp10');if(!ST||!ST.cases)ST=seed();
const save=()=>ss.set('lp10',ST);save();
const CS=id=>ST.cases[id];
function ev(t,href,id){ST.ev.unshift({at:nowT(),t,href,id});ST.ev=ST.ev.slice(0,12)}
function tdNew(full){const c={id:TD.id,kind:'td',task:'check',sub:'mixed',url:TD.url,ident:'',text:TD.text,files:[],goal:'resale',mk:'GB',ch:['eBay UK'],chNeed:false,cap:'',capNone:true,hor:'90',horOwn:'',depth:'full',email:'irina.becker@demo-handel.example',step:full?4:1,stage:full?'order':'setup',ord:{st:'draft'},run:{i:0,st:'idle'},mail:{l1:null,l2:{st:'none',log:[]}},at:todayIso()};ST.cases[TD.id]=c;return c}
const isTD=c=>c.kind==='td';
const SJ=c=>c.kind==='card'?(P9().DEMO||{subj:{}}).subj[c.sk]:null;
const titleOf=c=>isTD(c)?TD.title:c.kind==='card'?(SJ(c)||{}).title||c.id:(c.text||c.url||c.ident||'Своё исследование').split('\n').pop().slice(0,90);

/* ══ состояния заказа и линии ══ */
function stWord(c){if(c.hist){return c.run.st==='input'?['input','Требуется уточнение']:c.run.st==='wait'?['wait','Ждём внешний ответ']:['ready','Готово']}
 if(c.stage==='setup')return ['draft','Постановка'];if(c.ord.st==='draft')return ['draft','Смета готова'];
 if(c.ord.st==='await')return ['await','Оплата ожидается'];if(c.ord.st==='fail')return ['fail','Оплата не прошла'];
 if(c.kind==='own')return ['draft','Сохранено · анализ не выполнялся'];
 if(c.run.st==='run'||c.run.st==='idle')return ['run','Выполняется'];if(c.run.st==='input')return ['input','Требуется уточнение'];
 const l=c.mail.l2;return l.st==='sent'?['sent','Письмо отправлено']:l.st==='bounce'?['bounce','Письмо не доставлено']:['ready','Отчёт готов']}
const chip=c=>{const w=stWord(c);return `<span class="st10" data-s="${w[0]}"><i aria-hidden="true"></i>${w[1]}</span>`};
function lineIdx(c){if(c.hist)return c.run.st==='done'?4:3;if(c.stage==='setup')return 0;if(c.stage==='order')return c.ord.st==='draft'?1:2;if(c.stage==='work')return 3;return 4}
function line(c,view){let cur=lineIdx(c);const hist=!!c.hist;const done=!hist&&c.stage==='result';if(done&&(view==='docs'||view==='letters'))cur=5;
 const href=['?s=setup','?s=order','?s=order','?s=work','?s=result','/docs'];
 const sub=i=>{if(hist&&(i===1||i===2))return 'не оформлялась · исследование команды LotPrism';if(hist&&i===0)return 'из карточки';if(hist&&i===5)return 'в демо не собран';
  if(i===cur&&i===5)return 'сейчас';if(i<cur||(i===5&&done))return i===2?(ST.prof==='paid'?'оплачено · демо':'£0 · профиль Founder'):i===5?'отчёт и меморандум':'готово';if(i===cur)return i===2&&c.ord.st==='fail'?'не прошла':'сейчас';return 'дальше'};
 const st=i=>hist&&(i===1||i===2||i===5)?'na':i<cur?'done':i===cur?'cur':(i===5&&done)?'done':'next';
 const vi=view==='docs'||view==='letters'?5:{setup:0,order:2,work:3,result:4}[view];
 const items=STEPS.map((s,i)=>{const k=st(i),can=k==='done'||k==='cur';const inner=`<span class="ln-m" aria-hidden="true"></span><span class="ln-t">${s}</span><span class="ln-s">${sub(i)}</span>`;
  return `<li class="ln-i" data-s="${k}"${vi===i||(vi===2&&i===1)?' data-v="1"':''}>${can&&!(hist&&i<4)?`<a href="#/research/${c.id}${href[i]}"${vi===i?' aria-current="step"':''}>${inner}</a>`:`<span class="ln-x">${inner}</span>`}</li>`}).join('');
 const nx=nextOf(c);
 return `<nav class="ln10" aria-label="Ход дела"><ol>${items}</ol><p class="ln-now"><b>Сейчас:</b> ${nx[0]}${nx[1]?` <span class="t2">· Дальше: ${nx[1]}</span>`:''}</p></nav>`}
function nextOf(c){if(c.hist)return c.run.st==='input'?['нужен ваш ответ на вопрос исследования','продолжение работы']:c.run.st==='wait'?['ждём внешний ответ — срок в данных не задан','работа продолжится после ответа']:['результат готов','полный документ в демо не собран; решение записываете вы в карточке'];
 if(c.stage==='setup')return ['постановка, шаг '+Math.min(c.step,3)+' из 3','смета'];if(c.ord.st==='draft')return ['смета и почта для отчёта','оплата'];
 if(c.ord.st==='await')return ['оплата ожидается','работа начнётся после оплаты'];if(c.ord.st==='fail')return ['оплата не прошла — заказ сохранён','повторить оплату'];
 if(c.kind==='own')return ['анализ по вашему вводу не выполнялся','продолжить на кейсе TopDown'];
 if(c.run.st==='input')return ['нужен ваш ответ о количестве','работа продолжится'];if(c.stage==='work')return ['идёт работа по кейсу','результат и документ'];
 const l=c.mail.l2;return l.st==='bounce'?['письмо не доставлено — исправьте адрес','отчёт доступен в кабинете']:['результат и документ готовы','отправить запросы и обновить исследование']}

/* ══ первый экран ══ */
function home(){const L=Object.values(ST.cases).sort((a,b)=>String(b.at).localeCompare(String(a.at)));
 return `<main class="main r10" data-screen-label="Research"><header class="r10-hd"><h1 class="h1">Research</h1><p class="r10-lede">Исследование сделки до закупки: что известно, чего не хватает и какое действие допустимо. Оплачивается объём исследования, а не положительный вывод: «Не покупать сейчас — нужны данные» — тоже результат.</p></header>
<form class="r10-start" id="f10-start" novalidate aria-labelledby="t10-task">
<section class="sec" aria-labelledby="t10-task"><div class="sec-h"><h2 class="h2" id="t10-task">С чем вы пришли</h2></div>
<fieldset class="r10-tasks"><legend class="sr-only">Задача</legend>${TASKS.map((t,i)=>`<label class="r10-task"><input type="radio" name="task" value="${t[0]}"${i?'':' checked'}><span class="r10-tt"><span class="r10-tn">${t[1]}</span><span class="r10-io"><span><b>Нужно</b>${t[2]}</span><span><b>Получите</b>${t[3]}</span><span><b>Документ</b>${t[4]}</span></span></span></label>`).join('')}</fieldset>
<p class="r10-mi"><span class="t2">Ещё входы:</span>${MORE.map(m=>`<button type="button" class="lnk" data-act="t10-more" data-task="${m[1]}" data-sub="${m[2]}">${m[0]}</button>`).join('')}</p></section>
<section class="sec" aria-labelledby="t10-subj"><div class="sec-h"><h2 class="h2" id="t10-subj"><label for="f10-text">Что исследуем</label></h2><p class="t2">ссылка, идентификатор, описание своими словами, файл или фото · карточка товара не нужна</p></div>
<div class="r10-subj"><textarea id="f10-text" name="text" rows="3" placeholder="${esc(EXAMPLE)}" aria-describedby="f10-e f10-h"></textarea>
<div class="r10-sa"><label class="btn btn-s sm r10-file"><input type="file" name="files" multiple accept="image/*,.pdf,.csv,.xlsx,.txt" class="sr-only" id="f10-files">Добавить файл или фото</label><span class="t2" id="f10-fl"></span><button type="button" class="lnk" data-act="t10-example">Подставить пример TopDown</button><span class="sp"></span><button class="btn btn-p" type="submit">Начать постановку</button></div>
<p class="r10-err" id="f10-e" role="alert" hidden></p><p class="t2" id="f10-h">Демо выполняет только кейс TopDown. Свой предмет сохраняется: постановка и смета строятся по нему, анализ не изображается.</p></div></section></form>
<section class="sec" aria-labelledby="t10-my"><div class="sec-h"><h2 class="h2" id="t10-my">Мои исследования</h2></div><ul class="rows r10-my">${L.map(c=>myRow(c)).join('')}</ul></section>
<section class="sec r10-nt" aria-labelledby="t10-nt"><div class="sec-h"><h2 class="h3" id="t10-nt">Уведомления</h2></div>${ST.ev.length?`<ul class="r10-evl">${ST.ev.map(e=>`<li><span class="n t2">${esc(e.at)}</span><a href="${e.href}">${esc(e.t)}</a></li>`).join('')}</ul>`:'<p class="t2">Уведомлений нет.</p>'}</section></main>`}
function myRow(c){const docs=isTD(c)&&c.stage==='result'?`<a href="#/research/${c.id}/docs">Отчёт · меморандум</a>`:c.kind==='card'?'<span class="t2">документ в демо не собран</span>':c.kind==='own'?'<span class="t2">анализ не выполнялся</span>':'<span class="t2">документа пока нет</span>';
 return `<li class="r10-mr"><div><p><a id="m10-${c.id}" href="#/research/${c.id}">${esc(titleOf(c))}</a></p><p class="t2">${c.kind==='card'?'Проверка из карточки'+(c.code?' · <span class="code">'+c.code+'</span>':''):TASKN[c.task]}</p></div>${chip(c)}<div class="r10-md">${docs}</div></li>`}

/* ══ шапка дела ══ */
function caseHead(c,view){const sj=SJ(c);const rt=c.kind==='card'?retOf(c):null;const back=c.kind==='card'?`<a href="${esc(rt.h)}" id="r10-back" data-sk="${c.sk}">${esc(sj.back)}</a>`:'';const hb=c.shown?`<p class="r10-hb">Показан завершённый исторический кейс · <button type="button" class="lnk" data-act="t10-restart">Пройти путь с начала</button></p>`:'';
 return `<nav class="r9-bc" aria-label="Возврат">${back}<a href="#/research" class="${back?'t2':''}">← Research</a></nav>
<header class="r10-ch"><p class="eyebrow">${c.kind==='card'?'Проверка из карточки':TASKN[c.task]} · <span class="code">${c.id}</span>${isTD(c)&&c.ord.st==='paid'?` · заказ <span class="code">${TD.order}</span> <span class="t2">(пример формата)</span>`:''}</p><h1 class="h1" id="r10-h1" tabindex="-1">${esc(titleOf(c))}</h1><p class="r10-meta">${chip(c)}<span class="t2">${isTD(c)||c.kind==='card'&&c.hist?DEMO_LINE:'Ваш ввод сохранён в этой сессии.'}</span></p>${hb}</header>${line(c,view)}`}
function retOf(c){const sj=SJ(c);const r=(ST.ret||{})[c.sk];if(r&&r.h)return r;return {h:c.from||sj.home,y:null,f:null}}

/* ══ постановка ══ */
const sellerWords=t=>{const m=String(t||'').match(/(£\s?\d[\d\s.,]*\d|\d[\d\s]*\s?(?:шт\.?|штук|ед\.?|€|£)|€\s?\d[\d\s.,]*\d)/g)||[];return [...new Set(m.map(s=>s.trim()))]};
function setup(c){const sj=SJ(c);const sm=n=>c.step>n;const box=(n,t,sum,body)=>`<section class="r10-ps" data-on="${c.step===n}" data-done="${sm(n)}" aria-labelledby="ps10-${n}"><div class="r10-psh"><span class="r9-pn" aria-hidden="true">${n}</span><h2 class="h2" id="ps10-${n}" tabindex="-1">${t}</h2>${sm(n)?`<button type="button" class="lnk" data-act="s10-edit" data-n="${n}">Изменить<span class="sr-only">: ${t}</span></button>`:''}</div>${sm(n)?`<p class="r10-pss">${sum}</p>`:c.step===n?body:''}</section>`;
 const files=(c.files||[]).length?`<p class="t2">файлы: ${c.files.map(esc).join(', ')} · в демо не читаются</p>`:'';
 const sw=sellerWords(c.text);
 const s1=`<form class="r10-f" id="s10-1" novalidate><fieldset class="r10-seg"><legend class="h3">Вид задачи</legend>${[['single','Один товар'],['homog','Однородная партия'],['mixed','Смешанная партия или палета']].map(o=>`<label><input type="radio" name="sub" value="${o[0]}"${c.sub===o[0]?' checked':''}><span>${o[1]}</span></label>`).join('')}</fieldset>
${sj?`<div class="r10-tr"><h3 class="h3">Перенос из карточки</h3><p class="t2">${esc(sj.src)} · каждое поле — с происхождением и видом знания. Вывод карточки не становится выводом исследования.</p><div class="tbl-wrap" tabindex="0" role="region" aria-label="Перенос из карточки"><table class="tbl r10-t"><thead><tr><th scope="col">Поле</th><th scope="col">Значение</th><th scope="col">Вид знания</th><th scope="col">Откуда</th></tr></thead><tbody>${sj.ctx.map(x=>{const k=remapK(x[0],x[2],x[3]);return `<tr><th scope="row">${esc(x[0])}</th><td>${esc(x[1])}</td><td>${kk(k,k==='seller'?'Допущение':'')}</td><td class="t2">${esc(x[3])}</td></tr>`}).join('')}</tbody></table></div><p class="t2">Не переносится: ${esc(sj.nottr)}.</p></div>`:''}
<div class="r10-g2"><label class="r10-fl"><span class="h3">Ссылка</span><input name="url" type="url" inputmode="url" value="${esc(c.url||'')}" placeholder="${esc(TD.url)}"></label><label class="r10-fl"><span class="h3">Идентификатор</span><input name="ident" value="${esc(c.ident||'')}" placeholder="EAN, ASIN, номер лота"></label></div>
<label class="r10-fl"><span class="h3">Описание своими словами</span><textarea name="text" rows="3" placeholder="${esc(TD.text)}">${esc(c.text||'')}</textarea></label>
${sw.length?`<p class="r10-sw"><span class="t2">Из описания:</span>${sw.map(s=>`<span class="r10-swi"><b class="n">${esc(s)}</b> ${kk('seller')}</span>`).join('')}<span class="t2">будет проверено, фактом не считается</span></p>`:''}
<label class="r10-fl"><span class="h3">Документ или фото</span><input type="file" name="files" multiple accept="image/*,.pdf,.csv,.xlsx,.txt"></label>${files}
<p class="r10-note" data-k="unk">Страница продавца может не открыться (например, ответ 403). Тогда она станет неизвестностью, а не фактом. Без manifest исследование возможно: состав подтверждается ответом продавца, запрос подготовим.</p>
<p class="r10-err" id="s10-1e" role="alert" hidden></p><div class="r10-fa"><button class="btn btn-p" type="submit">Далее</button></div></form>`;
 const ch=MK[c.mk][2];
 const s2=`<form class="r10-f" id="s10-2" novalidate><fieldset class="r10-seg"><legend class="h3">Цель</legend>${[['resale','Перепродажа'],['agency','Агентская услуга'],['personal','Личная покупка']].map(o=>`<label><input type="radio" name="goal" value="${o[0]}"${c.goal===o[0]?' checked':''}><span>${o[1]}</span></label>`).join('')}</fieldset>
<div class="r10-g2"><label class="r10-fl"><span class="h3">Рынок этого исследования</span><select name="mk" data-act10="mk">${Object.entries(MK).map(([k,v])=>`<option value="${k}"${c.mk===k?' selected':''}>${k} · ${v[0]}</option>`).join('')}</select></label><div class="r10-fl"><span class="h3">Валюта</span><p class="r10-ccy n" id="s10-ccy">${MK[c.mk][1]}</p></div></div>
<p class="r10-note">Рабочее пространство — Amazon Германия, EUR. Рынок и площадка задаются для этого исследования: ${c.mk} → ${(c.ch||[])[0]||ch[0]}, ${MK[c.mk][1]}. Суммы в разных валютах не складываются.</p>
<fieldset class="r10-chk"><legend class="h3">Каналы продажи</legend>${ch.map(x=>`<label><input type="checkbox" name="ch" value="${x}"${(c.ch||[]).includes(x)?' checked':''}><span>${x}</span></label>`).join('')}<label><input type="checkbox" name="chNeed"${c.chNeed?' checked':''}><span>Нужен подбор</span></label></fieldset>
<p class="r10-err" id="s10-2e" role="alert" hidden></p><div class="r10-fa"><button class="btn btn-p" type="submit">Далее</button></div></form>`;
 const s3=`<form class="r10-f" id="s10-3" novalidate><div class="r10-fl"><span class="h3" id="s10-capl">Капитал для сделки</span><div class="r10-cap"><input name="cap" id="s10-cap" inputmode="decimal" aria-labelledby="s10-capl" value="${esc(c.cap||'')}" placeholder="сумма, ${MK[c.mk][1]}"${c.capNone?' disabled':''}><label class="r10-c1"><input type="checkbox" name="capNone"${c.capNone?' checked':''}><span>Пока не определён</span></label></div></div>
<p class="r10-note" data-k="unk" id="s10-capn"${c.capNone?'':' hidden'}>Предел убытка и цели не заданы → проверки G06 и G07 останутся неизвестными. Положительного решения без предела не будет; за вас предел не подставляется. Задать можно позже — пересчёт без нового анализа.</p>
<fieldset class="r10-seg"><legend class="h3">Горизонт</legend>${[['30','30 дней'],['60','60 дней'],['90','90 дней'],['180','180 дней'],['own','Свой']].map(o=>`<label><input type="radio" name="hor" value="${o[0]}"${c.hor===o[0]?' checked':''}><span>${o[1]}</span></label>`).join('')}</fieldset>
<label class="r10-fl" id="s10-ho"${c.hor==='own'?'':' hidden'}><span class="t2">Свой срок, дней</span><input name="horOwn" inputmode="numeric" value="${esc(c.horOwn||'')}"></label>
<fieldset class="r10-dep"><legend class="h3">Глубина</legend><label><input type="radio" name="depth" value="screen"${c.depth==='screen'?' checked':''}><span><b>Скрининг</b><span class="t2">быстрый отсев; не даёт закупочного решения — итог «проверить полностью» или «не продолжать»</span></span></label><label><input type="radio" name="depth" value="full"${c.depth!=='screen'?' checked':''}><span><b>Полное исследование</b><span class="t2">проверки G01–G10, три сценария, предел цены и объёма, независимая проверка</span></span></label></fieldset>
<details class="r10-x"><summary>Ещё параметры <span class="t2">· для старта не нужны; исследование спросит само</span></summary><ul class="r10-xl">${[['Компания','юрисдикция, налоговые регистрации, валюта отчёта, роль','из профиля компании; UK VAT — со слов Founder'],['Товар','вариант, состояние, комплектация, единица продажи, manifest','найдёт исследование или спросит'],['Закупка','продавец, цена и налоговая база, MOQ, оплата, срок предложения','найдёт исследование или спросит'],['Доставка','география по семи полям, Incoterm, вес, размеры','отправка внутри GB'],['Исполнение','свой склад, 3PL или FBA; приёмка, хранение, возвраты, ликвидация','найдёт исследование или спросит'],['Продажи','аккаунты, ограничения категорий, комиссии, реклама','не заполнено'],['Цели и риск','минимальная прибыль и её база, предел вложений и убытка, срок окупаемости','не задано'],['B2B и агентская модель','заказ, предоплата, договор, комиссия',c.goal==='agency'?'открыт: выбрана агентская услуга':'скрыт: нет предпродажи и агентской услуги'],['Меморандум','адресат, язык, назначение, конфиденциальность',c.task==='memo'?'открыт: задача «Подготовить меморандум»':'скрыт: только для задачи «Подготовить меморандум»']].map(b=>`<li><b>${b[0]}</b><span class="t2">${b[1]}</span><span class="${/^скрыт/.test(b[2])?'hz':''}">${b[2]}</span></li>`).join('')}</ul></details>
<p class="r10-err" id="s10-3e" role="alert" hidden></p><div class="r10-fa"><button class="btn btn-p" type="submit">Получить смету</button></div></form>`;
 const s1sum=`${{single:'Один товар',homog:'Однородная партия',mixed:'Смешанная партия или палета'}[c.sub]} · ${esc(c.url?c.url.replace(/^https?:\/\/(www\.)?/,'').slice(0,46)+'…':c.ident||'без ссылки')}${c.text?' · описание':''}${(c.files||[]).length?' · файлов: '+c.files.length:''}`;
 const s2sum=`${{resale:'Перепродажа',agency:'Агентская услуга',personal:'Личная покупка'}[c.goal]} · ${c.mk} · ${MK[c.mk][1]} · ${c.chNeed?'каналы: нужен подбор':(c.ch||[]).join(', ')}`;
 const s3sum=`капитал ${c.capNone?'пока не определён':esc(c.cap)+' '+MK[c.mk][1]} · горизонт ${c.hor==='own'?esc(c.horOwn):c.hor} дней · ${c.depth==='screen'?'скрининг':'полное исследование'}`;
 return `<div class="r10-steps">${box(1,'Предмет и материалы',s1sum,s1)}${box(2,'Цель, рынок и каналы',s2sum,s2)}${box(3,'Капитал, горизонт, глубина',s3sum,s3)}</div>`}
const remapK=(label,k,prov)=>/противоречи/.test(prov||'')?'cf':/^(Предложение|Закупка|Цена|Партия|Единица продажи|Срок|Манифест|Состояние)/.test(label)&&k!=='unk'?'seller':k==='conf'?'conf':k;

/* ══ смета, почта, оплата ══ */
function order(c){const pr=price(c),cv=cover(c),paid=ST.prof==='paid'&&isTD(c);const pay=paid?pr[2]:0;const sj=SJ(c);
 const ccy=MK[c.mk][1],hor=c.hor==='own'?c.horOwn:c.hor;
 const what=`<dl class="r10-kv"><div><dt>Предмет</dt><dd>${esc(titleOf(c))}${c.url?`<span class="t2 r10-url">${esc(c.url)}</span>`:''}</dd></div><div><dt>Рынок и площадка</dt><dd>${c.mk} · ${(c.ch||[]).join(', ')||'нужен подбор'} · ${ccy}</dd></div><div><dt>Горизонт</dt><dd>${hor} дней</dd></div><div><dt>Глубина</dt><dd>${c.depth==='screen'?'скрининг':'полное исследование'} · ${pr[0]}</dd></div></dl>`;
 const inc=`<div class="r10-inc"><div><h3 class="h3">Проверим сами</h3><ul><li>страницу предложения — с записью статуса доступа</li><li>продавца: реестр компаний и санкционные списки</li><li>комиссии канала и тарифы доставки по официальным страницам</li><li>налоговые нормы рынка для товара</li><li>три сценария и ликвидацию; предел цены и объёма</li><li>проверки G01–G10 и независимую проверку</li></ul></div><div><h3 class="h3">Данные уже есть</h3><ul><li>${c.url?'ссылка на предложение':'ваш ввод'}</li>${c.text?'<li>ваше описание — как заявление, не как факт</li>':''}<li>профиль компании: UK VAT — со слов Founder</li><li>рынок, канал, горизонт</li></ul></div><div><h3 class="h3">Нужны ответы</h3><ul><li>состав и количество — <span class="t2">продавец</span></li><li>письменная цена, VAT по строкам — <span class="t2">продавец</span></li><li>котировка сортировки, сборки, фото — <span class="t2">склад</span></li><li>выгрузка состоявшихся продаж — <span class="t2">вы</span></li></ul><p class="t2">Тексты запросов подготовим, отправляете вы (FD-8). Research ничего не отправляет и не покупает.</p></div></div>`;
 const left=`<div class="r10-ol"><section class="r10-ob" aria-labelledby="o10-a"><h2 class="h2" id="o10-a" tabindex="-1">Смета</h2>${what}</section>
<section class="r10-ob" aria-labelledby="o10-b"><h3 class="h3" id="o10-b">Что войдёт</h3>${inc}</section>
<section class="r10-ob r10-g2" aria-label="Завершение и границы"><div><h3 class="h3">Что считается завершением</h3><p>Опубликован отчёт с решением по рынку ${c.mk}: «Отказаться от сделки», «Не покупать сейчас — нужны данные» или «Готово к проверке решения». Честный вывод «нужны данные» — тоже завершение. Положительный статус не гарантирован.</p></div><div><h3 class="h3">Что не входит</h3><p>Ответы поставщиков и склада, образцы, инспекции, лицензии данных. Закупка, бронь и отправка запросов.</p></div></section>
<section class="r10-ob r10-g2" aria-label="Документ, покрытие, срок"><div><h3 class="h3">Документ</h3><p>Полный отчёт · 9 листов A4 · PDF + в кабинете</p><p>Меморандум «Краткое решение» · 2 листа</p></div><div><h3 class="h3">Покрытие и лучший достижимый вывод</h3><p><span class="cv10" data-c="${cv[0]}"><i aria-hidden="true"></i>${cv[1]}</span> <span class="t2">${esc(cv[2])}</span></p><p>${esc(best(c))}</p><h3 class="h3 r10-mt">Срок</h3><p>${UNK('не определён')}</p></div></section></div>`;
 const own=!isTD(c);
 const honest=own?`<div class="r10-hon" role="note"><p>Демонстрация выполняется на историческом кейсе TopDown (30.09.2026). Ваш ввод сохранён, анализ по нему не выполнялся.</p>${c.kind==='card'&&c.sk==='item:P01'?`<p class="t2">По этому товару есть завершённое исследование <span class="code">${REG.P01.research.brief}</span> — <a href="#/research/R-P01">открыть результат</a>.</p>`:''}${c.kind==='card'&&c.sk==='hyp:P06'?'<p class="t2">По этой гипотезе уже идёт исследование — <a href="#/research/R-D02">открыть идущее</a>.</p>':''}${c.task!=='check'?'<p class="t2">В демо выполняется только кейс TopDown.</p>':''}<button type="button" class="btn btn-p" data-act="t10-td">Продолжить на кейсе TopDown</button></div>`:'';
 const st=c.ord.st;
 const mail=`<form class="r10-mail" id="o10-mail" novalidate><label class="h3" for="o10-em">Почта для отчёта</label><div class="r10-cap"><input id="o10-em" name="email" type="email" autocomplete="email" value="${esc(c.email||'')}" aria-describedby="o10-emh"${st==='paid'?' readonly':''}>${st==='paid'?'':'<button class="btn btn-s sm" type="submit">Сохранить</button>'}</div><p class="t2" id="o10-emh" aria-live="polite">${emailHint(c.email)}</p></form>`;
 const cost=`<div class="r10-two"><div class="r10-col"><p class="eyebrow">Деньги на сделку</p><p class="r10-big">${c.capNone?UNK('не определены'):'<span class="n">'+esc(c.cap)+' '+ccy+'</span>'}</p><p class="t2">ваш капитал на закупку и всё после неё</p></div><div class="r10-col"><p class="eyebrow">Цена исследования</p><p class="r10-big"><span class="n">£${pr[2]}</span> <span class="code">${pr[0]}</span></p><p class="t2">${pr[1]} · ${PRICE_NOTE}</p><p class="r10-pay">К оплате: <b class="n">£${pay}</b> <span class="t2">${paid?'платный путь · демо':'профиль Founder, этапы S0–S2'}</span></p></div></div><p class="t2">Цена исследования не вычитается из бюджета сделки.</p>`;
 const terms=`<details class="r10-x"><summary>Условия <span class="t2">(предложение, не действуют)</span></summary><ul class="r10-ul"><li>Отмена до запуска — 100% возврат или кредит.</li><li>«Нужны данные» или «отказ» при выполненном объёме — полная цена; это не основание для возврата.</li><li>Ошибка сервиса — кредит или возврат и бесплатный повтор.</li></ul><p class="t2">Платёжный провайдер не выбран. Способы оплаты, сроки выполнения и возврата не заданы.</p></details>`;
 let cta;
 if(own)cta='';
 else if(st==='paid')cta=`<div class="r10-done" role="status"><p><b>Заказ <span class="code">${TD.order}</span> ${paid?'оплачен (демо)':'подтверждён'}</b> <span class="t2">номер — пример формата</span></p><p class="t2">${paid?'£79 по гипотезе C3 · деньги не списаны':'к оплате £0 · профиль Founder'} · подтверждение отправлено на ${esc(c.email)} в ${c.ord.at}</p><p class="t2">Готовый отчёт придёт отдельным письмом. Доступен в кабинете независимо от доставки.</p><a class="btn btn-s sm" href="#/research/${c.id}?s=work">К работе</a> <a class="lnk" href="#/research/${c.id}/letters">Письмо-подтверждение</a></div>`;
 else if(st==='fail')cta=`<div class="r10-fail" role="alert"><p><b>Оплата не прошла</b></p><p class="t2">Деньги не списаны, заказ сохранён, исследование не запущено. Проверьте данные у платёжного провайдера и повторите.</p><button type="button" class="btn btn-p" data-act="o10-pay">Повторить оплату (демо, деньги не списываются)</button></div>`;
 else cta=`${st==='await'?'<p class="r10-wait" role="status"><b>Оплата ожидается.</b> <span class="t2">Работа начнётся после подтверждения оплаты.</span></p>':''}${paid?`<button type="button" class="btn btn-p" data-act="o10-pay">Оплатить £79 (демо, деньги не списываются)</button>`:`<button type="button" class="btn btn-p" data-act="o10-pay">Подтвердить заказ · к оплате £0</button>`}${paid?'<p class="t2">Документ кейса исторический: на листе 4 — «£0 (профиль Founder)».</p>':''}`;
 const right=`<aside class="r10-or" aria-label="Заказ">${cost}${mail}${terms}${honest}${cta}<p class="r10-nb">${NOT_BUY}</p></aside>`;
 return `<div class="r10-ord">${left}${right}</div>`}
const emailOk=e=>/^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/.test(String(e||''));
const emailHint=e=>!e?'Укажите адрес':emailOk(e)?'Формат верный · адрес не подтверждён, письмо — макет':'Проверьте адрес: нужен вид имя@домен';

/* ══ работа ══ */
function stateTD(c){const i=c.run.i||0;const F={},G={};Object.keys(GN).forEach(g=>G[g]='pend');F.goals=['unk','не заданы — предел убытка и цели','Не задано'];
 EV.slice(0,i).forEach(s=>{(s.set||[]).forEach(x=>F[x[0]]=[x[1],x[2],x[3]]);Object.assign(G,s.g||{})});return {F,G,i}}
function counts(F){const t={conf:0,seller:0,comp:0,calc:0,ass:0,unk:0,cf:0};Object.values(F).forEach(v=>t[v[0]]++);return t}
const cnt=t=>`<ul class="r10-cnt" aria-label="Виды знания по полям">${['conf','seller','comp','calc','ass','unk','cf'].map(k=>`<li>${kk(k)} <b class="n">${t[k]}</b></li>`).join('')}</ul>`;
function work(c){if(c.hist)return workCard(c);if(c.kind==='own')return `<p class="t2">Анализ по вашему вводу не выполнялся.</p>`;
 const s=stateTD(c),cur=EV[s.i],last=EV[s.i-1],cf=s.i>=3,inp=c.run.st==='input',done=c.run.st==='done';
 const prev=c._prev||{};c._prev=Object.fromEntries(Object.entries(s.F).map(([k,v])=>[k,v[0]]));
 const now=done?'Работа завершена.':inp?'Остановлено: нужен ваш ответ о количестве.':cur?esc(cur.t)+' · <span class="code">'+cur.ev+'</span>':'—';
 const six=`<dl class="r10-six"><div><dt>Что проверяется сейчас</dt><dd>${now}</dd></div><div><dt>Что уже установлено</dt><dd>${s.i?`полей: <b class="n">${Object.keys(s.F).length-1}</b> из ${FL.length-1}${last?' · последнее: '+esc(last.t):''}`:'пока ничего'}</dd></div><div><dt>Где противоречие</dt><dd>${cf?'Количество: 1 500 на странице продавца, 1 200 в поисковом фрагменте — <span class="code">CG-01</span>':'не найдено'}</dd></div><div><dt>Какой ответ нужен от вас</dt><dd>${inp?'<a href="#q10">Есть ли письменное подтверждение количества</a>':c.run.q?'ответ записан '+esc(c.run.q.at):'сейчас никакой'}</dd></div><div><dt>Что ожидается извне</dt><dd>ничего: страница продавца ответила 403 и повторно не запрашивается. Запросы продавцу и складу — после результата, отправляете вы.</dd></div><div><dt>Как это влияет на вывод</dt><dd>${cf?'Пока противоречие не разрешено, лучший достижимый вывод — «Не покупать сейчас — нужны данные».':'Вывод не сформирован.'}</dd></div></dl>`;
 const gates=`<ul class="r10-gates" aria-label="Проверки G01–G10">${Object.keys(GN).map(g=>`<li title="${GN[g]}">${gt(g,s.G[g])}<span class="t2">${GN[g]}</span></li>`).join('')}</ul>`;
 const rows=FL.map(([id,l,g])=>{const v=s.F[id];const nw=v&&prev[id]!==v[0]&&c._seen;return `<tr${nw?` data-new="${v[0]}"`:''}><th scope="row">${l}</th><td>${v?esc(v[1]):'<span class="t2">не проверено</span>'}</td><td>${v?kk(v[0],v[2]):kk('pend')}</td><td class="code">${g}</td></tr>`}).join('');
 c._seen=1;
 const feed=EV.slice(0,s.i).map((e,j)=>`<li${j===s.i-1&&!done?' data-new="1"':''}><p><span class="code">${e.ev}</span> <b>${esc(e.t)}</b></p><p class="t2">${esc(e.src)} · ${esc(e.acc)}</p><p>${esc(e.what)}</p>${e.cf?'<p class="r10-cfl">Противоречие найдено: <span class="code">CG-01</span></p>':''}</li>`).reverse().join('');
 const q=inp?qForm(c):'';
 const top=done?`<div class="r10-done" role="status"><p><b>Результат готов.</b> <span class="t2">Отчёт ${TD.rep} v1 — в кабинете; письмо «Отчёт готов» ${c.mail.l2.st==='bounce'?'не доставлено':'отправлено'}.</span></p><a class="btn btn-p sm" href="#/research/${c.id}?s=result">Открыть результат</a></div>`:`<div class="r10-wbar"><span class="r10-pulse" aria-hidden="true"></span><span>${inp?'Требуется уточнение':'Выполняется'} · шаг <span class="n">${Math.min(s.i+1,EV.length)}</span> из <span class="n">${EV.length}</span> · вычисления, не ожидание</span><button type="button" class="lnk" data-act="w10-skip">Показать результат сразу (демо)</button></div>`;
 return `<div class="r10-work" id="w10">${top}${q}<section class="r10-ws" aria-labelledby="w10-h"><h2 class="h2" id="w10-h" tabindex="-1">Сейчас</h2>${six}</section>
<section class="r10-ws" aria-labelledby="w10-g"><h2 class="h3" id="w10-g">Проверки</h2>${gates}</section>
<section class="r10-ws" aria-labelledby="w10-f"><div class="sec-h"><h2 class="h3" id="w10-f">Знание по полям</h2></div>${cnt(counts(s.F))}<p class="t2">Счёт — по полям: одно поле — один вид знания. «Заявление продавца» — только поля продавца партии; предложения других продавцов — «сигнал конкуренции». Прочтение страницы продавца не подтверждает его заявление. Неизвестное не равно нулю.</p><div class="tbl-wrap" tabindex="0" role="region" aria-label="Знание по полям"><table class="tbl r10-t r10-ft"><thead><tr><th scope="col">Поле</th><th scope="col">Что установлено</th><th scope="col">Вид знания</th><th scope="col">Проверка</th></tr></thead><tbody>${rows}</tbody></table></div></section>
<section class="r10-ws" aria-labelledby="w10-e"><h2 class="h3" id="w10-e">Основания по мере получения</h2>${feed?`<ol class="r10-feed">${feed}</ol>`:'<p class="t2">Пока нет.</p>'}</section></div>`}
function qForm(c){const asked=c.run.askedIso||todayIso();return `<form class="r9-q r10-q" id="q10" novalidate aria-labelledby="q10-h"><h2 class="h3" id="q10-h" tabindex="-1">Количество: на странице продавца 1 500 шт., в поисковом фрагменте 1 200. Есть письменное подтверждение?</h2><p class="t2">Ответить до <b class="n ink">${plus14(asked)}</b> · 14 дней с вопроса. Без ответа работа продолжится, противоречие останется.</p>
<fieldset class="r9-opts"><legend class="sr-only">Ответ</legend><label class="r9-opt"><input type="radio" name="qa" value="no"><span>Нет — противоречие остаётся, вывод тот же</span></label><label class="r9-opt"><input type="radio" name="qa" value="doc"><span>Загрузить документ</span></label><div class="r9-doc" hidden><label class="t2" for="q10-f">В демо файл не анализируется: противоречие останется до проверки документа</label><input id="q10-f" type="file" name="file"></div></fieldset>
<p class="r10-err" id="q10-e" role="alert" hidden></p><div class="r9-qa"><button class="btn btn-p" type="submit">Ответить</button></div></form>`}
function workCard(c){const D9=P9().DEMO;if(!D9)return '';const L=D9.stages[c.sk]||[],Q=D9.q[c.sk];
 const n=c.run.st==='input'?L.findIndex(s=>s.q):c.run.st==='wait'?L.findIndex(s=>s.w):L.length;
 const items=L.map((s,i)=>{const k=i<n?(s.fail?'fail':s.nd?'nd':'done'):i===n?(c.run.st==='input'?'input':'wait'):'todo';return `<li class="r9-si" data-s="${k}"><span class="r9-sm" aria-hidden="true">${k==='wait'?LP.IC.clkd:k==='fail'?LP.IC.na:''}</span><div><p class="r9-sn">${esc(s.t)} <span class="r9-sw">· ${{done:'выполнено',fail:'источник недоступен',nd:'не выполнено',input:'требуется уточнение',wait:'ждём внешний ответ',todo:'впереди'}[k]}</span></p>${s.n&&k!=='todo'?`<p class="t2">${esc(s.n)}</p>`:''}${s.fail?`<p class="t2">${esc(s.fail)}</p>`:''}</div></li>`}).join('');
 const q=c.run.st==='input'&&Q?`<form class="r9-q r10-q" id="q10c" data-id="${c.id}" novalidate aria-labelledby="q10-h"><h2 class="h3" id="q10-h" tabindex="-1">${esc(Q.q)}</h2><p class="t2"><b class="ink">Почему нужен:</b> ${esc(Q.why)}</p><p class="t2">Ответить до <b class="n ink">${plus14(c.at)}</b> · 14 дней с вопроса</p><fieldset class="r9-opts"><legend class="sr-only">Ответ</legend><label class="r9-opt"><input type="radio" name="qa" value="a"><span>${esc(Q.opt)}</span></label><label class="r9-opt"><input type="radio" name="qa" value="own"><span>${esc(Q.own)}</span></label><div class="r9-own" hidden><label class="sr-only" for="q10c-t">Ваш ответ</label><textarea id="q10c-t" name="text" rows="2"></textarea></div><label class="r9-opt"><input type="radio" name="qa" value="doc"><span>${esc(Q.doc)}</span></label><div class="r9-doc" hidden><label class="t2" for="q10c-f">В демо файл не анализируется</label><input id="q10c-f" type="file" name="file"></div></fieldset><p class="r10-err" id="q10-e" role="alert" hidden></p><div class="r9-qa"><button class="btn btn-p" type="submit">Ответить</button><span class="t2">ответ без документа остаётся допущением</span></div></form>`:'';
 const wait=c.run.st==='wait'?`<p class="r10-note" data-k="wait"><b>Ждём внешний ответ</b> — задача у команды LotPrism; срок ответа в данных не задан. Это ожидание, а не вычисление.</p>`:'';
 return `<div class="r10-work">${q}${wait}<section class="r10-ws" aria-labelledby="w10-h"><h2 class="h2" id="w10-h" tabindex="-1">Ход</h2><ol class="r9-st">${items}</ol></section></div>`}

/* ══ графики ══ */
function figCost(){const tot=COST.reduce((a,x)=>a+x[1],0);const pc=v=>(v/tot*86).toFixed(2)+'%';
 return fig('Структура затрат базового сценария','£ за весь горизонт 90 дней · основание: сценарий 400 × £16.95, входы — допущения a1–a9',
 `<div class="ch-stack" role="img" aria-label="Строки базового сценария, лист 4, и неизвестные статьи без сумм">${COST.map((x,i)=>`<i class="ch-s" data-k="${x[2]}" data-i="${i}" style="width:${pc(x[1])}" title="${esc(x[0])}: ${gbp(x[1])}"></i>`).join('')}<i class="ch-s ch-u" style="width:14%" title="Неизвестно: сортировка, сборка троек, фото и листинг"></i></div>
<ul class="ch-lg">${COST.map((x,i)=>`<li><i class="ch-sw" data-k="${x[2]}" data-i="${i}" aria-hidden="true"></i><span>${esc(x[0])}</span><b class="n">${gbp(x[1])}</b></li>`).join('')}<li><i class="ch-sw ch-u" aria-hidden="true"></i><span>Сортировка, сборка троек, фото и листинг сверх бюджета</span><span class="hz">неизвестно</span></li></ul>`,
 'Строки базового сценария, лист 4. Заштрихованная часть — неизвестные статьи, сумм нет.')}
function figScen(){const mn=-617.58,mx=2057.81,span=mx-mn,z=(-mn/span*100);const bar=v=>{const l=v<0?(v-mn)/span*100:z,w=Math.abs(v)/span*100;return `<span class="ch-tr"><i class="ch-z" style="left:${z.toFixed(2)}%"></i><i class="ch-b${v<0?' ch-neg':''}" style="left:${l.toFixed(2)}%;width:${w.toFixed(2)}%"></i></span>`};
 const V=[['Прибыль по проданному',2],['Деньги на конец 90 дней',3],['Экономический результат',4]];
 return fig('Сценарии в трёх представлениях','£ · основание: исторический расчёт 30.09.2026, все входы — допущения',
 `<div class="ch-rows">${SC.map(s=>`<div class="ch-g"><p class="ch-gn"><b>${s[0]}</b> <span class="t2">${s[1]}</span></p>${V.map(v=>`<div class="ch-r"><span class="ch-n">${v[0]}</span>${bar(s[v[1]])}<span class="ch-v">${gb(s[v[1]])}</span></div>`).join('')}</div>`).join('')}</div>`,
 'Представления не складываются. Остаток в «деньгах» не учтён, в «прибыли по проданному» — по себестоимости. Цена ликвидации неизвестна.')}
function figSens(){const mn=-312.53,mx=725.31,span=mx-mn,z=-mn/span*100;const bar=v=>{const l=v<0?(v-mn)/span*100:z,w=Math.abs(v)/span*100;return `<span class="ch-tr"><i class="ch-z" style="left:${z.toFixed(2)}%"></i><i class="ch-b${v<0?' ch-neg':''}" style="left:${l.toFixed(2)}%;width:${w.toFixed(2)}%"></i></span>`};
 return fig('Чувствительность','£ · экономический результат и деньги на конец 90 дней · строки листа 4',
 `<div class="ch-rows">${SENS.map(s=>`<div class="ch-g"><p class="ch-gn">${esc(s[0])}</p><div class="ch-r"><span class="ch-n">Экон. результат</span>${bar(s[1])}<span class="ch-v">${gb(s[1])}</span></div><div class="ch-r"><span class="ch-n">Деньги</span>${bar(s[2])}<span class="ch-v">${gb(s[2])}</span></div></div>`).join('')}</div>`,
 'Запаса почти нет: 400 троек по £15.25 оставляют £6.56. Безубыточность — 344 тройки (на допущениях).')}
function figRest(){return fig('Непроданный остаток по сценариям','штук и £ по себестоимости £1.41 за шт. · основание: ev-10, на допущениях',
 `<div class="ch-rows">${SC.map(s=>`<div class="ch-r ch-r2"><span class="ch-n">${s[0]}</span><span class="ch-tr"><i class="ch-b ch-st" style="left:0;width:${(s[5]/600*100).toFixed(2)}%"></i></span><span class="ch-v"><b class="n">${s[5]} шт.</b> · £${s[6]}</span><span class="ch-liq">ликвидация: <span class="hz">неизвестна</span></span></div>`).join('')}</div>`,
 'При 1 200 шт. в партии остатка в базовом сценарии нет, а 500 троек невозможны.')}
const fig=(q,m,body,cap)=>`<figure class="ch10"><figcaption><p class="ch-q">${q}</p><p class="t2">${m}</p></figcaption>${body}<p class="ch-cap t2">${cap}</p></figure>`;

/* ══ результат ══ */
function result(c){if(c.hist)return resultCard(c);if(c.kind==='own')return '';
 const tbl=`<div class="r10-hist"><p class="r10-hk">Исторический условный сценарий, не прогноз</p><p class="t2">Все входы — допущения (приложение B), итоги — рассчитано на допущениях. GBP, до пенса.</p><div class="tbl-wrap" tabindex="0" role="region" aria-label="Три сценария в трёх представлениях"><table class="tbl r10-t r10-num"><thead><tr><th scope="col">Сценарий</th><th scope="col" class="num">Прибыль по проданному</th><th scope="col" class="num">Деньги на конец 90 дней</th><th scope="col" class="num">Экономический результат</th><th scope="col" class="num">Остаток</th></tr></thead><tbody>${SC.map(s=>`<tr><th scope="row">${s[0]} <span class="t2">${s[1]}</span></th><td class="num">${gb(s[2])}</td><td class="num">${gb(s[3])}</td><td class="num">${gb(s[4])}</td><td class="num"><span class="n">${s[5]} шт. · £${s[6]}</span></td></tr>`).join('')}</tbody></table></div><div class="r10-scm">${SC.map(s=>`<section class="r10-scb" aria-label="${s[0]}: ${s[1]}"><p><b>${s[0]}</b> <span class="t2">${s[1]}</span></p><dl><div><dt>Прибыль по проданному</dt><dd>${gb(s[2])}</dd></div><div><dt>Деньги на конец 90 дней</dt><dd>${gb(s[3])}</dd></div><div><dt>Экономический результат</dt><dd>${gb(s[4])}</dd></div><div><dt>Остаток</dt><dd><span class="n">${s[5]} шт. · £${s[6]}</span></dd></div></dl></section>`).join('')}</div><p class="t2">Прибыль по проданному — до резерва претензий, налога и времени. Деньги — партия оплачена целиком. Экономический результат — после времени владельца £150.</p></div>`;
 const more=[['why','Почему такой вывод','G01–G10 · правила R1–R6',why()],['basis','Основания','приложение A · ev-01…ev-12',apxA()],['ass','Допущения','приложение B · a1–a10',apxB()],['plan','План действий','5 шагов · черновики не отправлены',plan()]].map(([k,t,s,b])=>`<section>${LP.acc('r10'+k,`<span class="sq">${t}</span><span class="tot">${s}</span>`,b)}</section>`).join('');
 return `<div class="r10-res">
<section class="r10-v" aria-labelledby="v10-h"><p class="eyebrow">1 · Вывод</p><h2 class="r10-vt" id="v10-h" tabindex="-1">Не покупать сейчас — нужны данные</h2><p class="r10-vs">Подтверждённых стоп-факторов нет — это не отказ. ${NOT_BUY.replace('Оплата исследования','Вывод')}</p><p class="t2"><span class="code">NEEDS_EVIDENCE</span> · отчёт <span class="code">${TD.rep}</span> v1 · ${TD.date}</p></section>
<section aria-labelledby="v10-r"><p class="eyebrow" id="v10-r">2 · Три причины</p><ol class="r10-why"><li><span>${gt('G01','unk')}</span><div><b>Состав и количество партии не подтверждены</b><p class="t2">Размеры и дизайны неизвестны. Страница продавца — 1 500 шт., поисковый фрагмент — 1 200 шт.; при проверке страница ответила 403 и не прочитана.</p></div></li><li><span>${gt('G03','unk')}</span><div><b>400 продаж троек по £16.95 — допущение</b><p class="t2">Найдены только активные предложения других наборов. Состоявшихся продаж сопоставимых троек нет.</p></div></li><li><span>${gt('G04','unk')}</span><div><b>Нет полной котировки склада</b><p class="t2">Сортировка, сборка троек, фото и листинг не оценены; есть только публичный прайс отдельных операций.</p></div></li></ol></section>
<section class="r10-eco" aria-labelledby="v10-e"><p class="eyebrow" id="v10-e">3 · Ключевая экономика</p>
<div class="r10-k3"><div class="r10-kb"><h3 class="h3">Предел закупки</h3><dl class="r10-kv2"><div><dt>Максимальная цена</dt><dd>${UNK('не определена')}</dd></div><div><dt>Объём</dt><dd>${UNK('не определён')}</dd></div></dl><p class="t2">Нужны состав, три статьи затрат, подтверждённая выручка, ваша цель и предел убытка; лот продаётся целиком, количество спорно.</p></div>
<div class="r10-kb"><h3 class="h3">Полная стоимость</h3><dl class="r10-kv2"><div><dt>Закупка до продаж, не меньше</dt><dd>${gb(1665)} ${kk('ass')}</dd></div><div><dt>С подготовкой и фото до продаж</dt><dd>${gb(2265)} ${kk('ass')}</dd></div></dl><div class="r10-fc" role="img" aria-label="Известная часть £2 265.00, недостающие статьи без суммы"><i style="flex:1665"></i><i style="flex:600" class="r10-fc2"></i><i class="r10-fc3"></i></div><p class="t2">Не хватает: сортировка, сборка троек, фото и листинг — заштрихованы, суммы нет. Цена — со страницы продавца, бюджет — без котировок.</p></div>
<div class="r10-kb"><h3 class="h3">Прибыль и деньги</h3><dl class="r10-kv2"><div><dt>Прибыль</dt><dd>${UNK('не определена')}</dd></div><div><dt>Пиковая потребность в деньгах</dt><dd>${UNK('не определена')}</dd></div></dl></div></div>
${tbl}
<div class="r10-ch">${figCost()}${figScen()}${figSens()}${figRest()}</div>
<p class="r10-nocash t2">Движения денег по неделям в материалах нет — такой график не строится.</p></section>
<section class="r10-adv" aria-labelledby="v10-a"><p class="eyebrow" id="v10-a">4 · Неблагоприятный случай: 300 троек по £15.25</p><dl class="r10-kv2 r10-advl"><div><dt>Деньги на конец 90 дней</dt><dd>${gb(-467.58)}</dd></div><div><dt>Экономический результат</dt><dd>${gb(-617.58)}</dd></div><div><dt>Остаток 600 шт. по себестоимости</dt><dd>${gb(846)}</dd></div><div><dt>Цена ликвидации остатка</dt><dd>${UNK('неизвестна')}</dd></div></dl><p class="t2">Рассчитано на допущениях. Прибыль по проданному +£687.56, а денег −£467.58: 600 футболок на складе.</p></section>
<div class="r10-g2"><section aria-labelledby="v10-m"><p class="eyebrow" id="v10-m">5 · Чего не хватает</p><ul class="r10-miss">${MISS.map(m=>`<li><span class="ms u" aria-hidden="true"></span><span>${m[0]}</span><span class="t2">${m[1]}</span></li>`).join('')}</ul></section>
<section aria-labelledby="v10-c"><p class="eyebrow" id="v10-c">Что изменит вывод</p><ul class="r10-chg">${CHANGE.map(x=>`<li><span>${esc(x[0])}</span><span class="t2">→ ${esc(x[1])}</span></li>`).join('')}</ul></section></div>
<div class="r10-g2"><section aria-labelledby="v10-n"><p class="eyebrow" id="v10-n">6 · Следующий шаг</p><p>Отправить подготовленные запросы продавцу и складу, выгрузить продажи сопоставимых троек на eBay, задать пределы — затем обновить исследование.</p><a class="lnk" href="#acc-r10plan" data-act="r10-plan">Открыть план и черновики</a></section>
<section aria-labelledby="v10-u"><p class="eyebrow" id="v10-u">7 · Действует до</p><p><b class="n">${TD.until}</b> <span class="t2">— раньше всего истекает тариф eBay (7 дней). Скачанный PDF не обновляется.</span></p></section></div>
<div class="r10-docs"><a class="btn btn-s" href="#/research/${c.id}/docs">Документы · отчёт 9 листов, меморандум 2 листа</a><a class="lnk" href="#/research/${c.id}/letters">Письма</a></div>
<div class="u2 r10-more">${more}</div></div>`}
function why(){return `<div class="tbl-wrap" tabindex="0" role="region" aria-label="Проверки G01–G10"><table class="tbl r10-t"><thead><tr><th scope="col">Проверка</th><th scope="col">Результат</th><th scope="col">Почему</th><th scope="col">Что закроет</th></tr></thead><tbody>${Object.keys(GN).map(g=>`<tr><th scope="row">${GN[g]} <span class="code">${g}</span></th><td>${g==='G10'?gt(g,'pass')+'<span class="t2"> машинная · человек не запрашивается</span>':gt(g,g==='G09'?'pass':'unk')}</td><td>${esc(GTXT[g][0])}</td><td class="t2">${esc(GTXT[g][1])}</td></tr>`).join('')}</tbody></table></div>
<h3 class="h3">Как получено действие</h3><ul class="r10-rl">${RULES.map(r=>`<li><span class="code">${r[0]}</span><span>${esc(r[1])}</span></li>`).join('')}</ul>
<details class="r10-x r10-codes"><summary>Коды для сверки</summary><p class="t2"><span class="code">NEEDS_EVIDENCE</span> · доказательства <span class="code">CONFLICTED</span> · экономика <span class="code">UNDETERMINED</span>, основание <span class="code">CONDITIONAL</span> · покрытие <span class="code">SUPPORTED</span> · правило <span class="code">R6</span> · <span class="code">research-decision/1</span></p></details>`}
function apxA(){return `<p class="t2">Недоступная страница не выдаётся за прочитанную; поисковый фрагмент не закрывает ни одного существенного поля; активное объявление не доказывает продажи.</p><div class="tbl-wrap" tabindex="0" role="region" aria-label="Основания"><table class="tbl r10-t"><thead><tr><th scope="col">ID</th><th scope="col">Источник</th><th scope="col">Получено</th><th scope="col">Вид знания</th><th scope="col">Что подтверждает и чего нет</th></tr></thead><tbody>${APXA.map(a=>`<tr><td class="code">${a[0]}</td><th scope="row">${esc(a[1])}</th><td class="t2">${esc(a[2])}</td><td>${kk(a[3],a[4])}</td><td>${esc(a[5])}</td></tr>`).join('')}</tbody></table></div>`}
function apxB(){return `<p class="t2">Каждое допущение — вход сценариев. Ни одно не подтверждено.</p><div class="tbl-wrap" tabindex="0" role="region" aria-label="Допущения"><table class="tbl r10-t"><thead><tr><th scope="col">#</th><th scope="col">Допущение</th><th scope="col">Чем заменить</th></tr></thead><tbody>${APXB.map(a=>`<tr><td class="code">${a[0]}</td><td>${esc(a[1])}</td><td class="t2">${esc(a[2])}</td></tr>`).join('')}</tbody></table></div>`}
function plan(){return `<p class="t2">Исследование ничего не отправляет, не регистрирует и не покупает. Предел закупочной цены в запросы не включается.</p><ol class="r10-plan">${PLAN.map((p,i)=>`<li><div class="r10-plh"><span class="n">${i+1}</span><b>${p[0]}</b><span class="t2">${p[1]}</span><span class="code">${p[3]}</span><span class="tag">${p[4]}</span></div>${p[5]?`<details class="r10-x"><summary>Черновик · подготовлен, не отправлен</summary><p class="r10-draft" id="dr10-${i}">${esc(p[2])}</p><button type="button" class="btn btn-s sm" data-act="r10-copy" data-i="${i}">Скопировать текст</button></details>`:`<p class="t2">${esc(p[2])}</p>`}</li>`).join('')}</ol>`}
function resultCard(c){const res=P9().res;if(!res)return '';const x=res({sk:c.sk,f:null,qa:c.qa||null});if(!x)return '';const GNs=Object.values(GN);
 const km=(l,k)=>/^Закупка/.test(l)&&k!=='unk'?'seller':k;
 return `<div class="r10-res"><section class="r10-v" aria-labelledby="v10-h"><p class="eyebrow">Вывод</p><h2 class="r10-vt" id="v10-h" tabindex="-1">Не покупать сейчас — нужны данные</h2><p class="r10-vs">Подтверждённых стоп-факторов нет — это не отказ.${x.partial?' Результат частичный.':''}</p><p class="t2">Вывод карточки не становится выводом исследования; результат не перезаписывает ваше решение.</p></section>
<section><p class="eyebrow">Три причины</p><ol class="r10-why">${x.why.map(w=>{const g='G'+pad(w[0]);return `<li><span>${gt(g,'unk')}</span><div><b>${GNs[w[0]-1]}</b><p class="t2">${esc(w[1])}</p></div></li>`}).join('')}</ol></section>
<section class="r10-eco"><p class="eyebrow">Ключевая экономика</p><dl class="r10-kv2">${x.money.map(m=>`<div><dt>${esc(m[0])}</dt><dd>${m[1]==='неизвестно'?UNK('неизвестно'):'<span class="n">'+esc(m[1])+'</span>'} ${kk(km(m[0],m[2]))}<span class="t2"> ${esc(m[3])}</span></dd></div>`).join('')}</dl><p class="t2">${esc(x.limit)}</p></section>
<section class="r10-adv"><p class="eyebrow">Неблагоприятный случай</p><p>${esc(x.adverse)}</p></section>
<div class="r10-g2"><section><p class="eyebrow">Чего не хватает</p><ul class="r10-miss">${x.miss.map(m=>`<li><span class="ms u" aria-hidden="true"></span><span>${esc(m)}</span></li>`).join('')}</ul></section><section><p class="eyebrow">Что изменит вывод</p><ul class="r10-chg">${x.change.map(y=>`<li><span>${esc(y[0])}</span><span class="t2">→ ${esc(y[1])}</span></li>`).join('')}</ul></section></div>
<div class="r10-g2"><section><p class="eyebrow">Следующий шаг</p><ul class="r10-ul">${x.next.map(t=>`<li>${esc(t)}</li>`).join('')}</ul></section><section><p class="eyebrow">Действует до</p><p>${x.until==='не задано'?'срок действия не задан':'<b class="n">'+esc(x.until)+'</b>'} <span class="t2">· ${esc(x.untilWhy)}</span></p></section></div>
<p class="r10-note">Покрытие amazon.de — только исследование. Документ в демо не собран; формат — как у <span class="code">${TD.rep}</span>.</p>
<div class="u2 r10-more"><section>${LP.acc('r10c'+c.id,'<span class="sq">Основания</span><span class="tot">'+x.src.length+' источника</span>',`<ul class="r10-ul">${x.src.map(s=>`<li><b>${esc(s[0])}</b> <span class="t2">· ${esc(s[1])} · ${esc(s[2])} · ${esc(s[3])}</span></li>`).join('')}</ul>`)}</section></div></div>`}

/* ══ документы и письма ══ */
const DOCS=[{id:'report',t:'Полный отчёт',code:TD.rep+' v1',fmt:'9 листов A4 · PDF + в кабинете',file:'cto/report.html'},{id:'memo',t:'Меморандум «Краткое решение»',code:TD.memo+' v1',fmt:'2 листа A4 · лист 2 — вариант «отказ или недостаточность данных»',file:'cto/memo.html'}];
function docs(c,q){if(!isTD(c)||c.stage!=='result')return `<p class="t2">${c.kind==='card'?'Документ в демо не собран; формат — как у '+TD.rep+'.':'Документов пока нет: они появятся после результата.'}</p>`;
 const open=q.get('doc');const l2=c.mail.l2;const d=DOCS.find(x=>x.id===open);
 return `<div class="r10-docl"><h2 class="h2" id="d10-h" tabindex="-1">Кабинет: документы</h2><p class="t2">Кабинет, PDF и вложение письма — одна версия. Сверка: <b>«Не покупать сейчас — нужны данные»</b> · закупка <span class="n">£1 665.00</span> · неблагоприятно <span class="n">−£467.58</span> и <span class="n">−£617.58</span> · <span class="n">£413.29</span> — только условный сценарий · до <span class="n">${TD.until}</span>.</p>
${ST.prof==='paid'?'<p class="r10-note">Вы прошли платный путь (демо, £79 по гипотезе C3). Документ кейса исторический: на листе 4 указано «£0 (профиль Founder)».</p>':''}
<ul class="r10-dl">${DOCS.map(x=>`<li><div><p><b>${x.t}</b> <span class="code">${x.code}</span></p><p class="t2">${x.fmt} · ${TD.date} · действует до ${TD.until}</p></div><div class="r10-da"><a class="btn btn-s sm" href="#/research/${c.id}/docs?doc=${x.id}" id="d10-v-${x.id}"${open===x.id?' aria-current="true"':''}>Смотреть</a><button type="button" class="btn btn-s sm" data-act="d10-pdf" data-doc="${x.id}">Скачать PDF</button><a class="lnk" href="${x.file}" target="_blank" rel="noopener">Открыть отдельно<span class="sr-only"> (новая вкладка)</span></a></div></li>`).join('')}
<li class="r10-dlx"><div><p><b>Инвестиционный меморандум</b> <span class="tag">формат описан, макета нет</span></p><p class="t2">4–6 листов A4 · строится только по опубликованному отчёту · для партнёра или соинвестора</p></div><details class="r10-x"><summary>Разделы</summary><ol class="r10-ol2">${INV.map(x=>`<li><b>${x[0]}</b> <span class="t2">${x[1]}</span></li>`).join('')}</ol></details></li>
<li class="r10-dlx"><div><p><b>Обновление исследования</b> <span class="tag">формат описан, макета нет</span></p><p class="t2">1–2 листа A4 · строится из разницы двух версий: было LPR-… vN → стало vN+1</p></div><details class="r10-x"><summary>Разделы</summary><ol class="r10-ol2">${UPD.map(x=>`<li><b>${x[0]}</b> <span class="t2">${x[1]}</span></li>`).join('')}</ol></details></li></ul>
<p class="t2">Скачать PDF: в демо PDF формируется печатью браузера — выберите «Сохранить как PDF».</p>
<section class="r10-ml" aria-labelledby="d10-m"><h3 class="h3" id="d10-m">Письмо «Отчёт готов»</h3><p>${l2.st==='bounce'?`<span class="st10" data-s="bounce"><i aria-hidden="true"></i>Не доставлено</span> на ${esc(c.email)}`:l2.st==='sent'?`<span class="st10" data-s="sent"><i aria-hidden="true"></i>Отправлено</span> на ${esc(c.email)} · ${esc(l2.at||'')}`:'<span class="st10" data-s="ready"><i aria-hidden="true"></i>Отчёт готов, письмо не отправлялось</span>'} <span class="t2">· «отправлено» не значит «получено»</span></p>${l2.log.length?`<ul class="r10-ul">${l2.log.map(t=>`<li class="n">${esc(t)}</li>`).join('')}</ul>`:''}
${l2.st==='bounce'?`<form id="d10-fix" class="r10-mail" novalidate><label class="h3" for="d10-em">Исправьте адрес</label><div class="r10-cap"><input id="d10-em" name="email" type="email" value="${esc(c.email)}" aria-describedby="d10-emh"><button class="btn btn-p sm" type="submit">Отправить снова (демо)</button></div><p class="t2" id="d10-emh">${emailHint(c.email)}</p></form>`:`<button type="button" class="btn btn-s sm" data-act="d10-resend">Отправить письмо повторно (демо)</button>`}
<a class="lnk" href="#/research/${c.id}/letters">Посмотреть письма</a></section>
${d?`<section class="r10-view" aria-labelledby="d10-vh"><div class="r10-vb"><h3 class="h3" id="d10-vh" tabindex="-1">${d.t} · ${d.code}</h3><a class="lnk" href="#/research/${c.id}/docs">Закрыть</a></div><iframe id="d10-frame" src="${d.file}" title="${d.t} ${d.code}"></iframe></section>`:''}</div>`}
const INV=[['Что рассматриваем','предмет, рынок, каналы, роль, объём, горизонт'],['Решение и три причины','обязательна фраза «не разрешение на закупку и не инвестиционная рекомендация»'],['Сумма и предел','сумма закупки, предел цены, предельный объём, пиковая потребность в деньгах; предел цены печатается только с согласия, иначе «не раскрывается»'],['Прибыль, деньги, риск','три представления, полный проект и «с текущего момента», окупаемость, безубыточность; условные числа — только в рамке «условный сценарий»'],['Контрсценарий','неблагоприятный и ликвидация, пороги, при которых результат становится отрицательным'],['Расчёт','входы с видом знания и источником, формулы статей, версия расчёта; неизвестное штрихуется, не ноль'],['Источники','вид, когда получено, статус получения, что подтверждает'],['Приложения','допущения и чем их заменить, противоречия, версии, ссылка проверки'],['Срок действия','']];
const UPD=[['Что рассматриваем','ссылки «было → стало»'],['Решение','было → стало'],['Что изменилось','каждое поле, было/стало, вид знания было/стало, новое основание; новые и разрешённые противоречия; истёкшие основания'],['Влияние на деньги','базовый и неблагоприятный сценарии в каждом представлении, предел цены, пиковая потребность — было → стало → разница; разница — только когда оба значения определены'],['Какие проверки повторены','G01–G10 было → стало; без изменений — одной строкой'],['Оставшиеся условия, которые изменят вывод',''],['Срок действия','прежний документ становится «заменён новой версией»']];
function letters(c){if(!isTD(c)||c.stage==='setup'||c.ord.st!=='paid')return '<p class="t2">Писем пока нет: подтверждение приходит после оплаты.</p>';const paid=ST.prof==='paid',l2=c.mail.l2,rd=c.stage==='result';
 const hd=(subj,pre,to)=>`<div class="lt-env"><p><span class="t2">Тема</span> <b>${subj}</b></p><p><span class="t2">Кому</span> ${esc(to)}</p><p class="t2">${pre}</p></div>`;
 const brand=`<div class="lt-lh"><img src="../assets/logo-light.svg" alt="LotPrism" width="132" height="17"><span>Research</span></div>`;
 return `<div class="r10-lts"><h2 class="h2" id="l10-h" tabindex="-1">Письма</h2><p class="t2">Макеты. Почтовой отправки в продукте нет. Подтверждение заказа и готовый отчёт — разные сообщения.</p>
<section class="lt10" aria-label="Письмо 1: подтверждение заказа"><p class="lt-st"><span class="st10" data-s="sent"><i aria-hidden="true"></i>Отправлено ${esc(c.ord.at||'')}</span></p><p class="t2">Номер заказа ${TD.order} — пример формата.</p>${hd('LotPrism · заказ '+TD.order+' подтверждён: '+TD.short,'Исследование начато. О готовом отчёте придёт отдельное письмо.',c.email)}
<article class="lt-b">${brand}<h3>Заказ ${TD.order} подтверждён</h3><p class="t2">номер — пример формата</p><dl><div><dt>Предмет</dt><dd>${TD.title}</dd></div><div><dt>Рынок</dt><dd>GB · eBay UK · GBP · горизонт 90 дней</dd></div><div><dt>Исследование</dt><dd>полное исследование партии · C3</dd></div><div><dt>Оплата</dt><dd>${paid?'£79 — демо, деньги не списаны; гипотеза пилотного тарифа, не действующая цена':'£0 — профиль Founder, этапы S0–S2'}</dd></div></dl><p><b>Что дальше.</b> Исследование идёт. Если понадобится уточнение, спросим в кабинете. Готовый отчёт придёт отдельным письмом и будет доступен в кабинете независимо от доставки.</p><p class="lt-f">${NOT_BUY} LotPrism ничего не покупает и не отправляет от вашего имени.</p></article></section>
<section class="lt10" aria-label="Письмо 2: отчёт готов"><p class="lt-st">${!rd?'<span class="st10" data-s="draft"><i aria-hidden="true"></i>Ещё не отправлено — отчёт не готов</span>':l2.st==='bounce'?'<span class="st10" data-s="bounce"><i aria-hidden="true"></i>Не доставлено</span> <a href="#/research/'+c.id+'/docs">Исправить адрес</a>':l2.st==='sent'?'<span class="st10" data-s="sent"><i aria-hidden="true"></i>Отправлено '+esc(l2.at||'')+'</span>':'<span class="st10" data-s="ready"><i aria-hidden="true"></i>Не отправлялось</span>'}</p>${hd('LotPrism · отчёт готов: '+TD.short,'Не покупать сейчас — нужны данные. Действует до '+TD.until+'.',c.email)}
<article class="lt-b">${brand}<h3>Отчёт готов: ${TD.short}</h3><p class="lt-v"><b>Не покупать сейчас — нужны данные:</b> состав и количество партии, спрос и затраты склада не подтверждены. Это не разрешение на закупку.</p><p class="lt-att"><span class="lt-pdf" aria-hidden="true">PDF</span><span><b>${TD.pdf}</b><span class="t2">полный отчёт · 9 листов A4 · v1 · ${TD.date}</span></span></p><p><a class="lt-btn" href="#/research/${c.id}?s=result">Открыть в LotPrism</a></p><p>Действует до <b>${TD.until}</b>. Скачанный PDF не обновляется — актуальность проверяйте в LotPrism.</p><p class="lt-f">Не инвестиционная рекомендация и не разрешение на закупку.</p></article></section></div>`}

/* ══ страница дела ══ */
function casePage(c,view,q){const body=view==='setup'?setup(c):view==='order'?order(c):view==='work'?work(c):view==='result'?result(c):view==='docs'?docs(c,q):letters(c);
 return `<main class="main r10" data-screen-label="Research ${c.id} · ${view}">${caseHead(c,view)}<div id="cb10">${body}</div></main>`}
const defView=c=>c.hist?(c.run.st==='done'?'result':'work'):c.stage;

/* ══ выполнение (демо) ══ */
let tmr=0;
function startRun(c){c.run.st='run';c.stage='work';save();arm()}
function arm(){clearTimeout(tmr);const c=CS(TD.id);if(!c||c.run.st!=='run')return;tmr=setTimeout(tick,RM()?450:1300)}
function tick(){const c=CS(TD.id);if(!c||c.run.st!=='run')return;c.run.i=(c.run.i||0)+1;const s=EV[c.run.i-1];
 if(s&&s.pause&&!c.run.q){c.run.st='input';c.run.askedIso=todayIso();ev('Требуется уточнение: количество 1 500 или 1 200','#/research/'+c.id+'?s=work',c.id);say('Требуется уточнение: количество. Ответьте на вопрос исследования')}
 if(c.run.i>=EV.length){finish(c)}save();repaintWork();arm()}
function finish(c){c.run.st='done';c.run.i=EV.length;c.stage='result';const t=nowT();ev('Отчёт готов: '+TD.short,'#/research/'+c.id+'?s=result',c.id);c.mail.l2={st:'sent',at:t,log:['отправлено '+t]};ev('Письмо «Отчёт готов» отправлено на '+c.email,'#/research/'+c.id+'/letters',c.id);say('Результат готов. Отчёт в кабинете')}
function repaintWork(){const r=LP.parse();const m=r.p.match(/^\/research\/(R-[A-Z0-9-]+)$/);if(!m||m[1]!==TD.id)return;const c=CS(TD.id);const v=r.q.get('s')||defView(c);if(v!=='work'){render();return}
 const ae=document.activeElement,aid=ae&&ae.id;$('#cb10').innerHTML=T(work(c));const ln=$('.ln10');if(ln)ln.outerHTML=T(line(c,'work'));const ch=$('.r10-meta .st10');if(ch)ch.outerHTML=chip(c);LP.shell9&&0;
 if(aid&&document.getElementById(aid))document.getElementById(aid).focus({preventScroll:true});if(c.run.st==='input'){const h=$('#q10-h');h&&h.focus({preventScroll:true})}}

/* ══ маршрут ══ */
function render(){const r=LP.parse();LP.p10(r)}
LP.p10n=()=>Object.values(ST.cases).filter(c=>c.run&&c.run.st==='input').length;
LP.p10=function(r){const p=r.p;let m,html=null,focus='#view h1';
 if(p==='/research'){html=home()}
 else if(p==='/research/new'){newFrom(r.q);return true}
 else if(m=p.match(/^\/research\/(R-[A-Z0-9-]+)(?:\/(docs|letters))?$/)){let c=CS(m[1]);if(!c&&m[1]===TD.id)c=tdDone();
  if(!c)html=`<main class="main r10"><h1 class="h1">Исследование не найдено</h1><p class="t2">Возможно, демо Research сброшено.</p><a href="#/research">← Research</a></main>`;
  else{let v=m[2]||r.q.get('s')||defView(c);if(!c.hist&&(v==='result'||v==='work')&&!(c.kind==='td'&&c.ord.st==='paid'))v=c.stage;if(v==='result'&&c.kind==='td'&&c.stage!=='result')v=c.stage;if(v==='work'&&c.kind==='td'&&c.ord.st!=='paid')v=c.stage;html=casePage(c,v,r.q);
   focus=r.q.get('doc')?'#d10-vh':'#view h1'}}
 else return false;
 $('#view').innerHTML=T(html);proto10();
 const key=location.hash;if(LP._p10last!==key){LP._p10last=key;scrollTo(0,0);const h=$(focus);if(h){h.tabIndex=-1;h.focus({preventScroll:true})}}
 return true};
function tdDone(){const c=tdNew(true);Object.assign(c,{shown:1,stage:'result',ord:{st:'paid',at:'30.09.2026'},run:{i:EV.length,st:'done'},at:'2026-09-30'});c.mail.l1={at:'30.09.2026'};c.mail.l2={st:'sent',at:'30.09.2026',log:['отправлено 30.09.2026']};ST.prof='founder';save();return c}
function newFrom(q){const subj=q.get('subj'),id=q.get('id'),from=q.get('from')||'';
 if(subj&&id){const sk=(subj==='lot'?'lot:':subj==='hyp'?'hyp:':'item:')+id;const sj=(P9().DEMO||{subj:{}}).subj[sk];
  const cid='R-N'+(++ST.n);ST.cases[cid]={id:cid,kind:sj?'card':'own',sk,task:'check',sub:subj==='lot'?'mixed':'single',url:'',ident:id,text:'',files:[],goal:'resale',mk:'DE',ch:['amazon.de'],chNeed:subj==='lot',cap:'',capNone:true,hor:'90',horOwn:'',depth:'full',email:'irina.becker@demo-handel.example',step:1,stage:'setup',ord:{st:'draft'},run:{st:'idle'},mail:{l1:null,l2:{st:'none',log:[]}},at:todayIso(),from};
  if(sj)ST.cases[cid].kind='card',ST.cases[cid].fresh=1;save();location.replace('#/research/'+cid);return}
 location.replace('#/research')}

/* ══ события ══ */
Object.assign(LP.ACT,{
 't10-example':()=>{const t=$('#f10-text');if(t){t.value=EXAMPLE;t.focus()}},
 't10-more':b=>{const r=$(`#f10-start input[name=task][value=${b.dataset.task}]`);if(r)r.checked=true;$('#f10-start').dataset.sub=b.dataset.sub||'';const t=$('#f10-text');t&&t.focus();say('Выбрано: '+b.textContent)},
 's10-edit':b=>{const c=cur();c.step=+b.dataset.n;save();render();focusStep(c.step)},
 't10-td':()=>{const c=tdNew(true);save();location.hash='#/research/'+c.id+'?s=order'},
 'o10-pay':()=>{const c=cur();const em=$('#o10-em');if(em){c.email=em.value.trim()}if(!emailOk(c.email)){const h=$('#o10-emh');h.textContent=emailHint(c.email);em.focus();return}
  if(ST.prof==='paid'&&c.ord.st==='draft'){c.ord.st='await';save();render();setTimeout(()=>{const x=CS(c.id);if(x.ord.st!=='await')return;paid(x)},RM()?300:1200);return}paid(c)},
 'w10-skip':()=>{const c=cur();if(c.run.st==='input')c.run.q={v:'skip',at:nowT()};finish(c);save();clearTimeout(tmr);location.hash='#/research/'+c.id+'?s=result'},
 'r10-plan':()=>{const b=$('[aria-controls="acc-r10plan"]');if(b&&b.getAttribute('aria-expanded')!=='true')b.click();b&&b.focus()},
 'r10-copy':b=>{const t=$('#dr10-'+b.dataset.i).textContent;(navigator.clipboard?navigator.clipboard.writeText(t):Promise.reject()).then(()=>LP.toast&&LP.toast('na','Текст скопирован · не отправлен'),()=>LP.toast&&LP.toast('na','Скопируйте текст вручную'))},
 'd10-pdf':b=>{const c=cur();const r=LP.parse();if(r.q.get('doc')!==b.dataset.doc){sessionStorage.setItem('lp10:print','1');location.hash='#/research/'+c.id+'/docs?doc='+b.dataset.doc;return}printFrame()},
 'd10-resend':()=>{const c=cur();const t=nowT();c.mail.l2.st='sent';c.mail.l2.at=t;c.mail.l2.log.push('отправлено повторно '+t);ev('Письмо «Отчёт готов» отправлено повторно','#/research/'+c.id+'/letters',c.id);save();render();say('Отправлено повторно '+t+'. Это не подтверждение получения')},
 't10-restart':()=>{clearTimeout(tmr);delete ST.cases[TD.id];ST.ev=ST.ev.filter(e=>e.id!==TD.id);save();location.hash='#/research';setTimeout(()=>{const t=$('#f10-text');if(t){t.value=EXAMPLE;t.focus()}},60)},
 'p10-reset':()=>{clearTimeout(tmr);ST=seed();save();location.hash='#/research';render()}
});
function printFrame(){const f=$('#d10-frame');if(!f)return;const go=()=>{try{f.contentWindow.focus();f.contentWindow.print()}catch(e){window.open(f.src,'_blank')}};if(f.contentDocument&&f.contentDocument.readyState==='complete')go();else f.addEventListener('load',go,{once:true})}
function paid(c){c.ord.st='paid';c.ord.at=nowT();c.mail.l1={at:c.ord.at};ev('Заказ '+TD.order+' '+(ST.prof==='paid'?'оплачен (демо)':'подтверждён')+' · подтверждение отправлено','#/research/'+c.id+'/letters',c.id);c.run={i:0,st:'run'};c.stage='work';c._seen=0;save();arm();location.hash='#/research/'+c.id+'?s=work';say('Заказ подтверждён. Работа началась')}
const cur=()=>{const m=LP.parse().p.match(/^\/research\/(R-[A-Z0-9-]+)/);return m&&CS(m[1])};
function focusStep(n){const h=$('#ps10-'+n);if(h){h.focus({preventScroll:true});const t=h.getBoundingClientRect().top;if(t<72||t>innerHeight*.6)scrollBy(0,t-96);const s=h.closest('.r10-ps');if(s&&!RM())s.animate([{opacity:.4,transform:'translateY(6px)'},{opacity:1,transform:'none'}],{duration:220,easing:'cubic-bezier(.23,1,.32,1)'})}}
const err=(id,msg,el)=>{const e=$(id);e.hidden=false;e.textContent=msg;el&&el.focus()};
document.addEventListener('submit',e=>{const f=e.target;if(!f.id||!/^(f10-start|s10-[123]|o10-mail|q10|q10c|d10-fix)$/.test(f.id))return;e.preventDefault();e.stopImmediatePropagation();
 if(f.id==='f10-start'){const task=(f.querySelector('[name=task]:checked')||{}).value||'check';const text=f.text.value.trim();const files=[...(f.files.files||[])].map(x=>x.name);
  if(!text&&!files.length)return err('#f10-e','Опишите предмет, вставьте ссылку или добавьте файл. Можно подставить пример TopDown.',f.text);
  const td=task==='check'&&/topdown/i.test(text);const url=(text.match(/https?:\/\/\S+/)||[''])[0];const rest=text.replace(url,'').trim();
  let c;if(td){c=tdNew(false);c.text=rest||TD.text;c.url=url||TD.url;c.files=files}else{const id='R-N'+(++ST.n);c=ST.cases[id]={id,kind:'own',task,sub:f.dataset.sub||(task==='check'?'mixed':'single'),url,ident:url?'':(/^\S+$/.test(rest)?rest:''),text:/^\S+$/.test(rest)&&!url?'':rest,files,goal:'resale',mk:'GB',ch:['eBay UK'],chNeed:false,cap:'',capNone:true,hor:'90',horOwn:'',depth:'full',email:'irina.becker@demo-handel.example',step:1,stage:'setup',ord:{st:'draft'},run:{st:'idle'},mail:{l1:null,l2:{st:'none',log:[]}},at:todayIso()}}
  save();location.hash='#/research/'+c.id+'?s=setup';return}
 const c=cur();if(!c)return;
 if(f.id==='s10-1'){const url=f.url.value.trim(),ident=f.ident.value.trim(),text=f.text.value.trim(),nf=[...(f.files.files||[])].map(x=>x.name);
  if(!url&&!ident&&!text&&!nf.length&&!(c.files||[]).length&&c.kind!=='card')return err('#s10-1e','Нужен хотя бы один вход: ссылка, идентификатор, описание, документ или фото',f.url);
  Object.assign(c,{sub:(f.querySelector('[name=sub]:checked')||{}).value||c.sub,url,ident,text,files:(c.files||[]).concat(nf)});c.step=2}
 if(f.id==='s10-2'){const ch=[...f.querySelectorAll('[name=ch]:checked')].map(x=>x.value),need=f.chNeed.checked;if(!ch.length&&!need)return err('#s10-2e','Выберите канал или «Нужен подбор»',f.querySelector('[name=ch]'));
  Object.assign(c,{goal:(f.querySelector('[name=goal]:checked')||{}).value,mk:f.mk.value,ch,chNeed:need});c.step=3}
 if(f.id==='s10-3'){const none=f.capNone.checked,cap=f.cap.value.trim(),hor=(f.querySelector('[name=hor]:checked')||{}).value,ho=f.horOwn.value.trim();
  if(!none&&!/^\d[\d\s.,]*$/.test(cap))return err('#s10-3e','Введите сумму числом или отметьте «Пока не определён»',f.cap);
  if(hor==='own'&&!/^\d{1,3}$/.test(ho))return err('#s10-3e','Укажите свой срок в днях',f.horOwn);
  Object.assign(c,{capNone:none,cap:none?'':cap,hor,horOwn:ho,depth:(f.querySelector('[name=depth]:checked')||{}).value});c.step=4;c.stage='order';save();location.hash='#/research/'+c.id+'?s=order';return}
 if(f.id==='o10-mail'){c.email=f.email.value.trim();$('#o10-emh').textContent=emailHint(c.email);save();return}
 if(f.id==='d10-fix'){const v=f.email.value.trim();if(!emailOk(v)){$('#d10-emh').textContent=emailHint(v);f.email.focus();return}const t=nowT();c.email=v;c.mail.l2={st:'sent',at:t,log:c.mail.l2.log.concat(['адрес исправлен, отправлено снова '+t])};save();render();say('Отправлено снова '+t);return}
 if(f.id==='q10'){const v=(f.querySelector('[name=qa]:checked')||{}).value,file=f.file.files&&f.file.files[0]?f.file.files[0].name:'';
  if(!v)return err('#q10-e','Выберите ответ',f.querySelector('[name=qa]'));if(v==='doc'&&!file)return err('#q10-e','Выберите файл',f.file);
  c.run.q={v,file,at:nowT()};c.run.st='run';ev(v==='no'?'Ваш ответ: письменного подтверждения нет — противоречие остаётся':'Документ «'+file+'» приложен; в демо не анализируется — противоречие остаётся','#/research/'+c.id+'?s=work',c.id);save();arm();repaintWork();say('Ответ записан. Работа продолжается');const h=$('#w10-h');h&&h.focus();return}
 if(f.id==='q10c'){const v=(f.querySelector('[name=qa]:checked')||{}).value,text=f.text.value.trim(),file=f.file.files&&f.file.files[0]?f.file.files[0].name:'';
  if(!v)return err('#q10-e','Выберите ответ',f.querySelector('[name=qa]'));if(v==='own'&&!text)return err('#q10-e','Напишите свой ответ',f.text);if(v==='doc'&&!file)return err('#q10-e','Выберите файл',f.file);
  c.qa={v,text,file,at:nowIso()};c.run.st='done';c.stage='result';ev('Ответ записан: '+titleOf(c),'#/research/'+c.id,c.id);save();location.hash='#/research/'+c.id+'?s=result';LP._p10last='';return}
 save();render();focusStep(c.step)},true);
document.addEventListener('change',e=>{const t=e.target;if(!t.closest||!t.closest('.r10,#p10'))return;e.stopImmediatePropagation();
 if(t.id==='f10-files')$('#f10-fl').textContent=[...t.files].map(x=>x.name).join(', ');
 if(t.name==='capNone'){const i=$('#s10-cap');i.disabled=t.checked;if(t.checked)i.value='';$('#s10-capn').hidden=!t.checked;if(!t.checked)i.focus()}
 if(t.name==='hor'){$('#s10-ho').hidden=t.value!=='own'}
 if(t.name==='mk'){const c=cur();c.mk=t.value;c.ch=[MK[t.value][2][0]];save();render();focusStep(2)}
 if(t.name==='chNeed'&&t.checked)$$('[name=ch]',t.form).forEach(x=>x.checked=false);if(t.name==='ch'&&t.checked&&t.form.chNeed)t.form.chNeed.checked=false;
 if(t.name==='qa'){const fm=t.form;const o=$('.r9-own',fm),d=$('.r9-doc',fm);if(o)o.hidden=t.value!=='own';if(d)d.hidden=t.value!=='doc';$('#q10-e').hidden=true}
 if(t.name==='email'&&t.id==='o10-em'){const c=cur();c.email=t.value.trim();$('#o10-emh').textContent=emailHint(c.email);save()}
 if(t.name==='p10prof'){ST.prof=t.value;save();if(/^\/research/.test(LP.parse().p))render()}
 if(t.name==='p10st'){setState(t.value)}},true);
document.addEventListener('input',e=>{if(e.target.id==='o10-em'){$('#o10-emh').textContent=emailHint(e.target.value.trim())}if(e.target.id==='d10-em'){$('#d10-emh').textContent=emailHint(e.target.value.trim())}if(e.target.id==='f10-text'){const x=$('#f10-e');if(x)x.hidden=true}});

/* ══ панель прототипа ══ */
const PST=[['await','Оплата ожидается'],['fail','Оплата не прошла'],['run','Выполняется'],['input','Требуется уточнение'],['ready','Отчёт готов'],['sent','Письмо отправлено'],['bounce','Письмо не доставлено']];
function setState(s){clearTimeout(tmr);const c=CS(TD.id)||tdNew(true);c.step=4;const t=nowT();
 if(s==='await'||s==='fail'){c.stage='order';c.ord={st:s};c.run={i:0,st:'idle'};c.mail.l2={st:'none',log:[]}}
 else{c.ord={st:'paid',at:c.ord.at||t};c.mail.l1={at:c.ord.at};
  if(s==='run'){c.stage='work';c.run={i:c.run&&c.run.st==='run'?c.run.i:0,st:'run',q:null};c._seen=0;c.mail.l2={st:'none',log:[]}}
  else if(s==='input'){c.stage='work';c.run={i:3,st:'input',askedIso:todayIso()};c.mail.l2={st:'none',log:[]}}
  else{c.stage='result';c.run={i:EV.length,st:'done'};c.mail.l2=s==='ready'?{st:'none',log:[]}:s==='sent'?{st:'sent',at:t,log:['отправлено '+t]}:{st:'bounce',at:t,log:['отправлено '+t,'не доставлено: адрес отклонён почтовым сервером (демо)']}}}
 save();arm();const h='#/research/'+c.id+(s==='await'||s==='fail'?'?s=order':s==='run'||s==='input'?'?s=work':s==='ready'?'?s=result':'/docs');if(location.hash===h)render();else location.hash=h}
function curSt(){const c=CS(TD.id);if(!c||c.stage==='setup')return '';if(c.ord.st==='await'||c.ord.st==='fail')return c.ord.st;if(c.ord.st!=='paid')return '';if(c.run.st==='run')return 'run';if(c.run.st==='input')return 'input';return c.mail.l2.st==='sent'?'sent':c.mail.l2.st==='bounce'?'bounce':'ready'}
function proto10(){const b=$('#proto-b');if(!b)return;const o=$('#r9-proto',b);if(o)o.remove();let f=$('#p10',b);const cs=curSt();
 const html=`<legend>Research (демо)</legend><fieldset class="p10-g"><legend class="t2">Оплата</legend><label><input type="radio" name="p10prof" value="founder"${ST.prof!=='paid'?' checked':''}>Профиль Founder · к оплате £0</label><label><input type="radio" name="p10prof" value="paid"${ST.prof==='paid'?' checked':''}>Платный путь (демо) · £79, гипотеза C3</label></fieldset><fieldset class="p10-g"><legend class="t2">Состояние заказа TopDown</legend>${PST.map(s=>`<label><input type="radio" name="p10st" value="${s[0]}"${cs===s[0]?' checked':''}>${s[1]}</label>`).join('')}</fieldset><button class="btn btn-s sm" type="button" data-act="p10-reset">Сбросить демо Research</button>`;
 if(!f){f=document.createElement('fieldset');f.id='p10';b.appendChild(f)}f.innerHTML=T(html)}

/* ══ входы из карточек и партии; дашборд ══ */
const enc=encodeURIComponent;
function cardBlock(id){const sk=(LP.NL.includes(id)?'hyp:':'item:')+id;const map={'item:P01':'R-P01','hyp:P06':'R-D02','hyp:P15':'R-D04'};const c=CS(map[sk]);const sj=(P9().DEMO||{subj:{}}).subj[sk];if(!sj)return '';
 const lbl=sk.startsWith('hyp')?'Проверить гипотезу':'Исследовать товар';const go=`#/research/new?subj=${sk.split(':')[0]}&amp;id=${id}&amp;from=${enc(location.hash)}`;
 const st=c?`<p class="r9-meta">${chip(c)}${c.code?'<span class="code">'+c.code+'</span>':''}<span class="t2">${c.run.st==='done'?'Не покупать сейчас — нужны данные · документ в демо не собран; формат — как у '+TD.rep:c.run.st==='input'?'вопрос к вам: '+esc((P9().DEMO.q[sk]||{}).q||''):'ждём внешний ответ'}</span></p>`:'<p>Исследование не запускалось.</p>';
 const nf=c&&c.run.st==='done'?`<div class="r9-nf"><h3 class="h3">Новое из исследования</h3><p class="t2">Сравниваются только реальные версии данных: поле, было (источник и дата) → стало (источник и дата).</p><p><span class="ms u" aria-hidden="true"></span> Сравнивать не с чем: у полей карточки одна версия данных, исследование ${c.code||''} второй версии полей не создавало.</p><p class="t2">Карточка и ваше решение не меняются.</p></div>`:'';
 return `<section class="gs r9-c r10-cb" aria-labelledby="r9c-h"><div class="r9-ch"><h2 class="h2" id="r9c-h">Исследование</h2></div>${st}<div class="r9-ca">${c?`<a class="btn btn-s sm" data-ret data-sk="${sk}" id="r9c-open" href="#/research/${c.id}">${c.run.st==='done'?'Открыть результат':'Открыть идущее'}</a>`:''}<a class="btn btn-s sm" data-ret data-sk="${sk}" id="r9c-new" href="${go}">${lbl}</a></div>${nf}</section>`}
function lotBlock(){return `<section class="r9-c r9-cl r10-cb" aria-labelledby="r9c-h"><div class="r9-ch"><h2 class="h2" id="r9c-h">Исследование партии</h2></div><p class="t2">Покрытие amazon.de — только исследование; лучший вывод — «нужны данные». Полного отчёта по этой партии нет: документ в демо не собран; формат — как у ${TD.rep}.</p><div class="r9-ca"><a class="btn btn-s sm" data-ret data-sk="lot:BT-01" id="r9c-new" href="#/research/new?subj=lot&amp;id=BT-01&amp;from=${enc(location.hash)}">Проверить партию</a></div></section>`}
function post(){if(S().view!=='user')return;const p=LP.parse().p;
 if(p.startsWith('/p/')){const id=p.slice(3),old=$('.r9-c');if(old){const h=cardBlock(id);if(h)old.outerHTML=T(h)}}
 if(p==='/research/BT-01'){const old=$('.r9-c');if(old)old.outerHTML=T(lotBlock())}
 if(p==='/'||p===''){const a=$('#dm-rs');if(a)a.setAttribute('href','#/research')}
 proto10()}
const S=()=>LP.S;
/* возврат из дела: «← К товару» ведёт на адрес карточки с выборкой; прокрутку и фокус восстанавливает механизм P8/P9 (lp9:ret) */
document.addEventListener('click',e=>{
 const o=e.target.closest('.r10-cb a[data-ret]');if(o&&o.dataset.sk){ST.ret=ST.ret||{};ST.ret[o.dataset.sk]={h:location.hash,y:scrollY,f:o.id};save()}
 const a=e.target.closest('#r10-back');if(a){LP._p10last='';const r=(ST.ret||{})[a.dataset.sk];if(r&&r.h===a.getAttribute('href')&&r.f)ss.set('lp9:ret',{h:r.h,y:r.y,f:r.f})}},true);
const _r=LP.route;LP.route=function(){_r();post()};
addEventListener('pageshow',()=>{});
if(sessionStorage.getItem('lp10:print')){}
const _p10=LP.p10;LP.p10=function(r){const ok=_p10(r);if(ok&&sessionStorage.getItem('lp10:print')&&$('#d10-frame')){sessionStorage.removeItem('lp10:print');printFrame()}return ok};
arm();LP.route();
})();
