/* LotPrism · доводка 9 · Research как раздел приложения. Основа — P8 (доводка-8/). Новое — здесь и в prototype-9.css. */
(function(){
'use strict';
const LP=window.LP,{D,$,$$,esc,T,fdt,K,IC,REG,E4,S,thumb}=LP;
const RS=D.research,B=RS.main_batch,PR=D.P01_research,EC=D.P01_offer_economics;
const SRC={};PR.sources.forEach(s=>SRC[s.id]=s);
const BY={};RS.buyers.forEach(b=>BY[b.id]=b);
const NOW='2026-10-01T10:00';
const d5=iso=>fdt(iso).slice(0,5);
const plus14=iso=>{const m=iso.match(/^(\d{4})-(\d\d)-(\d\d)/);const d=new Date(Date.UTC(+m[1],+m[2]-1,+m[3]+14));return String(d.getUTCDate()).padStart(2,'0')+'.'+String(d.getUTCMonth()+1).padStart(2,'0')};
const plural=n=>n%10===1&&n%100!==11?'исследование':[2,3,4].includes(n%10)&&![12,13,14].includes(n%100)?'исследования':'исследований';

/* ══ подписи (из пакета CTO, где есть) ══ */
const STL={input:'Требуется уточнение',wait:'Ждём внешний ответ',run:'Идёт',done:'Готово',part:'Частично',cancel:'Отменено'};
const ACTL={NEEDS_EVIDENCE:'Не покупать сейчас — нужны данные',REJECT:'Отказаться от сделки',READY_FOR_REVIEW:'Готово к проверке решения',PILOT_ONLY:'Допустим ограниченный тест'};
const KN={conf:'<span class="k f">Подтверждено</span>',calc:'<span class="k c">Рассчитано</span>',ass:'<span class="k a">Допущение</span>',unk:'<span class="k u">Неизвестно</span>'};
const KW={conf:'Подтверждено',calc:'Рассчитано',ass:'Допущение',unk:'Неизвестно'};
const GN=['Товар и состав','Условия закупки','Спрос','Исполнение и затраты','Право продажи и требования','Экономика против целей','Неблагоприятный случай','Актуальность и конфликты','Программные проверки','Проверка'];
const gc=i=>'G'+String(i).padStart(2,'0');
const chip=st=>`<span class="st9" data-st="${st}"><i aria-hidden="true"></i>${STL[st]}</span>`;
const NOSTOP='Подтверждённых стоп-факторов нет — это не отказ';
const COVER='amazon.de · EUR — в предложении CTO не поддержано (в демо CTO: eBay UK · GBP)';
const FOOT='Не инвестиционная рекомендация и не разрешение на закупку';
const LOTIMG='../assets/img/q16.jpg';

/* ══ демо Research: сценарий выполнения ══
   Предметы, этапы, вопросы и формулировки результата — сценарий интерфейса. Числа, даты, источники — из D (research.*, P01_research, registry P06/P15, charts.E4). Новых цен, сроков и итогов нет. */
const F06=REG.P06.freshness,R06=REG.P06.research,R15=REG.P15.research,S1=SRC.S1,S2=SRC.S2,S3=SRC.S3,S4=SRC.S4;
const DEMO={
 subj:{
  'item:P01':{kind:'item',id:'P01',short:'Чайник',title:REG.P01.title_ru,task:'Проверка товара',home:'#/p/P01',back:'← К товару Чайник',
   src:'Карточка перепродажи «Чайник» · версия от 28.09',
   q:'Уточнить у поставщика число посылок на 60 шт. и объём (400 или 450 мл), запросить образец',
   ctx:[['Товар',REG.P01.title_ru,'conf','листинг amazon.de · код — EAN листинга, как в карточке'],['Рынок','amazon.de · EUR · цены без НДС','conf','настройка карточки'],['Предложение S1','7,60 € без НДС за шт. · мин. заказ 60 шт.','conf','в карточке ФАКТ · прайс 25.09'],['Предложение S2','8,10 € без НДС','ass','в карточке УСЛОВНО · единица не подтверждена'],['Ограничение','объём: 450 мл в прайсе S1, 400 мл на листинге','conf','в карточке ФАКТ · противоречие не разрешено'],['Ограничение','доставка: 6,90 € за посылку, число посылок — неизвестно','unk','в карточке «доставка не посчитана»']],
   nottr:'вывод карточки «Кандидат для проверки» — вывод карточки не становится выводом исследования',
   asked:[['Каналы','amazon.de · FBA','из карточки']],
   need:[[1,'Образец: объём 400 или 450 мл'],[4,'Число посылок на 60 шт.'],[2,'Упаковка у S2: за шт. или за упаковку']]},
  'hyp:P06':{kind:'hyp',id:'P06',short:'Банки',title:REG.P06.title_ru,task:'Проверка гипотезы нового листинга',home:'#/p/P06',back:'← К гипотезе Банки',code:R06.brief,
   src:'Карточка нового листинга «Банки»',q:'Стоит ли запускать собственный набор',
   ctx:[['Гипотеза',REG.P06.title_ru,'ass','гипотеза листинга'],['Состав','10 шт., 3 объёма: 250 / 500 / 750 мл','ass','в карточке УСЛОВНО · не проверен'],['Закупка','5,40 € за набор','ass','в карточке УСЛОВНО · цена за набор'],['Цена продажи','сценарий: нижняя цена двух сопоставимых наборов','ass','в карточке УСЛОВНО'],['Рынок','amazon.de · EUR','conf','настройка карточки'],['Аналоги','архив рынка (поиск аналогов) · '+fdt(F06.provider_answered_at),'conf','источник карточки'],['Ограничение','доставка от поставщика «по запросу»','unk','в карточке неизвестно']],
   nottr:'вывод карточки «Кандидат для проверки»',asked:[['Каналы','amazon.de · FBA','из карточки']],
   need:[[1,'Состав набора — документ поставщика'],[4,'Оценка FBA по своему набору'],[3,'Сигнал спроса на набор']]},
  'hyp:P15':{kind:'hyp',id:'P15',short:'Баночки для специй',title:REG.P15.title_ru,task:'Проверка гипотезы нового листинга',home:'#/p/P15',back:'← К гипотезе Баночки для специй',code:R15.brief,src:'Карточка нового листинга «Баночки для специй»',q:'Есть ли аналоги и цена продажи',ctx:[],need:[]},
  'lot:BT-01':{kind:'lot',id:'BT-01',short:'BT-01',title:B.title,task:'Проверка оптовой партии',home:'#/research/BT-01',back:'← К партии BT-01',
   src:'Партия BT-01 · страница лота сохранена '+fdt(B.found.page_observed_at),q:'Стоит ли брать партию и каким маршрутом сбыта',
   ctx:[['Партия',`${B.positions_count} позиций · ${B.units} ед. · ${B.pallets_count} паллет ${B.pallet_type.split(',')[0]}`,'conf','страница лота · '+fdt(B.found.page_observed_at)],['Цена',B.price.lot_net.display+' за партию без НДС','conf',B.price.lot_net.basis],['Единица продажи',B.four_conditions[0].value,'conf','страница лота'],['Срок',B.terms[1].value,'conf','страница лота'],['Манифест',B.four_conditions[1].value,'conf',B.four_conditions[1].state],['Состояние',B.four_conditions[2].value,'conf',B.four_conditions[2].state],['Продавец',B.seller.verification,'unk',B.seller.note],['Доставка','«по запросу, после выбора способа»','unk','ответ продавца 30.09']],
   nottr:'потолок партии из P8 снят (ДЕМО-для-CD §8) и не переносится',asked:[],
   need:[[2,'Проверка продавца: реестр, номер НДС (VIES)'],[2,'Цена доставки Познань → склад'],[1,'Фото паллет 1, 3, 5, 6'],[3,'Письменное предложение покупателя: цена, количество, срок']]}
 },
 stages:{
  'lot:BT-01':[{t:'Партия найдена, страница лота сохранена',n:fdt(RS.stages[0].at)},{t:'Проверка предложения: продавец',q:1,n:RS.stages[1].note},{t:'Экономика маршрутов — до неизвестных расходов',n:RS.stages[2].note},{t:'Маршруты и покупатели',n:RS.stages[3].note},{t:'Условия покупки и продажи сопоставлены',nd:'не выполнено: '+RS.stages[4].note}],
  'item:P01':[{t:'Задача принята',n:PR.question},{t:'S4 · '+S4.what,fail:'Не прочитано: каталог за регистрацией · '+d5(S4.observed_at)},{t:'S2 · '+S2.what,n:'прочитано '+d5(S2.observed_at)+' · только цена: упаковка '+S2.pack+', EAN '+S2.ean}, {t:'S3 · '+S3.what,n:'прочитано '+d5(S3.observed_at)+' · розница — только сравнение'},{t:'S1 · '+S1.what,n:'прочитано '+d5(S1.observed_at)+' · '+S1.price_net.display+' без НДС, мин. заказ '+S1.moq+', EAN '+S1.ean},{t:'Противоречие',n:PR.contradiction.what+' — '+PR.contradiction.status},{t:'Вывод',n:fdt(PR.answered_at)}],
  'hyp:P06':[{t:'Гипотеза принята: набор 10 шт., 3 объёма'},{t:'Аналоги на amazon.de',n:'архив рынка · '+fdt(F06.provider_answered_at)},{t:'Состав набора',q:1},{t:'Затраты по аналогу',n:'FBA — по аналогу 10 шт.; комиссия 15 % по умолчанию'},{t:'Спрос на ваш набор',nd:'не установлено: спрос — гипотеза'}],
  'hyp:P15':[{t:'Задача записана',n:fdt(R15.updated_at)},{t:'Ответ команды LotPrism',w:1},{t:'Аналоги, цена продажи, закупочная цена',n:'сейчас неизвестно: 3 статьи'},{t:'Вывод'}]
 },
 q:{
  'lot:BT-01':{q:'Проверен ли продавец?',why:'Личность продавца скрыта площадкой до членства; реестр и номер НДС не смотрели. Оплата — предоплата 100 %, возврат не принимается: без проверки гейт «Условия закупки» не пройти.',warn:'Предложение продавца действует до 08.10 18:00 — ответ после этой даты вывод не изменит.',opt:'Нет, не проверен',own:'Ввести своё',doc:'Проверен — загрузить документ'},
  'hyp:P06':{q:'Подтвердите состав набора',why:'Состав не проверен. От него зависят FBA по аналогу 10 шт. и сопоставимость с аналогами.',opt:'Подтверждаю: 10 шт., 3 объёма — 250 / 500 / 750 мл',own:'Состав другой — ввести',doc:'Загрузить документ поставщика'}
 }
};
const seed=()=>[
 {id:'R-P01',sk:'item:P01',code:REG.P01.research.brief,st:'done',n:7,at:PR.asked_at,fin:PR.answered_at,from:'',seed:1,f:null},
 {id:'R-D02',sk:'hyp:P06',code:R06.brief,st:'input',n:2,at:R06.updated_at,asked:R06.updated_at,from:'',seed:1,f:null},
 {id:'R-D04',sk:'hyp:P15',code:R15.brief,st:'wait',n:1,at:R15.updated_at,from:'',seed:1,f:null}];
const RID={'lot:BT-01':'R-B01','item:P01':'R-P01','hyp:P06':'R-D02','hyp:P15':'R-D04'};

/* ══ состояние (sessionStorage) ══ */
const ss={get:k=>{try{return JSON.parse(sessionStorage.getItem(k)||'null')}catch(e){return null}},set:(k,v)=>{try{sessionStorage.setItem(k,JSON.stringify(v))}catch(e){}},del:k=>{try{sessionStorage.removeItem(k)}catch(e){}}};
let ST=ss.get('lp9');const FRESH=!ST||!ST.runs;if(FRESH)ST={runs:seed(),empty:false,hist:[],prep:{}};
const save=()=>ss.set('lp9',ST);save();
const runs=()=>ST.empty?[]:ST.runs;
const runOf=id=>runs().find(r=>r.id===id);
const runBy=sk=>runs().filter(r=>r.sk===sk&&r.st!=='cancel').pop();
const prevOf=r=>{const i=ST.runs.indexOf(r);return ST.runs.filter((x,j)=>j<i&&x.sk===r.sk&&['done','part'].includes(x.st)).pop()};
const polya=n=>n%10===1&&n%100!==11?'поле':[2,3,4].includes(n%10)&&![12,13,14].includes(n%100)?'поля':'полей';
const ansSrc=a=>'ваш ответ'+(a.demo?' (демо)':'')+' · '+d5(a.at);
const sellerT=a=>!a||a.v==='a'?'Продавец не проверен: реестр и номер НДС не смотрели.':a.v==='doc'?'Продавец: ваш ответ — документ приложен, в демо не проверяется.':`Продавец: ${a.demo?'ваш ответ (демо)':'ваш ответ'} «${a.text}» — допущение, не проверка.`;
/* прямой адрес: исследование показывается сразу в итоговом состоянии (демо) */
const DIRECT={'R-B01':'lot:BT-01','R-P01':'item:P01','R-D02':'hyp:P06'};
function finalize(id){const sk=DIRECT[id];let r=ST.runs.find(x=>x.id===id);const L=DEMO.stages[sk],Q=DEMO.q[sk];
 if(!r){r={id,sk,code:'',at:NOW,asked:NOW,from:'',f:null};ST.runs.push(r)}
 r.n=L.length;r.st=L.some(s=>s.nd)?'part':'done';r.fin=r.fin||NOW;r.direct=1;if(Q&&!r.qa)r.qa={v:'demo',text:Q.opt,at:NOW,demo:1};
 ST.hist.push({run:id,at:NOW,t:'Демо: показано сразу в итоговом состоянии'+(Q?'; ответ записан как допущение — ваш ответ (демо): «'+Q.opt+'»':'')});ST.empty=false;save();return r}
const active=r=>['run','input','wait'].includes(r.st);
const nInput=()=>LP.p10n?LP.p10n():runs().filter(r=>r.st==='input').length;
const SJ=r=>DEMO.subj[r.sk];
const thumbOf=sk=>sk.startsWith('lot:')?`<img class="th" src="${LOTIMG}" alt="Иллюстрация" width="40" height="50">`:thumb(DEMO.subj[sk].id);

/* ══ результат: утверждения с классом знания и этапом, на котором они появились ══ */
function claims(r){const sk=r.sk,a=r.qa;const L=[];const c=(k,s,t,src)=>L.push({k,s,t,src});
 if(sk==='lot:BT-01'){
  c('conf',0,`Цена партии ${B.price.lot_net.display} без НДС`,'страница лота · '+fdt(B.found.page_observed_at));c('conf',0,'Единица продажи: '+B.four_conditions[0].value,'страница лота');c('conf',0,'Срок предложения '+B.terms[1].value,'страница лота');c('conf',0,'Оплата: '+B.terms[2].value,'страница лота');c('conf',0,'Возврат: '+B.terms[7].value,'страница лота');c('conf',0,'Манифест: '+B.four_conditions[1].value,'заявлен продавцом');c('conf',0,'Состояние: '+B.four_conditions[2].value,B.four_conditions[2].state);
  c('conf',1,'Ответ продавца: фото паллет 2 и 4; доставка «по запросу, после выбора способа»; срок до 08.10','через площадку · '+fdt(RS.history[4].at));
  c('calc',2,`Средняя цена за ед. ${B.price.per_unit_avg_net.display}`,B.price.per_unit_avg_net.basis);c('calc',2,`6 паллет по одной — ${B.price.six_pallets_by_pallet.display}`,B.price.six_pallets_by_pallet.basis);c('calc',2,'Деньги на пике по маршрутам: '+rng(RS.routes.map(x=>x.cash_need.peak.cents)),'предоплата + членство; доставка — неизвестно');
  c('calc',3,`Сумма пределов 9 позиций для FBA ${B.fba_route_ceiling_sum.total.display}`,B.fba_route_ceiling_sum.caption);
  c('ass',2,'Цены продажи по маршрутам','ваше допущение · Томас Вебер · экономика v2, 01.10 08:40');c('ass',2,'НДС: '+B.price.vat.scenario_A.label,B.price.vat.scenario_A.condition);c('ass',2,'Сроки маршрутов: от 1 недели до 7,6 мес.','гипотеза');
  c('conf',3,'Сообщение покупателя В получено: 3,40–3,60 € за ед. после фото и осмотра','30.09 17:05 · содержание необязывающее, не спрос');
  if(!a||a.v==='a')c('unk',1,'Продавец: реестр и номер НДС не проверены',a?ansSrc(a):'данные партии');else c('ass',1,a.v==='doc'?`Продавец проверен — ваш ответ, документ «${a.file||'без имени'}»; в демо документ не читается`:`Продавец: ваш ответ «${a.text}»`,ansSrc(a));
  c('unk',1,'Доставка Познань → склад','«по запросу»');c('unk',1,'Документы происхождения','не указаны');c('unk',2,'НДС по сценарию Б',B.price.vat.scenario_B.cash_vat.why);c('unk',2,'Брак и расхождение с манифестом','заявлено 84 упаковки; фото 2 из 6 паллет');c('unk',3,'Подтверждённое предложение покупателя','подтверждённых 0 из 6')}
 if(sk==='item:P01'){
  c('calc',0,'Предел 9,60 € без НДС за шт. при 30 %','правило карточки · значение по умолчанию, порогом не утверждено');
  c('unk',1,'S4: цена','каталог за регистрацией · '+d5(S4.observed_at));
  c('conf',2,'S2: 8,10 € без НДС — только цена','S2 · '+d5(S2.observed_at));c('unk',2,'Упаковка у S2','на странице не указана');
  c('conf',3,'S3: розница 19,90 € с НДС — только сравнение','S3 · '+d5(S3.observed_at));
  c('conf',4,'S1: 7,60 € без НДС за шт., мин. заказ 60, EAN совпал','S1 · '+d5(S1.observed_at));c('conf',4,'S1: доставка 6,90 € за посылку','S1 · '+d5(S1.observed_at));c('calc',4,`Товар при мин. заказе ${EC.goods_at_moq.display}`,'60 × 7,60 €');
  PR.assumptions.forEach(t=>c('ass',4,t,'допущение исследования'));c('unk',4,'Сколько посылок нужно на 60 шт.','S1 не указал');
  c('unk',5,'Качество и объём (400 или 450 мл)','противоречие не разрешено');
  c('ass',6,`Известная часть выплаты ${EC.cash_known.display}`,'с НДС 19 % DE — сценарий');c('ass',6,`Результат по учтённой стоимости ${EC.lot_result_counted.display}`,'до доставки')}
 if(sk==='hyp:P06'){
  c('ass',0,'Закупка 5,40 € за набор','условие «за набор»');c('unk',0,'Доставка от поставщика','«по запросу»');
  c('conf',1,'Аналоги найдены','архив рынка · '+fdt(F06.provider_answered_at));c('ass',1,'Цена продажи','сценарий: нижняя цена двух сопоставимых наборов');
  c('ass',2,a?(a.v==='a'?'Состав: 10 шт., 3 объёма — ваш ответ':a.v==='doc'?`Состав: документ «${a.file||'без имени'}» — в демо не читается`:`Состав: ваш ответ «${a.text}»`):'Состав набора — не проверен',a?ansSrc(a)+' · без документа поставщика — допущение':'ждёт вашего ответа');
  c('calc',3,'Предел 8,90 € за набор при 30 %','от сценарной цены продажи');c('ass',3,'Комиссия Amazon 15 %','по умолчанию');c('ass',3,'FBA по аналогу 10 шт.','допущение');c('ass',3,'Доставка до склада Amazon','допущение конфигурации');c('unk',3,'Собственный GTIN и листинг','');c('unk',3,'Подготовка, хранение, возвраты, реклама запуска','');
  c('unk',4,'Спрос на ваш набор','гипотеза')}
 if(sk==='hyp:P15')REG.P15.completeness.items.forEach(i=>c('unk',2,i.name,i.note||''));
 return L}
const rng=a=>{const lo=Math.min(...a),hi=Math.max(...a);return LP.eur(lo)+(hi!==lo?' – '+LP.eur(hi):'')};
function tally(r,all){const n=all?99:r.n;const t={conf:0,calc:0,ass:0,unk:0};claims(r).forEach(c=>{if(c.s<n)t[c.k]++});return t}
const cnt=t=>`<p class="r9-cnt" aria-label="Счётчик знания">${['conf','calc','ass','unk'].map(k=>`<span>${KN[k]} <b class="n">${t[k]}</b></span>`).join('')}</p>`;
const unkN=x=>x.unknown_costs.filter(c=>c.kind==='UNKNOWN').length;
const untilT=x=>x.until==='не задано'?'срок действия не задан':'действует до '+x.until;
const goalTxt=f=>!f||!f.goal?'цель не задана':f.goal;
function res(r){const sk=r.sk,f=r.f||{},a=r.qa;const g6=f.goal?['не проверено','цель «'+f.goal+'»'+(f.capNone?' · капитал пока не определён':f.cap?' · капитал '+f.cap+' €':'')+' — экономика посчитана до неизвестных расходов, сравнивать с целью рано']:['не проверено','цель не задана'];
 const g9=['не выполнялись','в демо программные проверки не запускаются'],g10=['не проведена','проверку вывода вторым человеком никто не выполнял'];
 if(sk==='lot:BT-01'){const R=RS.routes,u=R.map(unkN);
  return {action:'NEEDS_EVIDENCE',partial:true,noStop:true,
   what:`Партия BT-01 · ${B.positions_count} позиций, ${B.units} ед., ${B.pallets_count} паллет · ${B.price.lot_net.display} без НДС за партию · срок предложения до 08.10 18:00`,
   why:[[2,'Доставка неизвестна: «по запросу, после выбора способа». '+sellerT(a)],[3,'Покупатели — кандидаты: 6, подтверждённых 0. Один ориентировочный интерес к паллетам 1 и 3 — необязывающий.'],[4,`Результат маршрутов посчитан до неизвестных расходов: в каждом маршруте не посчитаны ${Math.min(...u)}–${Math.max(...u)} статей. Неизвестное — не ноль.`]],
   miss:['Цена доставки Познань → склад или согласие продавца на самовывоз покупателем','Проверка продавца: реестр, номер НДС (VIES)','Фото паллет 1, 3, 5, 6 — получены только 2 и 4','Письменное предложение покупателя: цена, количество, условия, срок'],
   next:['Повторить запрос продавцу: способ и цена доставки, фото остальных паллет','Решить, отправлять ли черновик покупателю А — подготовлен 01.10 09:30, не отправлен'],
   until:'08.10.2026 18:00',untilWhy:'срок предложения продавца',
   limit:`Предел закупки партии не определён: цена партии не распределена по позициям. Сумма пределов 9 позиций для FBA — ${B.fba_route_ceiling_sum.total.display} (рассчитано), с ценой партии не сравнивается.`,
   money:[['Цена партии',B.price.lot_net.display,'conf','без НДС · предоплата 100 %'],['Деньги на пике',rng(R.map(x=>x.cash_need.peak.cents)),'calc','по 4 маршрутам · + доставка — неизвестно'],['Результат по проданному',LP.eur(Math.min(...R.map(x=>x.result_before_unknown.low.cents)))+' … '+LP.eur(Math.max(...R.map(x=>x.result_before_unknown.high.cents))),'ass','по маршрутам, до неизвестных расходов'],['Экономический итог','неизвестно','unk','непроданный остаток — не ноль']],
   adverse:`Маршрут «${R[1].name}»: если лот Б без покупателя — ${R[1].remainder.units} ед. остаются на складе. Маршрут «${R[3].name}»: результат от ${R[3].result_before_unknown.low.display} до неизвестных расходов. Брак и расхождение с манифестом — неизвестно.`,
   gates:[['нужны данные','манифест 14 строк, EAN у 13; точность не проверена; фото 2 из 6 паллет'],['нужны данные','доставка неизвестна; продавец '+(a&&a.v==='doc'?'— документ приложен, не проверен':a&&a.v!=='a'?'— ваш ответ, допущение':'не проверен')+'; возврат не принимается'],['нужны данные','6 кандидатов, подтверждённых 0; 1 ориентировочный интерес'],['нужны данные','неизвестные статьи по маршрутам; приёмка по § 377 HGB — отдельный этап'],['нужны данные','свободная продажа в ЕС — заявлено продавцом; допуск брендов на amazon.de не проверен; документы происхождения неизвестны'],g6,['посчитан частично',`остаток ${R[1].remainder.units} ед. при непроданном лоте Б; результат от ${R[3].result_before_unknown.low.display} до неизвестных`],['в силе до 08.10 18:00','цены листингов на 30.09; предложение продавца до 08.10 18:00'],g9,g10],
   src:[['Страница лота','площадка складских остатков','29.09 14:10','прочитано'],['Манифест XLSX','со страницы лота','29.09 15:00','прочитано · заявлен продавцом'],['Листинги amazon.de','12 позиций по EAN','30.09','прочитано'],['Ответ продавца','через площадку','30.09 13:45','прочитано'],['Сообщение покупателя В','собственная переписка','30.09 17:05','прочитано · необязывающее'],['Реестр продавца, номер НДС','—','—','не прочитано: не смотрели']],
   change:[['продавец назовёт цену доставки','пересчёт маршрутов с известной доставкой'],['покупатель письменно подтвердит цену, количество и срок','гейт «Спрос» можно проверить заново'],['фото остальных паллет покажут расхождение с манифестом','пересчёт состава или отказ'],['пройдёт 08.10 18:00','вывод теряет силу вместе с предложением']],
   plan:[['Повторить запрос продавцу: способ и цена доставки, фото паллет 1, 3, 5, 6','G01 · G02'],['Проверить продавца: реестр и номер НДС (VIES)','G02'],['Решить, отправлять ли черновик покупателю А','G03'],['Записать решение по версии — исследование его не записывает','—']],
   concl:{ev:'Цена партии, единица продажи и срок — страница лота 29.09. Манифест и состояние — заявление продавца.',money:'До неизвестных расходов результат по маршрутам — сценарий; деньги на пике от '+LP.eur(Math.min(...R.map(x=>x.cash_need.peak.cents)))+'.',cond:'Рассматривать покупку можно только после цены доставки, проверки продавца и письменного подтверждения покупателя.'}}}
 if(sk==='item:P01'){return {action:'NEEDS_EVIDENCE',partial:false,noStop:true,
   what:REG.P01.title_ru+' · amazon.de · EUR · '+PR.question,
   why:[[1,PR.contradiction.what+' — '+PR.contradiction.status+'; '+PR.contradiction.matters_because+'.'],[4,'Доставка 6,90 € за посылку; сколько посылок на 60 шт. — неизвестно. Подготовка, хранение, возвраты не измерены.'],[2,'S2: упаковка не указана, EAN на странице нет — единица цены 8,10 € не подтверждена. S4: каталог за регистрацией не прочитан.']],
   miss:PR.unknown.concat(['S4: цена — каталог за регистрацией']),next:[PR.next_step],
   until:'не задано',untilWhy:'срока в данных демо нет · цены рынка на 30.09 18:05, обновление 30.09 23:40 не удалось',
   limit:'Предел 9,60 € без НДС за шт. при 30 % (рассчитано) — значение по умолчанию, порогом не утверждено. S1 7,60 € ниже на 2,00 € — не прибыль.',
   money:[['Товар при мин. заказе 60 шт.',EC.goods_at_moq.display,'calc','без НДС'],['Известная часть выплаты',EC.cash_known.display,'ass','с НДС 19 % DE; полная — неизвестно'],['Результат по учтённой стоимости',EC.lot_result_counted.display,'ass','до доставки; после — не больше '+EC.lot_result_after_delivery_upper.display],['Экономический итог','неизвестно','unk','подготовка, хранение, возвраты не измерены; остаток при слабом спросе — не ноль']],
   adverse:'Если образец покажет 450 мл, предложение S1 отпадает; S2 без подтверждённой единицы его не заменяет.',
   gates:[['нужны данные','EAN у S1 совпал; объём 450 / 400 мл — противоречие не разрешено'],['нужны данные','S1: 7,60 €, мин. заказ 60 шт.; S2: упаковка не указана; S4 не прочитан'],['нужны данные','прогноза продаж в штуках нет; куплено 300+ за прошлый месяц — нижняя граница'],['нужны данные','число посылок на 60 шт. неизвестно; подготовка, хранение, возвраты не измерены'],['не проверено','право продажи и требования к товару здесь не проверялись'],g6,['посчитан частично','если 450 мл — предложение отпадает'],['нужны данные','обновление цен 30.09 23:40 не удалось; данные на 30.09 18:05'],g9,g10],
   src:PR.sources.map(s=>[s.id,s.what,d5(s.observed_at),s.verification==='confirmed'?(s.result==='comparison'?'прочитано · только сравнение':'прочитано'):s.verification==='price_only'?'прочитано · только цена':'Не прочитано: каталог за регистрацией · '+d5(s.observed_at)]),
   change:D.P01_explanation_v3.change_conditions.map(c=>[c.if||'Amazon появится на листинге',c.then]),
   plan:[[PR.next_step,'G01 · G04'],['Решить, нужен ли доступ к каталогу S4 (регистрация)','G02'],['Записать решение по версии в карточке — исследование его не записывает','—']],
   concl:{ev:PR.conclusion,money:'Известная часть выплаты '+EC.cash_known.display+'; результат по учтённой стоимости '+EC.lot_result_counted.display+' — до доставки.',cond:'Закупку можно рассматривать после образца (400 мл) и числа посылок.'}}}
 if(sk==='hyp:P06'){const e=E4.P06;return {action:'NEEDS_EVIDENCE',partial:true,noStop:true,
   what:'Гипотеза: '+REG.P06.title_ru+' · закупка 5,40 € за набор — условно · цена продажи — сценарий',
   why:[[3,'Спрос на ваш набор неизвестен — гипотеза; аналоги найдены в архиве рынка '+d5(F06.provider_answered_at)+'.'],[4,'FBA — по аналогу 10 шт., допущение. Доставка от поставщика «по запросу». Подготовка, хранение, возвраты, реклама запуска — неизвестно.'],[1,'Состав — '+(a?'ваш ответ '+d5(a.at)+'; без документа поставщика остаётся допущением.':'не проверен.')]],
   miss:['Доставка от поставщика','Собственный GTIN и листинг','Подготовка, хранение, возвраты, реклама запуска','Спрос на ваш набор','Состав набора — документ поставщика'],
   next:['Запросить у поставщика доставку и состав набора письменно','Оценить FBA по своему набору, а не по аналогу'],
   until:'не задано',untilWhy:'срока в данных демо нет · архив рынка '+d5(F06.provider_answered_at),
   limit:`Предел ${e.ceiling_30.display} за набор при 30 % (рассчитано) — от сценарной цены продажи. Закупка ${e.offer.display} ниже на ${e.headroom.display} — условно, не прибыль.`,
   money:[['Закупка',e.offer.display+' за набор','ass','условие «за набор»'],['До предела',e.headroom.display+' на набор','calc','цена продажи — сценарий'],['Деньги на горизонте','неизвестно','unk','мин. заказ и доставка не названы'],['Экономический итог','неизвестно','unk','спрос — гипотеза; остаток не ноль']],
   adverse:'Если спрос на набор не подтвердится, закупленный объём остаётся на складе; размер неизвестен, не ноль.',
   gates:[['нужны данные','состав — '+(a?'ваш ответ, документа нет':'не проверен')],['нужны данные','цена 5,40 € за набор; доставка «по запросу»'],['нужны данные','спрос — гипотеза'],['нужны данные','FBA по аналогу; GTIN и листинг — неизвестно'],['не проверено','собственный листинг и требования к товару не проверялись'],g6,['не посчитан','объём закупки не задан'],['в силе',`архив рынка ${d5(F06.provider_answered_at)}: ${F06.age_days_since_answer} дн., порог 45 дней`],g9,g10],
   src:[['Архив рынка','поиск аналогов',fdt(F06.provider_answered_at),'прочитано'],['Поставщик','цена 5,40 € за набор','—','прочитано · условие «за набор»'],['Ваш ответ','состав набора',a?d5(a.at):'—',a?'записано':'ждём']],
   change:[['поставщик подтвердит состав письменно','гейт «Товар и состав» можно проверить заново'],['поставщик назовёт доставку','пересчёт затрат'],['будет оценка FBA по своему набору','допущение станет расчётом']],
   plan:[['Запросить у поставщика состав и доставку письменно','G01 · G02'],['Оценить FBA по своему набору','G04'],['Записать решение по версии в карточке — исследование его не записывает','—']],
   concl:{ev:'Аналоги — архив рынка; закупка — 5,40 € за набор (условие «за набор»).',money:'До предела '+e.headroom.display+' на набор — условно; деньги на горизонте неизвестны.',cond:'Запуск можно рассматривать после документа о составе, доставки и оценки FBA по своему набору.'}}}
 return null}

/* ══ графики ══ */
const pc=(v,mx)=>Math.max(0,Math.min(100,v/mx*100)).toFixed(2)+'%';
function figW(q,meta,body,lg){return `<figure class="f9"><figcaption><p class="f9-q">${q}</p><p class="t2 f9-m">${meta}</p></figcaption>${body}${lg?`<p class="f9-lg">${lg}</p>`:''}</figure>`}
function figRoutes(){const R=RS.routes,mx=Math.max(...R.map(x=>x.result_before_unknown.high.cents));
 return figW('Варианты сбыта: результат по проданному',`Единицы: € без НДС за партию · Основание: выручка — ваше допущение, экономика v2 01.10 08:40; закупка ${B.price.lot_net.display} · Неизвестно: статьи расходов, отмечены штриховкой`,
 `<div class="f9-rows" role="list">${R.map(x=>{const lo=x.result_before_unknown.low.cents,hi=x.result_before_unknown.high.cents;return `<div class="f9-r" role="listitem"><span class="f9-n">${esc(x.name)}</span><span class="f9-tr" aria-hidden="true"><i class="f9-u" style="left:0;width:${pc(lo,mx)}"></i><i class="f9-rg" style="left:${pc(lo,mx)};width:${pc(hi-lo,mx)}"></i></span><span class="f9-v"><span class="n">${x.result_before_unknown.low.display} – ${x.result_before_unknown.high.display}</span> <span class="t2">· не посчитано ${unkN(x)}</span></span></div>`}).join('')}</div><div class="f9-r f9-axr" aria-hidden="true"><span></span><span class="f9-ax"><span>0 €</span><span>${LP.eur(mx)}</span></span><span></span></div>`,
 `<span><i class="f9-k f9-k-rg"></i>диапазон до неизвестных расходов · сценарий</span><span><i class="f9-k f9-k-u"></i>неизвестные расходы уменьшают результат на неизвестную величину — не ноль</span>`)}
function figCostLot(){const R=RS.routes,mx=Math.max(...R.map(x=>x.purchase.cents+x.known_costs_total.cents));
 return figW('Структура затрат по маршрутам',`Единицы: € без НДС · Основание: закупка — страница лота, членство — условия площадки · Неизвестно: заштриховано, ширина условная — не величина`,
 `<div class="f9-rows" role="list">${R.map(x=>`<div class="f9-r" role="listitem"><span class="f9-n">${esc(x.name)}</span><span class="f9-st" aria-hidden="true"><i class="f9-sf" style="width:${pc(x.purchase.cents,mx*1.35)}"></i><i class="f9-sc" style="width:${pc(x.known_costs_total.cents,mx*1.35)}"></i>${x.unknown_costs.filter(c=>c.kind==='UNKNOWN').map(()=>'<i class="f9-sx"></i>').join('')}</span><span class="f9-v"><span class="n">${x.purchase.display}</span> + <span class="n">${x.known_costs_total.display}</span> <span class="t2">+ неизвестно: ${unkN(x)}</span></span></div>`).join('')}</div>`,
 `<span><i class="f9-k f9-k-f"></i>закупка · подтверждено</span><span><i class="f9-k f9-k-c"></i>членство площадки · подтверждено</span><span><i class="f9-k f9-k-x"></i>неизвестно · одна клетка — одна статья</span>`)}
function figCash(){const R=RS.routes,W=36,wk=t=>{const w=[];const RX=/(\d+(?:,\d+)?)\s*(?:[–-]|до)\s*(\d+(?:,\d+)?)\s*(нед|мес)/;const m=t.match(new RegExp(RX.source,'g'))||[];m.forEach(s=>{const x=s.match(RX);const k=x[3]==='мес'?4.35:1;w.push([parseFloat(x[1].replace(',','.'))*k,parseFloat(x[2].replace(',','.'))*k,s])});return w};
 return figW('Движение денег по горизонту',`Единицы: недели от оплаты продавцу; месяцы переведены ×4,35 для шкалы · Основание: пик — предоплата + членство (рассчитано), сроки возврата — гипотеза · Неизвестно: доставка и НДС по сценарию Б в пик не входят`,
 `<div class="f9-rows" role="list">${R.map(x=>`<div class="f9-r" role="listitem"><span class="f9-n">${esc(x.name)}</span><span class="f9-tr f9-cw" aria-hidden="true"><i class="f9-out"></i>${wk(x.timing).map(w=>`<i class="f9-win" style="left:${pc(w[0],W)};width:${pc(w[1]-w[0],W)}"></i>`).join('')}</span><span class="f9-v"><span class="n">−${x.cash_need.peak.display}</span> <span class="t2">· возврат ${esc(x.timing.replace(/\s*\(ГИПОТЕЗА\)/,''))}</span></span></div>`).join('')}</div><div class="f9-r f9-axr" aria-hidden="true"><span></span><span class="f9-ax"><span>0</span><span>${W} нед.</span></span><span></span></div>`,
 `<span><i class="f9-k f9-k-out"></i>оплата продавцу, деньги на пике</span><span><i class="f9-k f9-k-win"></i>окно возврата денег · гипотеза</span>`)}
function figOffers(){const mx=1800,rows=[['S1',S1.price_net.cents,'f','прайс, подтверждено'],['S2',S2.price_net.cents,'y','только цена: единица не подтверждена'],['S3',S3.price_net.cents,'r','розница — только сравнение'],['S4',null,'u','Не прочитано: каталог за регистрацией']];
 return figW('Предложения против предела','Единицы: € без НДС за 1 шт. · Основание: источники S1–S4, 22–24.09; предел — правило карточки при 30 % · Неизвестно: цена S4',
 `<div class="f9-rows f9-lim" role="list" style="--lim:${pc(960,mx)}">${rows.map(r=>`<div class="f9-r" role="listitem"><span class="f9-n"><span class="code">${r[0]}</span></span><span class="f9-tr" aria-hidden="true">${r[1]==null?'<i class="f9-u" style="left:0;width:100%"></i>':`<i class="f9-b f9-b-${r[2]}" style="width:${pc(r[1],mx)}"></i>`}<i class="f9-lm"></i></span><span class="f9-v">${r[1]==null?'<span class="ms u">неизвестно</span>':`<span class="n">${LP.eur(r[1])}</span>`} <span class="t2">· ${r[3]}</span></span></div>`).join('')}</div><div class="f9-r f9-axr" aria-hidden="true"><span></span><span class="f9-ax"><span>0 €</span><span>18,00 €</span></span><span></span></div>`,
 `<span><i class="f9-k f9-k-lm"></i>предел 9,60 € при 30 % · рассчитано</span>`)}
function figCostItem(){const mx=EC.cash_known.cents*1.4;
 return figW('Структура выплаты при мин. заказе 60 шт.','Единицы: € · Основание: S1 и правило карточки; НДС 19 % DE — сценарий · Неизвестно: заштриховано, ширина условная',
 `<div class="f9-rows" role="list"><div class="f9-r" role="listitem"><span class="f9-n">60 шт.</span><span class="f9-st" aria-hidden="true"><i class="f9-sf" style="width:${pc(EC.goods_at_moq.cents,mx)}"></i><i class="f9-ss" style="width:${pc(EC.vat_purchase_scenario.cents,mx)}"></i><i class="f9-sc" style="width:${pc(EC.one_parcel.cents*3,mx)}"></i><i class="f9-sx"></i><i class="f9-sx"></i></span><span class="f9-v"><span class="n">${EC.goods_at_moq.display}</span> + <span class="n">${EC.vat_purchase_scenario.display}</span> + <span class="n">${EC.one_parcel.display}</span> × ? <span class="t2">= известная часть ${EC.cash_known.display}</span></span></div></div>`,
 `<span><i class="f9-k f9-k-f"></i>товар · рассчитано</span><span><i class="f9-k f9-k-s"></i>НДС закупки · допущение</span><span><i class="f9-k f9-k-c"></i>посылка 6,90 € · подтверждено</span><span><i class="f9-k f9-k-x"></i>число посылок; подготовка, хранение, возвраты — неизвестно</span>`)}

/* ══ разделы результата ══ */
function secOffers(r){if(r.sk==='lot:BT-01')return `<ul class="r9-ls">${RS.routes.map(x=>`<li><p><b>${esc(x.name)}</b> <span class="t2">· ${esc(x.form)}</span></p><p class="t2">покупатели: ${x.buyers.map(b=>esc(BY[b].name.replace(/ \(демо\)/,''))+' — '+esc(BY[b].confirmation.label)).join('; ')}</p></li>`).join('')}</ul>${figRoutes()}`;
 if(r.sk==='item:P01')return `<ul class="r9-ls">${PR.sources.map(s=>`<li><p><span class="code">${s.id}</span> <b>${esc(s.what)}</b></p><p class="t2">${s.price_net.cents==null?'<span class="ms u">цена неизвестна</span> · Не прочитано: каталог за регистрацией · '+d5(s.observed_at):s.price_net.display+' без НДС · мин. заказ '+s.moq+' · упаковка '+esc(s.pack)+' · доставка '+esc(s.delivery)+' · '+d5(s.observed_at)}</p></li>`).join('')}</ul>${figOffers()}`;
 return `<ul class="r9-ls"><li><p><b>Поставщик</b> <span class="t2">· 5,40 € за набор · условие «за набор» · доставка «по запросу»</span></p></li><li><p><b>Канал</b> <span class="t2">· amazon.de · FBA — из карточки</span></p></li><li><p><b>Аналоги</b> <span class="t2">· архив рынка (поиск аналогов) · ${fdt(F06.provider_answered_at)}</span></p></li></ul>`}
function secEcon(r){const x=res(r);
 if(r.sk==='lot:BT-01')return `<p class="t2">Три представления — не складываются. Непроданный остаток — не ноль.</p><div class="tbl-wrap" tabindex="0" role="region" aria-label="Экономика маршрутов"><table class="tbl r9-tbl"><thead><tr><th scope="col">Маршрут</th><th scope="col">Прибыль по проданному</th><th scope="col">Деньги на горизонте</th><th scope="col">Экономический итог</th></tr></thead><tbody>${RS.routes.map(y=>`<tr><th scope="row">${esc(y.name)}</th><td><span class="n">${y.result_before_unknown.low.display} – ${y.result_before_unknown.high.display}</span> ${KN.ass}<br><span class="kx">до неизвестных расходов · не посчитано ${unkN(y)}</span></td><td><span class="n">${y.cash_need.peak.display}</span> ${KN.calc}<br><span class="kx">${esc(y.cash_need.locked_for.replace(/\s*\(ГИПОТЕЗА\)/,' · гипотеза'))}</span></td><td><span class="ms u">неизвестно</span><br><span class="kx">остаток ${y.remainder.units?'<span class="n">'+y.remainder.units+' ед.</span>':'0 ед., если покупатель берёт всё'} · ${esc(y.remainder.note)}</span></td></tr>`).join('')}</tbody></table></div>${figCostLot()}${figCash()}`;
 return `<dl class="r9-dl">${x.money.map(m=>`<div><dt>${m[0]}</dt><dd>${m[1]==='неизвестно'?'<span class="ms u">неизвестно</span>':'<b class="n">'+m[1]+'</b>'} ${KN[m[2]]}<span class="kx">${esc(m[3])}</span></dd></div>`).join('')}</dl>${r.sk==='item:P01'?figCostItem():''}`}
function secScen(r){if(r.sk==='lot:BT-01'){const v=B.price.vat;return `<ul class="r9-ls"><li><p><b>НДС · сценарий А</b> <span class="t2">· ${esc(v.scenario_A.label)} · ${v.scenario_A.cash_vat.display} · ${esc(v.scenario_A.condition)}</span></p></li><li><p><b>НДС · сценарий Б</b> <span class="t2">· ${esc(v.scenario_B.label)} · <span class="ms u">неизвестно</span> · ${esc(v.scenario_B.cash_vat.why)}</span></p></li>${RS.routes.map(y=>`<li><p><b>${esc(y.name)}</b> <span class="t2">· ${esc(y.revenue.basis)}</span></p></li>`).join('')}</ul>`}
 if(r.sk==='item:P01'){const t=D.charts.E10_delivery_scenario.teapot;return `<div class="tbl-wrap" tabindex="0" role="region" aria-label="Если посылок X"><table class="tbl" data-density="dense"><caption class="cap-l">Если посылок X · сценарий · X неизвестно</caption><thead><tr><th scope="col" class="num">Посылок</th><th scope="col" class="num">Доставка</th><th scope="col" class="num">Результат после доставки</th></tr></thead><tbody>${t.rows.map(y=>`<tr><td class="num">${y.parcels}</td><td class="num">${y.delivery.display}</td><td class="num">${y.result_after_delivery.display}</td></tr>`).join('')}</tbody></table></div>`}
 return `<p class="t2">Цена продажи — один сценарий: нижняя цена двух сопоставимых наборов. Других сценариев в данных нет.</p>`}
function secRisk(r){const x=res(r);const rk=r.sk==='lot:BT-01'?[...new Set(RS.routes.flatMap(y=>y.risks))]:r.sk==='item:P01'?['5 продавцов на листинге','Объём в прайсе 450 мл против 400 мл на листинге','Совпадение кода ≠ проверка товара']:['Спрос — гипотеза','FBA по аналогу, не по своему набору'];
 return `<div class="r9-2c"><div><h3 class="h3">Риски</h3><ul class="r9-ls">${rk.map(t=>`<li><p>${esc(t)}</p></li>`).join('')}</ul></div><div><h3 class="h3">Что изменит вывод</h3><ul class="r9-ls">${x.change.map(c=>`<li><p>Если ${esc(c[0])} <span class="t2">→ ${esc(c[1])}</span></p></li>`).join('')}</ul></div></div>`}
function secSrc(r){const x=res(r);return `<ul class="r9-ls r9-src">${x.src.map(s=>`<li class="${/^Не прочитано|^не прочитано/.test(s[3])?'r9-na':''}"><p><b>${esc(s[0])}</b> <span class="t2">· ${esc(s[1])}</span></p><p class="r9-ss">${/^Не прочитано|^не прочитано/.test(s[3])?`<span class="ms na">${IC.na}</span>`:''}<span>${esc(s[3])}</span><span class="t2">${s[2]!=='—'?' · '+esc(s[2]):''}</span></p></li>`).join('')}</ul>`}
function histOf(r){const own=ST.hist.filter(h=>h.run===r.id).map(h=>[h.at,h.t]);const base=r.sk==='lot:BT-01'?RS.history.map(h=>[h.at,h.what]):r.sk==='item:P01'?[[PR.asked_at,'Задача: '+PR.question],[PR.answered_at,'Итог RB-D07: '+PR.conclusion]]:[];return base.concat(own)}
function secHist(r){return `<ol class="r9-hl">${histOf(r).map(h=>`<li><span class="tm n">${h[0]===NOW?'01.10 10:00':fdt(h[0])}</span><span>${esc(h[1])}</span></li>`).join('')}</ol>`}

/* ══ первый экран результата ══ */
function resultHtml(r){const x=res(r),sj=SJ(r);
 return `<section class="r9-res" aria-labelledby="r9r-h">
<div class="r9-r0"><p class="eyebrow">Что исследовали</p><p>${esc(x.what)}</p></div>
<div class="r9-r1"><p class="eyebrow" id="r9r-h" tabindex="-1">К чему пришли</p><div class="r9-act"><span class="r9-av">${ACTL[x.action]}</span>${x.partial?'<span class="tag">частично</span>':''}</div>${r.sk==='item:P01'?`<p>${esc(PR.conclusion)}</p>`:''}${x.noStop?`<p class="r9-ns">${NOSTOP}</p>`:''}</div>
<div class="r9-r2"><p class="eyebrow">Почему</p><ol class="r9-why">${x.why.map(w=>`<li><span class="code r9-g">${gc(w[0])}</span><span><b>${GN[w[0]-1]}.</b> ${esc(w[1])}</span></li>`).join('')}</ol></div>
<div class="r9-r3"><div><p class="eyebrow">Чего не хватает</p><ul class="r9-miss">${x.miss.map(t=>`<li><span class="ms u"></span><span>${esc(t)}</span></li>`).join('')}</ul></div><div><p class="eyebrow">Что дальше</p><ul class="r9-nx">${x.next.map(t=>`<li>${esc(t)}</li>`).join('')}</ul><p class="eyebrow r9-ue">Действует до</p><p><b class="n">${x.until}</b> <span class="t2">· ${esc(x.untilWhy)}</span></p></div></div>
${cnt(tally(r,1))}
<div class="r9-docs"><a class="btn btn-s" href="#/research/${r.id}/report">Полный отчёт · 9 листов A4</a><a class="btn btn-s" href="#/research/${r.id}/memo">Меморандум · 2 листа</a></div>
<p class="t2 r9-auth">Вывод исследования — рекомендация. Решение по версии записываете вы ${sj.kind==='lot'?'на странице партии':'в карточке'}; разрешение тратить капитал — вне системы.</p></section>
<div class="u2 r9-more">${[['off',r.sk==='lot:BT-01'?'Предложения и каналы':'Предложения и каналы',r.sk==='lot:BT-01'?'4 маршрута · покупатели — кандидаты':r.sk==='item:P01'?'S1–S4 · 1 источник не прочитан':'поставщик и канал из карточки',secOffers],['eco','Экономика','прибыль по проданному · деньги на горизонте · итог',secEcon],['scn','Сценарии',r.sk==='lot:BT-01'?'НДС А / Б · цены сбыта':r.sk==='item:P01'?'если посылок 1…6':'один сценарий цены',secScen],['rsk','Риски и «Что изменит вывод»',x.change.length+' условия',secRisk],['src','Источники',x.src.length+' · '+x.src.filter(s=>/^Не прочитано|^не прочитано/.test(s[3])).length+' не прочитано',secSrc],['his','История',histOf(r).length+' записей',secHist],['prg','Ход исследования','завершено '+doneN(r)+' '+etap(doneN(r))+' из '+DEMO.stages[r.sk].length,progList]].map(([k,t,s,fn])=>`<section>${LP.acc('r9'+r.id+k,`<span class="sq">${t}</span><span class="tot">${esc(s)}</span>`,fn(r))}</section>`).join('')}</div>`}

/* ══ ход ══ */
const etap=n=>n%10===1&&n%100!==11?'этап':[2,3,4].includes(n%10)&&![12,13,14].includes(n%100)?'этапа':'этапов';
const doneN=r=>DEMO.stages[r.sk].filter((s,i)=>i<r.n&&!s.nd).length;
function stState(r,i){const s=DEMO.stages[r.sk][i];if(i<r.n)return s.fail?'fail':s.nd?'nd':'done';if(i===r.n)return r.st==='input'?'input':r.st==='wait'?'wait':r.st==='run'?'now':'todo';return 'todo'}
const STW={done:'выполнено',fail:'источник недоступен',nd:'не выполнено',input:'требуется уточнение',wait:'ждём внешний ответ',now:'идёт',todo:'впереди'};
function progList(r){return `<ol class="r9-st">${DEMO.stages[r.sk].map((s,i)=>{const k=stState(r,i);return `<li class="r9-si" data-s="${k}"${r._new===i?' data-in="1"':''}><span class="r9-sm" aria-hidden="true">${k==='wait'?IC.clkd:k==='fail'?IC.na:''}</span><div><p class="r9-sn">${esc(s.t)} <span class="r9-sw">· ${STW[k]}</span></p>${k==='fail'?`<p class="r9-sf">${esc(s.fail)}</p>`:k==='nd'?`<p class="t2">${esc(s.nd)}</p>`:s.n&&k!=='todo'?`<p class="t2">${esc(s.n)}</p>`:''}${k==='input'?qForm(r):''}</div></li>`}).join('')}</ol>`}
function qForm(r){const Q=DEMO.q[r.sk];const asked=r.asked||r.at;return `<form class="r9-q" id="r9-q" data-run="${r.id}" aria-labelledby="r9q-h" novalidate><h3 class="h3" id="r9q-h" tabindex="-1">${esc(Q.q)}</h3><p class="t2"><b class="ink">Почему нужен:</b> ${esc(Q.why)}</p><p class="t2">ответить до <b class="n ink">${plus14(asked)}</b> · 14 дней с вопроса ${fdt(asked)}${Q.warn?' · '+esc(Q.warn):''}</p>
<fieldset class="r9-opts" aria-describedby="r9q-e"><legend class="sr-only">Ответ</legend><label class="r9-opt"><input type="radio" name="qa" value="a"><span>${esc(Q.opt)}</span></label><label class="r9-opt"><input type="radio" name="qa" value="own"><span>${esc(Q.own)}</span></label><div class="r9-own" hidden><label class="sr-only" for="r9q-t">Ваш ответ</label><textarea id="r9q-t" name="text" rows="2" placeholder="Ваш ответ"></textarea></div><label class="r9-opt"><input type="radio" name="qa" value="doc"><span>${esc(Q.doc)}</span></label><div class="r9-doc" hidden><label class="t2" for="r9q-f">Документ · в демо файл не загружается и не читается</label><input id="r9q-f" type="file" name="file"></div></fieldset>
<p class="r9-err" id="r9q-e" role="alert" hidden></p><div class="r9-qa"><button class="btn btn-p" type="submit">Ответить</button><span class="t2">ответ записывается как ваш; исследование продолжится</span></div></form>`}
function progHtml(r){const t=tally(r);return `<section class="sec r9-prog" aria-labelledby="r9p-h"><div class="sec-h"><h2 class="h2" id="r9p-h" tabindex="-1">Ход</h2><p class="t2">завершено <span class="n">${doneN(r)}</span> ${etap(doneN(r))} из <span class="n">${DEMO.stages[r.sk].length}</span>${r.st==='wait'?' · ждём внешний ответ: задача у команды LotPrism, срок ответа в данных не задан':''}</p></div>${cnt(t)}${progList(r)}<p class="t2 r9-out">Дальше — вне исследования: решение по версии записываете вы; разрешение на капитал — вне системы.</p></section>`}
function bodyHtml(r){return ['done','part'].includes(r.st)?resultHtml(r):progHtml(r)}

/* ══ страница исследования ══ */
function backOf(r){const sj=SJ(r);const f=r.from&&r.from.split('?')[0]===sj.home?r.from:sj.home;return {href:f,label:sj.back}}
function runPage(id){const r=runOf(id);if(!r)return `<main class="main r9"><h1 class="h1">Исследование не найдено</h1><p class="t2">Возможно, демо Research сброшено.</p><a href="#/research">Исследования</a></main>`;const sj=SJ(r),b=backOf(r);
 return `<main class="main r9" data-screen-label="Исследование ${r.id}"><nav class="r9-bc" aria-label="Возврат"><a href="${b.href}" id="r9-back">${esc(b.label)}</a><a href="#/research" class="t2">Исследования</a></nav>
<header class="r9-h"><p class="eyebrow">${sj.task}${r.code?' · <span class="code">'+r.code+'</span>':''}</p><h1 class="h1">${esc(sj.title)}</h1><p class="r9-meta">${chip(r.st)}${r.direct?'<span class="tag">демо: показано сразу в итоговом состоянии</span>':''}${prevOf(r)?`<span class="t2">версия ${ST.runs.filter(x=>x.sk===r.sk).indexOf(r)+1} · предыдущая: <a href="#/research/${prevOf(r).id}">${prevOf(r).code||prevOf(r).id}</a></span>`:''}<span class="t2">${r.seed?'начато '+fdt(r.at)+(r.fin?' · готово '+fdt(r.fin):''):'запущено 01.10 10:00 · срез демо'} · демонстрация: этапы и ответы — из сохранённых данных, модели не вызываются</span></p></header>
<div id="r9-body">${bodyHtml(r)}</div></main>`}

/* ══ первый экран раздела ══ */
const ENTR=[['item','Проверить товар или предложение','товар перепродажи или гипотеза нового листинга',1],['lot','Проверить оптовую партию','файл, ссылка или вручную',1],['find','Найти варианты под условия','капитал, рынок, каналы',0],['upd','Обновить исследование','новая версия по сохранённой задаче',0],['memo','Подготовить меморандум','2 листа A4 из готового результата',0]];
function entries(lim){return `<ul class="r9-en">${ENTR.filter(e=>!lim||e[3]).map(e=>e[3]?`<li><a class="r9-ea" href="#/research/new?subj=${e[0]}&amp;from=${encodeURIComponent('#/research')}"><span class="r9-et">${e[1]}</span><span class="t2">${e[2]}</span></a></li>`:`<li><button class="r9-ea" type="button" aria-disabled="true" data-act="na" data-what="${e[1]}" data-msg="в прототипе не собрано"><span class="r9-et">${e[1]}</span><span class="t2">${e[2]}</span><span class="req-tag">в прототипе не собрано</span></button></li>`).join('')}</ul>`}
function rowHtml(r,mode){const sj=SJ(r),x=['done','part'].includes(r.st)?res(r):null,Q=DEMO.q[r.sk];
 const mid=mode==='input'?`<p class="r9-rq">${esc(Q.q)}</p><p class="t2">Почему нужен: ${esc(Q.why)}</p><p class="t2">ответить до <span class="n">${plus14(r.asked||r.at)}</span> · срок ответа 14 дней</p>`:x?`<p class="r9-rq">${ACTL[x.action]}${x.partial?' <span class="tag">частично</span>':''}</p>${r.sk==='item:P01'?`<p class="t2">${esc(PR.conclusion)}</p>`:''}<p class="t2">${r.fin?'готово '+fdt(r.fin):''} · ${untilT(x)}</p>`:`<p class="r9-rq">${esc((DEMO.stages[r.sk][r.n]||{}).t||'')} <span class="t2">· ${STW[stState(r,r.n)]||''}</span></p><p class="t2">завершено <span class="n">${doneN(r)}</span> ${etap(doneN(r))} из <span class="n">${DEMO.stages[r.sk].length}</span></p>`;
 return `<li class="r9-row"><div class="r9-rm">${thumbOf(r.sk)}</div><div class="r9-rc"><p class="r9-rt"><a class="r9-ra" id="r9-${r.id}" href="#/research/${r.id}">${esc(sj.title)}</a></p><p class="t2">${sj.task}${r.code?' · <span class="code">'+r.code+'</span>':''}</p>${mid}</div><div class="r9-rx">${chip(r.st)}<a class="btn btn-s sm" href="#/research/${r.id}" tabindex="-1" aria-hidden="true">${mode==='input'?'Ответить':x?'Открыть результат':'Открыть идущее'}</a></div></li>`}
function home(q){const f=q.get('f')||'';const A=runs();
 if(!A.length)return `<main class="main r9" data-screen-label="Исследования · пусто"><div class="pg-h"><h1 class="h1">Исследования</h1><p class="t2">Research · Demo-Handel GmbH · срез 01.10.2026 10:00</p></div><section class="r9-empty" aria-labelledby="r9e-h"><h2 class="h2" id="r9e-h">Исследований пока нет</h2><p class="t2">Исследование отвечает на вопрос о товаре, гипотезе или партии: что известно, чего не хватает, какое действие допустимо. Начните с одного из входов или из карточки товара.</p>${entries(1)}</section></main>`;
 const inp=A.filter(r=>r.st==='input'),run=A.filter(r=>r.st==='run'),wt=A.filter(r=>r.st==='wait'),dn=A.filter(r=>['done','part'].includes(r.st));
 const FL=[['','Все',A.length],['input','Ждут ответа',inp.length],['run','Идут',run.length+wt.length],['done','Готово',dn.length]];
 const show=k=>!f||f===k;
 const hist=ST.hist.filter(h=>h.ver).reverse().concat([{at:'2026-09-25T10:20',t:'Чайник · вывод карточки, версия 2',was:'Рынок: стоит искать предложение',now:'Кандидат для проверки',why:'после поиска поставщиков RB-D07, 24.09'},{at:PR.answered_at,t:'Чайник · исследование RB-D07',was:'вывода не было',now:ACTL.NEEDS_EVIDENCE,why:'S1 — кандидат, а не готовая закупка'}]);
 return `<main class="main r9" data-screen-label="Исследования"><div class="pg-h"><h1 class="h1">Исследования</h1><p class="t2">Research · Demo-Handel GmbH · срез 01.10.2026 10:00 · демонстрация: запуск исследований в продукте не реализован</p></div>
<div class="r9-fl" role="group" aria-label="Показать">${FL.map(x=>`<a class="pl-chip" href="#/research${x[0]?'?f='+x[0]:''}" ${f===x[0]?' aria-current="true"':''}>${x[1]} <span class="n">${x[2]}</span></a>`).join('')}</div>
${!f?`<section class="sec" aria-labelledby="r9s-h"><div class="sec-h"><h2 class="h2" id="r9s-h">Начать</h2><p class="t2">собраны два входа; гипотезу нового листинга можно проверить и из карточки</p></div>${entries()}</section>`:''}
${show('input')?`<section class="sec" aria-labelledby="r9i-h"><div class="sec-h"><h2 class="h2" id="r9i-h">Ждут вашего ответа · <span class="n">${inp.length}</span></h2><p class="t2">исследование остановлено, пока вы не ответите</p></div>${inp.length?`<ul class="rows r9-rows">${inp.map(r=>rowHtml(r,'input')).join('')}</ul>`:'<p class="t2">Вопросов нет.</p>'}</section>`:''}
${show('run')?`<section class="sec" aria-labelledby="r9r2-h"><div class="sec-h"><h2 class="h2" id="r9r2-h">Идут · <span class="n">${run.length+wt.length}</span></h2><p class="t2">этапы словами · без процентов</p></div>${run.length?`<ul class="rows r9-rows">${run.map(r=>rowHtml(r)).join('')}</ul>`:''}${wt.length?`<h3 class="h3 r9-sub">Ждём внешний ответ · <span class="n">${wt.length}</span></h3><ul class="rows r9-rows">${wt.map(r=>rowHtml(r)).join('')}</ul>`:''}${!run.length&&!wt.length?'<p class="t2">Сейчас ничего не идёт.</p>':''}</section>`:''}
${show('done')?`<section class="sec" aria-labelledby="r9d-h"><div class="sec-h"><h2 class="h2" id="r9d-h">Готово · <span class="n">${dn.length}</span></h2><p class="t2">вывод, дата, срок действия · частичный результат помечен</p></div>${dn.length?`<ul class="rows r9-rows">${dn.map(r=>rowHtml(r)).join('')}</ul>`:'<p class="t2">Готовых результатов пока нет.</p>'}</section>`:''}
${!f?`<section class="sec" aria-labelledby="r9h-h"><div class="sec-h"><h2 class="h2" id="r9h-h">История обновлений</h2><p class="t2">версии выводов · было → стало</p></div><ul class="rows dcs r9-hv">${hist.map(h=>`<li class="dc"><span class="tm n">${h.at===NOW?'01.10':d5(h.at)}</span><span><b>${esc(h.t)}</b>: «${esc(h.was)}» → «${esc(h.now)}» <span class="t2">· ${esc(h.why)}</span></span></li>`).join('')}</ul></section>`:''}</main>`}

/* ══ подготовка задачи ══ */
const GOALS=['Решить, закупать ли','Найти лучший вариант закупки и сбыта','Понять, чего не хватает для решения'];
const CHS=RS.routes.map(x=>x.name);
const HOR=['1 мес.','3 мес.','6 мес.','не задан'];
const DEP=[['Быстрая','по сохранённым данным, без запросов'],['Полная','с запросами поставщикам и покупателям']];
function picker(kind,from){const lot=kind==='lot';
 return `<main class="main r9" data-screen-label="Подготовка · выбор предмета"><nav class="r9-bc" aria-label="Возврат"><a href="#/research">← Исследования</a></nav><div class="pg-h"><h1 class="h1">${lot?'Проверить оптовую партию':'Проверить товар или предложение'}</h1><p class="t2">Шаг 1 из 4 · предмет</p></div>
<ul class="r9-en">${lot?`<li><a class="r9-ea" href="#/research/new?subj=lot&amp;id=BT-01&amp;from=${encodeURIComponent('#/research/BT-01')}"><span class="r9-et">Партия BT-01 · Познань</span><span class="t2">страница лота сохранена ${fdt(B.found.page_observed_at)} · ${B.positions_count} позиций, ${B.units} ед.</span></a></li>`+['Загрузить манифест (файл)','Ссылка на лот','Ввести вручную'].map(t=>`<li><button class="r9-ea" type="button" aria-disabled="true" data-act="na" data-what="${t}" data-msg="в прототипе не собрано"><span class="r9-et">${t}</span><span class="req-tag">в прототипе не собрано</span></button></li>`).join('')
 :[['item','P01','перепродажа'],['hyp','P06','гипотеза нового листинга']].map(([k,i,t])=>`<li><a class="r9-ea" href="#/research/new?subj=${k}&amp;id=${i}&amp;from=${encodeURIComponent('#/p/'+i)}"><span class="r9-et">${esc(REG[i].title_ru)}</span><span class="t2">${t}</span></a></li>`).join('')+`<li><a class="r9-ea" href="#/products"><span class="r9-et">Другой товар</span><span class="t2">откройте карточку и нажмите «Исследовать товар» · в прототипе собрано для Чайника</span></a></li>`}</ul></main>`}
function prep(q){const kind=q.get('subj')||'item',id=q.get('id'),from=q.get('from')||'';if(!id)return picker(kind,from);
 const sk=(kind==='lot'?'lot:':kind==='hyp'||NL_.includes(id)?'hyp:':'item:')+id,sj=DEMO.subj[sk];
 if(!sj)return `<main class="main r9"><nav class="r9-bc"><a href="#/research">← Исследования</a></nav><h1 class="h1">Подготовка задачи</h1><p>Для этого предмета маршрут в прототипе не собран. Собраны: Чайник, Банки, партия BT-01.</p></main>`;
 const ex=runBy(sk),b={href:from&&from.split('?')[0]===sj.home?from:sj.home,label:sj.back};
 const head=`<nav class="r9-bc" aria-label="Возврат"><a href="${b.href}" id="r9-back">${esc(b.label)}</a><a href="#/research" class="t2">Исследования</a></nav><div class="pg-h"><p class="eyebrow">Подготовка задачи · ${sj.task}</p><h1 class="h1">${esc(sj.title)}</h1></div>`;
 if(ex&&active(ex))return `<main class="main r9" data-screen-label="Подготовка · уже идёт">${head}<section class="r9-ex" aria-labelledby="r9x-h"><h2 class="h2" id="r9x-h">По этому предмету уже идёт исследование</h2><p class="r9-meta">${chip(ex.st)}${ex.code?'<span class="code">'+ex.code+'</span>':''}<span class="t2">завершено ${doneN(ex)} ${etap(doneN(ex))} из ${DEMO.stages[sk].length}</span></p>${ex.st==='input'?`<p>Вопрос к вам: <b>${esc(DEMO.q[sk].q)}</b></p>`:''}<p class="t2">Новый запуск не создаётся: одна задача — одно исследование. Ответ или результат появятся в идущем.</p><div class="r9-docs"><a class="btn btn-p" id="r9-open" href="#/research/${ex.id}">Открыть идущее</a></div></section></main>`;
 const exN=ex?`<section class="r9-ex" aria-labelledby="r9y-h"><h2 class="h2" id="r9y-h">По этому предмету есть результат</h2><p class="r9-meta">${chip(ex.st)}${ex.code?'<span class="code">'+ex.code+'</span>':''}<span class="t2">${ex.fin?'готово '+fdt(ex.fin):''} · ${ACTL[res(ex).action]}</span></p><p class="t2">Новый запуск станет отдельной версией; прежний результат не меняется, в «Истории обновлений» появится «было → стало».</p><div class="r9-docs"><a class="btn btn-s" href="#/research/${ex.id}">Открыть результат</a></div></section>`:'';
 const P=ST.prep[sk]||(ST.prep[sk]={step:1,f:{},need:{},from});const st=P.step,f=P.f;
 const stH=(n,t,sum)=>`<div class="r9-ph"><span class="r9-pn n" aria-hidden="true">${n}</span><h2 class="h2" id="r9p${n}" tabindex="-1">${t}</h2>${n<st?`<button class="lnk" type="button" data-act="r9-step" data-n="${n}" data-sk="${sk}">изменить</button>`:''}</div>${n<st&&sum?`<p class="t2 r9-psum">${sum}</p>`:''}`;
 const s1=`<section class="r9-p" data-on="${st===1}" aria-labelledby="r9p1">${stH(1,'Предмет',esc(sj.src)+' · перенесено '+sj.ctx.length+' '+polya(sj.ctx.length))}${st===1?`<div class="r9-from"><p class="eyebrow">Откуда</p><p>${esc(sj.src)} <a href="${b.href}">изменить</a></p><p class="t2">Перенос по правилам: факт карточки → утверждение со своим источником и датой; условное и сценарий → допущение. Только для чтения.</p><ul class="r9-ctx">${sj.ctx.map(c=>`<li><span class="r9-cl">${esc(c[0])}</span><span class="r9-cv">${c[2]==='unk'?'<span class="ms u">неизвестно</span> ':''}${esc(c[1])}</span><span class="r9-ck">${KN[c[2]]}</span><span class="r9-cs t2">${esc(c[3])}</span></li>`).join('')}</ul><p class="r9-no"><span class="t2">Не переносится:</span> ${esc(sj.nottr)}. Цели, пределы и капитал — спросим ниже, из настроек не берутся.</p></div><div class="r9-pa"><button class="btn btn-p" type="button" data-act="r9-next" data-sk="${sk}">Дальше: условия</button></div>`:''}</section>`;
 const s2sum=st>2?[f.goal||'цель не задана',f.capNone?'капитал пока не определён':f.cap?'капитал '+f.cap+' €':'',(f.ch||[]).join(', ')||(f.chNeed?'каналы: нужен подбор':''),'горизонт '+(f.hor||'не задан'),'глубина: '+(f.dep||'—')].filter(Boolean).map(esc).join(' · '):'';
 const ctxF=[['Предмет',sj.title],['Рынок и валюта',sj.kind==='lot'?'PL / DE — из задачи, которой найдена партия':'amazon.de · EUR'],['Вопрос',sj.q]].concat(sj.asked);
 const s2=st<2?`<section class="r9-p" data-on="false" aria-labelledby="r9p2">${stH(2,'Условия')}</section>`:`<section class="r9-p" data-on="${st===2}" aria-labelledby="r9p2">${stH(2,'Условия',s2sum)}${st===2?`<form class="r9-form" id="r9-f2" data-sk="${sk}" novalidate>
${LP.acc('r9ctx'+sk,`<span class="sq">Из контекста · ${ctxF.length} ${polya(ctxF.length)} заполнено</span><span class="tot">свёрнуто · только чтение</span>`,`<dl class="r9-dl">${ctxF.map(c=>`<div><dt>${esc(c[0])}</dt><dd>${esc(c[1])}<span class="kx">${c[2]?esc(c[2]):sj.kind==='lot'&&c[0]!=='Предмет'?'из партии':'из карточки'}</span></dd></div>`).join('')}</dl>`)}
<fieldset class="r9-fs" aria-describedby="e-goal"><legend class="h3">Цель</legend>${GOALS.map(g=>`<label class="r9-opt"><input type="radio" name="goal" value="${g}"${f.goal===g?' checked':''}><span>${g}</span></label>`).join('')}<p class="r9-err" id="e-goal" hidden></p></fieldset>
<fieldset class="r9-fs" aria-describedby="e-cap"><legend class="h3">Капитал</legend><p class="t2">сколько готовы вложить в эту задачу · из настроек не берётся${sj.kind==='lot'?' · в задаче поиска партий был предел до 5 000 € — не переносится':''}</p><div class="r9-cap"><label class="sr-only" for="r9-cap">Сумма, €</label><input id="r9-cap" name="cap" inputmode="decimal" placeholder="сумма, €" value="${esc(f.cap||'')}"${f.capNone?' disabled':''}><label class="r9-opt r9-inl"><input type="checkbox" name="capNone"${f.capNone?' checked':''}><span>пока не определён</span></label></div><p class="r9-err" id="e-cap" hidden></p></fieldset>
${sj.kind==='lot'?`<fieldset class="r9-fs" aria-describedby="e-ch"><legend class="h3">Каналы сбыта</legend><div class="r9-chs">${CHS.map(c=>`<label class="r9-opt"><input type="checkbox" name="ch" value="${esc(c)}"${(f.ch||[]).includes(c)?' checked':''}><span>${esc(c)}</span></label>`).join('')}<label class="r9-opt"><input type="checkbox" name="chNeed"${f.chNeed?' checked':''}><span>нужен подбор</span></label></div><p class="r9-err" id="e-ch" hidden></p></fieldset>`:''}
<div class="r9-2c"><div class="r9-fs"><label class="h3" for="r9-hor">Горизонт</label><select id="r9-hor" name="hor" aria-describedby="e-hor"><option value="">выберите</option>${HOR.map(h=>`<option${f.hor===h?' selected':''}>${h}</option>`).join('')}</select><p class="r9-err" id="e-hor" hidden></p></div>
<fieldset class="r9-fs" aria-describedby="e-dep"><legend class="h3">Глубина</legend>${DEP.map(d=>`<label class="r9-opt"><input type="radio" name="dep" value="${d[0]}"${f.dep===d[0]?' checked':''}><span>${d[0]} <span class="t2">· ${d[1]}</span></span></label>`).join('')}<p class="r9-err" id="e-dep" hidden></p></fieldset></div>
<div class="r9-pa"><button class="btn btn-p" type="submit">Дальше: что понадобится</button></div></form>`:''}</section>`;
 const needs=sj.need;const nsum=st>3?(Object.keys(P.need).length?Object.keys(P.need).length+' документа отмечено':'пропущено · исследование запросит само'):'';
 const s3=st<3?`<section class="r9-p" data-on="false" aria-labelledby="r9p3">${stH(3,'Что понадобится для вердикта')}</section>`:`<section class="r9-p" data-on="${st===3}" aria-labelledby="r9p3">${stH(3,'Что понадобится для вердикта',nsum)}${st===3?`<p class="t2">Сгруппировано по гейтам. Если документа нет — исследование запросит или отметит неизвестным. Шаг можно пропустить.</p><ul class="r9-need">${[...new Set(needs.map(n=>n[0]))].map(g=>`<li><p class="r9-ng"><span class="code r9-g">${gc(g)}</span> ${GN[g-1]}</p><ul>${needs.filter(n=>n[0]===g).map(n=>{const k=sk+n[1];return `<li><label class="r9-opt"><input type="checkbox" data-need="${esc(n[1])}"${P.need[n[1]]?' checked':''}><span>${esc(n[1])} <span class="t2">· есть у меня, приложу</span></span></label></li>`}).join('')}</ul></li>`).join('')}</ul><p class="t2">в демо документы не загружаются: отметка только записывает, что документ есть</p><div class="r9-pa"><button class="btn btn-p" type="button" data-act="r9-next" data-sk="${sk}">Дальше: перед запуском</button><button class="btn btn-s" type="button" data-act="r9-skip" data-sk="${sk}">Пропустить</button></div>`:''}</section>`;
 const s4=st<4?`<section class="r9-p" data-on="false" aria-labelledby="r9p4">${stH(4,'Перед запуском')}</section>`:`<section class="r9-p" data-on="true" aria-labelledby="r9p4">${stH(4,'Перед запуском')}<dl class="r9-dl r9-pre"><div><dt>Задача</dt><dd>${esc(sj.task)}: ${esc(sj.q)}</dd></div><div><dt>Что проверим</dt><dd>гейты ${gc(1)}–${gc(10)}: ${GN.slice(0,8).join(', ').toLowerCase()}${f.goal?'':' · '+gc(6)+' не будет проверен: цель не задана'}</dd></div><div><dt>Покрытие</dt><dd>${esc(COVER)}</dd></div><div><dt>Лучший достижимый статус</dt><dd><b>${ACTL.NEEDS_EVIDENCE}</b><span class="kx">рынок вне покрытия предложения CTO — выше этого статуса исследование не поднимется</span></dd></div><div><dt>Стоимость исследования</dt><dd><span class="ms u">в демо не задано</span></dd></div><div><dt>Срок исследования</dt><dd><span class="ms u">в демо не задано</span></dd></div></dl>
<div class="r9-pa"><button class="btn btn-p" type="button" id="r9-go" data-act="r9-launch" data-sk="${sk}">Запустить (демо)</button><span class="t2">демонстрация: этапы и ответы — из сохранённых данных; модели не вызываются; ничего не отправляется</span></div></section>`;
 return `<main class="main r9 r9-prep" data-screen-label="Подготовка задачи">${head}${exN}<ol class="r9-steps">${s1}${s2}${s3}${s4}</ol></main>`}
const NL_=LP.NL;
function readF2(fm){const v=n=>{const e=fm.querySelector(`[name="${n}"]:checked`);return e?e.value:''};const f={goal:v('goal'),cap:fm.cap.value.trim(),capNone:fm.capNone.checked,ch:[...fm.querySelectorAll('[name=ch]:checked')].map(e=>e.value),chNeed:!!(fm.chNeed&&fm.chNeed.checked),hor:fm.hor.value,dep:v('dep')};
 const er=[];if(!f.goal)er.push(['e-goal','Выберите цель','[name=goal]']);if(!f.capNone&&!/^\d[\d\s]*(?:[.,]\d+)?$/.test(f.cap))er.push(['e-cap',f.cap?'Введите сумму числом или отметьте «пока не определён»':'Укажите сумму или отметьте «пока не определён»','#r9-cap']);if(fm.chNeed&&!f.ch.length&&!f.chNeed)er.push(['e-ch','Отметьте каналы или «нужен подбор»','[name=ch]']);if(!f.hor)er.push(['e-hor','Выберите горизонт или «не задан»','#r9-hor']);if(!f.dep)er.push(['e-dep','Выберите глубину','[name=dep]']);
 $$('.r9-err',fm).forEach(e=>{e.hidden=true;e.textContent=''});er.forEach(e=>{const p=$('#'+e[0],fm);p.hidden=false;p.textContent=e[1]});if(er.length){const el=fm.querySelector(er[0][2]);el&&el.focus();return null}return f}

/* ══ выполнение (демо) ══ */
let tmr=0;const RM=()=>matchMedia('(prefers-reduced-motion: reduce)').matches;
function launch(sk){const P=ST.prep[sk],sj=DEMO.subj[sk];const nv=ST.runs.filter(r=>r.sk===sk).length;const id=RID[sk]+(nv?'-'+(nv+1):'');ST.runs=ST.runs.filter(r=>r.id!==id);
 const r={id,sk,code:'',st:'run',n:1,at:NOW,asked:NOW,from:P.from||'',f:P.f,need:P.need};ST.empty=false;ST.runs.push(r);ST.hist.push({run:id,at:NOW,t:'Запущено (демо): '+sj.task});delete ST.prep[sk];save();location.hash='#/research/'+id;arm()}
function arm(){clearInterval(tmr);if(!ST.runs.some(r=>r.st==='run'))return;tmr=setInterval(step,LP.r9speed||(RM()?400:1100))}
function step(){let any=0;ST.runs.forEach(r=>{if(r.st!=='run')return;any=1;const L=DEMO.stages[r.sk];
 if(L[r.n]&&L[r.n].q&&!r.qa){r.st='input';r.asked=NOW;ST.hist.push({run:r.id,at:NOW,t:'Вопрос: '+DEMO.q[r.sk].q});paint(r,'q');return}
 r.n++;r._new=r.n-1;if(r.n>=L.length){const nd=L.some(s=>s.nd);r.st=nd?'part':'done';r.fin=NOW;const x=res(r);ST.hist.push({run:r.id,at:NOW,t:(nd?'Частично':'Готово')+': '+ACTL[x.action]});const pv=prevOf(r),pa=pv?ACTL[res(pv).action]+(pv.st==='part'?' · частично':''):'вывода не было',na=ACTL[x.action]+(nd?' · частично':'');ST.hist.push({run:r.id,ver:1,at:NOW,t:SJ(r).short+' · исследование'+(pv?', версия '+(ST.runs.filter(y=>y.sk===r.sk).indexOf(r)+1):''),was:pa,now:na,why:'демо-запуск 01.10'+(pv?' · прежняя версия '+(pv.code||pv.id)+(pa===na?' · вывод не изменился':''):'')});paint(r,'done')}else paint(r)});
 save();if(!any||!ST.runs.some(r=>r.st==='run'))clearInterval(tmr)}
function paint(r,ev){const p=LP.parse().p;if(p==='/research/'+r.id){const b=$('#r9-body');if(!b)return;b.innerHTML=T(bodyHtml(r));const ch=$('.r9-h .st9');if(ch)ch.outerHTML=chip(r.st);LP.mountCharts&&LP.mountCharts(b);
  if(ev==='q'){const h=$('#r9q-h');h&&h.focus({preventScroll:true});near(h);LP.announce&&LP.announce('Требуется уточнение: '+DEMO.q[r.sk].q)}else if(ev==='done'){const h=$('#r9r-h');h&&h.focus({preventScroll:true});scrollTo(0,0);LP.announce&&LP.announce('Исследование: '+STL[r.st]+'. '+ACTL[res(r).action])}else{const s=$('.r9-si[data-in="1"]');s&&near(s)}}
 else if(p==='/research'||p==='/research/new'||p==='/'){/* обновить счётчики */shell9(LP.parse());if(p==='/research')$('#view').innerHTML=T(home(LP.parse().q))}
 delete r._new}
function near(el){if(!el)return;const b=el.getBoundingClientRect();if(b.bottom>innerHeight-24)scrollBy(0,b.bottom-innerHeight+24+(innerWidth<=760?80:0));else if(b.top<72)scrollBy(0,b.top-72)}

/* ══ отчёт и меморандум A4 ══ */
function sheet(r,kind,i,n,body){const sj=SJ(r);return `<section class="a4" data-screen-label="${kind==='report'?'Отчёт':'Меморандум'} · лист ${i}"><header class="a4-h"><span class="a4-b">LotPrism Research · ${kind==='report'?'Отчёт':'Меморандум'}</span><span class="a4-t">${esc(sj.title)}</span><span class="code">${r.id}</span></header><div class="a4-c">${body}</div><footer class="a4-f"><span>${FOOT}</span><span>демонстрация · лист ${i} из ${n}</span></footer></section>`}
const kv=a=>`<dl class="a4-kv">${a.map(x=>`<div><dt>${x[0]}</dt><dd>${x[1]}</dd></div>`).join('')}</dl>`;
function gateT(x,a,b){return `<table class="a4-t"><thead><tr><th scope="col">Гейт</th><th scope="col">Состояние</th><th scope="col">Основание</th></tr></thead><tbody>${x.gates.slice(a,b).map((g,i)=>`<tr><th scope="row"><span class="code">${gc(a+i+1)}</span> ${GN[a+i]}</th><td>${esc(g[0])}</td><td>${esc(g[1])}</td></tr>`).join('')}</tbody></table>`}
function report(id,kind){const r=runOf(id);if(!r||!['done','part'].includes(r.st))return `<main class="main r9"><h1 class="h1">Отчёта пока нет</h1><p class="t2">Отчёт собирается из готового или частичного результата.</p><a href="#/research/${id}">← К исследованию</a></main>`;
 const x=res(r),sj=SJ(r),f=r.f||{},cl=claims(r);const act=`<p class="a4-act">${ACTL[x.action]}${x.partial?' · частично':''}</p>${x.noStop?`<p>${NOSTOP}</p>`:''}`;
 const why=`<ol class="a4-why">${x.why.map(w=>`<li><span class="code">${gc(w[0])}</span> <b>${GN[w[0]-1]}.</b> ${esc(w[1])}</li>`).join('')}</ol>`;
 const money=`<table class="a4-t"><tbody>${x.money.map(m=>`<tr><th scope="row">${m[0]}</th><td class="num">${m[1]}</td><td>${KW[m[2]]}</td><td>${esc(m[3])}</td></tr>`).join('')}</tbody></table>`;
 const cls=k=>`<ul class="a4-l">${cl.filter(c=>c.k===k).map(c=>`<li>${esc(c.t)} <span class="a4-m">· ${esc(c.src)}</span></li>`).join('')}</ul>`;
 let pages;
 if(kind==='memo')pages=[`<h1 class="a4-h1">Меморандум</h1><p class="a4-m">${sj.task} · готово ${fdt(r.fin||NOW)} · те же решение и числа, что в отчёте; нового исследования нет</p><h2 class="a4-h2">Решение исследования</h2>${act}<h2 class="a4-h2">Три причины</h2>${why}<h2 class="a4-h2">Предел закупки</h2><p>${esc(x.limit)}</p><h2 class="a4-h2">Прибыль и деньги</h2>${money}`,
  `<h2 class="a4-h2">Неблагоприятный случай</h2><p>${esc(x.adverse)}</p><h2 class="a4-h2">Каких подтверждений не хватает</h2><ul class="a4-l">${x.miss.map(t=>`<li>${esc(t)}</li>`).join('')}</ul><h2 class="a4-h2">Что дальше</h2><ul class="a4-l">${x.next.map(t=>`<li>${esc(t)}</li>`).join('')}</ul><h2 class="a4-h2">Действует до</h2><p><b>${x.until}</b> · ${esc(x.untilWhy)}</p><h2 class="a4-h2">Полномочия</h2><p>Это рекомендация исследования. Решение по версии записывает пользователь; разрешение тратить капитал, обязательство и исполнение — вне системы.</p>`];
 else pages=[
  `<h1 class="a4-h1">Семь вопросов</h1><ol class="a4-7"><li><h2 class="a4-h2">Какое действие допустимо</h2>${act}</li><li><h2 class="a4-h2">Три причины</h2>${why}</li><li><h2 class="a4-h2">Предел закупки</h2><p>${esc(x.limit)}</p></li><li><h2 class="a4-h2">Прибыль и деньги</h2>${money}</li><li><h2 class="a4-h2">Неблагоприятный случай</h2><p>${esc(x.adverse)}</p></li><li><h2 class="a4-h2">Каких подтверждений не хватает</h2><p>${x.miss.map(esc).join(' · ')}</p></li><li><h2 class="a4-h2">До какой даты действует вывод</h2><p><b>${x.until}</b> · ${esc(x.untilWhy)}</p></li></ol>`,
  `<h1 class="a4-h1">Паспорт решения</h1>${kv([['Предмет',esc(sj.title)],['Задача',esc(sj.task)+': '+esc(sj.q)],['Перенесено из',esc(sj.src)+' · '+sj.ctx.length+' полей; вывод карточки не перенесён'],['Цель',esc(goalTxt(f))],['Капитал',f.capNone?'пока не определён':f.cap?esc(f.cap)+' €':'не задан'],['Каналы',esc((f.ch||[]).join(', ')||(f.chNeed?'нужен подбор':sj.kind==='lot'?'не заданы':'amazon.de · FBA'))],['Горизонт · глубина',esc((f.hor||'не задан')+' · '+(f.dep||'не задана'))],['Покрытие',esc(COVER)],['Лучший достижимый статус',ACTL.NEEDS_EVIDENCE],['Начато · готово',(r.seed?fdt(r.at):'01.10 10:00')+' · '+fdt(r.fin||NOW)],['Знание',['conf','calc','ass','unk'].map(k=>KW[k]+' '+tally(r,1)[k]).join(' · ')]])}<h2 class="a4-h2">Где находится это решение</h2><ol class="a4-chain">${[['Прогноз','исследовательский'],['Рекомендация','этот отчёт'],['Решение','не записано'],['Разрешение капитала','вне системы'],['Обязательство капитала','вне системы'],['Исполнение','вне системы'],['Реализованный результат','не наступил']].map((s,i)=>`<li${i===1?' class="on"':''}><b>${s[0]}</b><span>${s[1]}</span></li>`).join('')}</ol>`,
  `<h1 class="a4-h1">Гейты ${gc(1)}–${gc(5)}</h1>${gateT(x,0,5)}`,
  `<h1 class="a4-h1">Гейты ${gc(6)}–${gc(10)}</h1>${gateT(x,5,10)}<p class="a4-m">Программные проверки и проверка вторым человеком требуют инженерной реализации; в демо не выполняются.</p>`,
  `<h1 class="a4-h1">Экономика</h1><p class="a4-m">Три представления не складываются. Непроданный остаток — не ноль.</p>${money}${sj.kind==='lot'?figRoutes()+figCash():sj.kind==='item'?figCostItem():''}`,
  `<h1 class="a4-h1">Заключение</h1>${kv([['Вывод',ACTL[x.action]+(x.partial?' · частично':'')],['Доказательства',esc(x.concl.ev)],['Влияние на деньги',esc(x.concl.money)],['Условия',esc(x.concl.cond)],['Что изменит решение',x.change.map(c=>'если '+esc(c[0])+' → '+esc(c[1])).join('<br>')]])}`,
  `<h1 class="a4-h1">План действий</h1><table class="a4-t"><thead><tr><th scope="col">Шаг</th><th scope="col">Кто</th><th scope="col">Гейт</th></tr></thead><tbody>${x.plan.map(p=>`<tr><td>${esc(p[0])}</td><td>вы</td><td class="code">${p[1]}</td></tr>`).join('')}</tbody></table><p class="a4-m">Исследование не записывает решение, не отправляет запросы и не тратит капитал.</p>`,
  `<h1 class="a4-h1">Приложение A · доказательства</h1><h2 class="a4-h2">Источники</h2><table class="a4-t"><tbody>${x.src.map(s=>`<tr><th scope="row">${esc(s[0])}</th><td>${esc(s[1])}</td><td>${esc(s[2])}</td><td>${esc(s[3])}</td></tr>`).join('')}</tbody></table><h2 class="a4-h2">Подтверждено</h2>${cls('conf')}<h2 class="a4-h2">Рассчитано</h2>${cls('calc')}`,
  `<h1 class="a4-h1">Приложение B · допущения</h1><h2 class="a4-h2">Допущения</h2>${cls('ass')}<h2 class="a4-h2">Неизвестно</h2>${cls('unk')}<p class="a4-m">Неизвестное не считается нулём.</p>`];
 const N=pages.length;
 return `<main class="main rp9" data-screen-label="${kind==='report'?'Отчёт':'Меморандум'} ${r.id}"><h1 class="sr-only">${kind==='report'?'Отчёт':'Меморандум'} · ${esc(sj.title)}</h1><nav class="rp9-bar" aria-label="Отчёт"><a href="#/research/${r.id}" id="r9-back">← К исследованию</a><span class="t2">${kind==='report'?'Отчёт · 9 листов A4':'Меморандум · 2 листа A4'} · вёрстка; снимок и экспорт — требуют инженерной реализации</span><span class="sp"></span><a href="#/research/${r.id}/${kind==='report'?'memo':'report'}">${kind==='report'?'Меморандум':'Полный отчёт'}</a><button class="btn btn-s sm" type="button" data-act="r9-print">Печать</button></nav><div class="rp9-pages">${pages.map((p,i)=>sheet(r,kind,i+1,N,p)).join('')}</div></main>`}

/* ══ оболочка: шапка без инструмента, Research — раздел навигации ══ */
function shell9(r){const pr=$('#proto');if(pr&&$('#top').contains(pr))document.body.appendChild(pr);
 $('#top').innerHTML=T(`<a class="logo" href="#/" aria-label="LotPrism — главная"><img src="../assets/logo.svg" alt="LotPrism" width="144" height="19"></a><div class="ws"><b>Demo-Handel GmbH</b><span>Amazon Германия · EUR</span></div><span class="sp"></span><span class="user"><i>ИБ</i>Ирина Беккер</span><button class="mnav" type="button" data-act="mnav" aria-expanded="false" aria-controls="rail" aria-label="Разделы">${IC.menu}</button>`);
 if(pr)$('#top .ws').after(pr);
 const p=r.p,lane=p==='/products'?r.q.get('lane'):null,ni=nInput();
 const cur=c=>c?' aria-current="page"':'';
 const na=n=>`<a href="#/" data-act="na" data-what="${n}">${n}</a>`;
 const rail=$('#rail');const open=rail.classList.contains('open');
 rail.innerHTML=T(`<div class="rg"><a href="#/"${cur(p==='/'||p==='')}>Главная</a></div>
<div class="rg"><span class="eyebrow">Товары</span><a href="#/products?lane=resale" data-fresh${cur(lane==='resale')}>Перепродажа<span class="c">13</span></a><a href="#/products?lane=new" data-fresh${cur(lane==='new')}>Новый листинг<span class="c">${LP.NL.length}</span></a></div>
<div class="rg rg9"><span class="eyebrow">Research</span><a href="#/research" id="nav-rs"${cur(p==='/research'||p==='/research/new'||/^\/research\/R-/.test(p))}>Исследования${ni?`<span class="c c9"><span class="sr-only">ждут ответа: </span>${ni}</span>`:''}</a><a href="#/research/lots"${cur(p==='/research/lots'||/^\/research\/BT-/.test(p))}>Партии</a></div>
<div class="rg"><span class="eyebrow">Поставщики</span>${na('Предложения и прайсы')}${na('Задания ассистента')}</div><div class="rg"><span class="eyebrow">Деньги</span>${na('Закупки и продажи')}${na('Результаты')}</div><div class="rg"><span class="eyebrow">Пространство</span>${na('Источники данных')}${na('Команда и настройки')}</div>`);
 rail.classList.toggle('open',open)}

/* ══ входы и возврат ══ */
const enc=encodeURIComponent;
function cardBlock(id){const sk=(LP.NL.includes(id)?'hyp:':'item:')+id,sj=DEMO.subj[sk];if(!sj)return '';const r=runBy(sk),h=location.hash;
 const go=`#/research/new?subj=${sk.split(':')[0]}&amp;id=${id}&amp;from=${enc(h)}`;const lbl=sk.startsWith('hyp')?'Проверить гипотезу':'Исследовать товар';
 let st='',nw='';
 if(!r)st=`<p>Исследование в Research не запускалось.${id==='P01'?' <span class="t2">Поиск поставщиков 21–24.09 выполняла команда LotPrism — итог ниже, в «Почему такой вывод».</span>':''}</p>`;
 else if(active(r))st=`<p class="r9-meta">${chip(r.st)}${r.code?'<span class="code">'+r.code+'</span>':''}<span class="t2">${r.st==='input'?'вопрос к вам: '+esc(DEMO.q[sk].q):'завершено '+doneN(r)+' '+etap(doneN(r))+' из '+DEMO.stages[sk].length}</span></p>`;
 else{const x=res(r);st=`<p class="r9-meta">${chip(r.st)}<span class="t2">${r.fin?fdt(r.fin):''} · ${untilT(x)}</span></p><p class="r9-cr"><b>${ACTL[x.action]}</b>${x.noStop?' · '+NOSTOP.toLowerCase():''}</p>`;if(id==='P01')nw=newFrom()}
 const act=r?`<a class="btn btn-s sm" data-ret id="r9c-open" href="#/research/${r.id}">${active(r)?'Открыть идущее':'Открыть результат'}</a>`:'';
 return `<section class="gs r9-c" aria-labelledby="r9c-h" data-av="des" data-avl="вариант дизайна"><div class="r9-ch"><h2 class="h2" id="r9c-h">Исследование</h2></div>${st}<div class="r9-ca">${act}<a class="btn btn-s sm" data-ret id="r9c-new" href="${go}">${lbl}</a></div>${nw}</section>`}
function newFrom(){return `<div class="r9-nf"><h3 class="h3">Новое из исследования</h3><p class="t2">Сопоставление без перезаписи: карточка и ваше решение не меняются. Новое решение записываете вы.</p><div class="tbl-wrap" tabindex="0" role="region" aria-label="Новое из исследования"><table class="tbl r9-tbl"><thead><tr><th scope="col">Поле</th><th scope="col">В карточке</th><th scope="col">Нашло исследование</th><th scope="col">Источник · дата · вид знания</th></tr></thead><tbody>
<tr><th scope="row">S4 · производитель, Китай</th><td>не показан · итог: 4 предложения, условно сопоставимы два</td><td><span class="ms na">${IC.na}</span> Не прочитано: каталог за регистрацией</td><td>S4 · ${d5(S4.observed_at)} · ${KN.unk}</td></tr>
<tr><th scope="row">S2 · единица цены</th><td>8,10 € ${K.COND}</td><td>упаковка ${esc(S2.pack)}, EAN ${esc(S2.ean)} — единица не подтверждена</td><td>S2 · ${d5(S2.observed_at)} · ${KN.unk}</td></tr></tbody></table></div></div>`}
function cardPatch(id){const sk=(LP.NL.includes(id)?'hyp:':'item:')+id;if(!DEMO.subj[sk]||$('.r9-c'))return;const html=T(cardBlock(id));
 const h3=$('#cd section.hero3');if(h3)h3.insertAdjacentHTML('afterend',html);else{const ch=$('#cd .cd-h');ch&&ch.insertAdjacentHTML('afterend',html)}
 const g3=$('#g3');if(g3&&!$('#r9-cmp')){const sec=g3.closest('section');sec.insertAdjacentHTML('beforeend',T(`<div class="r9-ca"><a class="btn btn-s sm" data-ret id="r9-cmp" href="#/research/new?subj=item&amp;id=P01&amp;from=${enc(location.hash)}">Сравнить предложения</a><span class="t2">в Research · предложения переносятся с источниками и условиями</span></div>`))}}
function lotPatch(){const m=$('#view main');if(!m||$('.r9-c'))return;const sk='lot:BT-01',r=runBy(sk);const h='#/research/BT-01';
 const html=`<section class="r9-c r9-cl" aria-labelledby="r9c-h"><div class="r9-ch"><h2 class="h2" id="r9c-h">Исследование партии</h2></div>${r?`<p class="r9-meta">${chip(r.st)}<span class="t2">${active(r)?'завершено '+doneN(r)+' '+etap(doneN(r))+' из '+DEMO.stages[sk].length:untilT(res(r))}</span></p>${!active(r)?`<p class="r9-cr"><b>${ACTL[res(r).action]}</b> · частично</p>`:''}`:'<p>Исследование партии не запускалось.</p>'}<div class="r9-ca">${r?`<a class="btn btn-s sm" data-ret id="r9c-open" href="#/research/${r.id}">${active(r)?'Открыть идущее':'Открыть результат'}</a>`:''}<a class="btn btn-${r?'s':'p'} sm" data-ret id="r9c-new" href="#/research/new?subj=lot&amp;id=BT-01&amp;from=${enc(h)}">Проверить партию</a></div></section>`;
 const ph=m.querySelector('.pg-h,h1');const anchor=ph&&ph.closest('.pg-h')||ph;if(anchor)anchor.insertAdjacentHTML('afterend',T(html));else m.insertAdjacentHTML('afterbegin',T(html))}
function fixLots(){$$('#view a[href="#/research"]').forEach(a=>{a.setAttribute('href','#/research/lots');if(/Партии по запросу/.test(a.textContent))a.textContent='← Партии'});$$('#view a,#view button').forEach(a=>{if(/↗/.test(a.textContent))a.textContent=a.textContent.replace(/\s*↗/,'')})}
function dashPatch(){const ul=$('#view .msg');const n=nInput();
 if(ul&&n&&!$('#dm-rs')){ul.insertAdjacentHTML('beforeend',T(`<li class="msg-r" data-av="des" data-avl="вариант дизайна"><span class="msg-g" aria-hidden="true">?</span><div class="msg-tx"><p><span class="msg-s">Ждут ответа: ${n}</span><span class="msg-x">Ждут вашего ответа: ${n} ${plural(n)} · без ответа исследование стоит</span></p></div><div class="msg-a"><a class="btn btn-s sm" id="dm-rs" href="#/research?f=input"><span>Открыть<span class="msg-al"> вопросы</span><span class="msg-ar" aria-hidden="true"> →</span></span></a></div></li>`))}
 const dd=$('#dd-h');if(dd){const s=dd.closest('section');const p=$('.line8 p',s);if(p)p.innerHTML=T('Партия <span class="code">BT-01</span> · Research · Партии · предложение до <span class="n">08.10 18:00</span> · спрос не подтверждён');const a=$('.line8 a',s);if(a)a.textContent='Открыть партию'}
 $$('#view a').forEach(a=>{if(/↗/.test(a.textContent))a.textContent=a.textContent.replace(/\s*↗/,'')})}
document.addEventListener('click',e=>{const a=e.target.closest('a[data-ret]');if(a)ss.set('lp9:ret',{h:location.hash,y:scrollY,f:a.id})},true);
function retRestore(){const t=ss.get('lp9:ret');if(!t||t.h!==location.hash)return false;ss.del('lp9:ret');setTimeout(()=>{scrollTo(0,t.y);const el=t.f&&document.getElementById(t.f);if(el){el.focus({preventScroll:true});const c=el.closest('.r9-c');if(c&&!RM()){c.classList.add('r9-here');setTimeout(()=>c.classList.remove('r9-here'),700)}}},0);return true}

/* ══ действия и формы ══ */
Object.assign(LP.ACT,{
 'r9-next':b=>{const P=ST.prep[b.dataset.sk];P.step++;save();rePrep(P.step)},
 'r9-skip':b=>{const P=ST.prep[b.dataset.sk];P.need={};P.step=4;save();rePrep(4)},
 'r9-step':b=>{const P=ST.prep[b.dataset.sk];P.step=+b.dataset.n;save();rePrep(P.step)},
 'r9-launch':b=>launch(b.dataset.sk),
 'r9-print':()=>print()
});
function rePrep(n){$('#view').innerHTML=T(prep(LP.parse().q));const h=$('#r9p'+n);if(h){h.focus({preventScroll:true});const sec=h.closest('.r9-p');if(sec&&!RM())sec.animate([{opacity:0,transform:'translateY(6px)'},{opacity:1,transform:'none'}],{duration:200,easing:'cubic-bezier(.23,1,.32,1)'});near(sec);const t=sec.getBoundingClientRect().top;if(t<72||t>innerHeight*.6)scrollBy(0,t-88)}}
document.addEventListener('submit',e=>{const fm=e.target;
 if(fm.id==='r9-f2'){e.preventDefault();const f=readF2(fm);if(!f)return;const P=ST.prep[fm.dataset.sk];P.f=f;P.step=3;save();rePrep(3)}
 if(fm.id==='r9-q'){e.preventDefault();const v=(fm.querySelector('[name=qa]:checked')||{}).value,er=$('#r9q-e');const text=fm.text.value.trim(),file=fm.file.files&&fm.file.files[0]?fm.file.files[0].name:'';
  const msg=!v?'Выберите ответ':v==='own'&&!text?'Напишите свой ответ':v==='doc'&&!file?'Выберите файл документа':'';if(msg){er.hidden=false;er.textContent=msg;(v==='own'?fm.text:v==='doc'?fm.file:fm.querySelector('[name=qa]')).focus();return}
  const r=runOf(fm.dataset.run);r.qa={v,text,file,at:NOW};r.n++;r._new=r.n-1;r.st='run';ST.hist.push({run:r.id,at:NOW,t:'Ваш ответ: '+(v==='a'?DEMO.q[r.sk].opt:v==='own'?text:'документ «'+file+'»')});save();paint(r);const h=$('#r9p-h');h&&h.focus({preventScroll:true});LP.announce&&LP.announce('Ответ записан. Исследование продолжается');shell9(LP.parse());arm()}});
document.addEventListener('change',e=>{const t=e.target;
 if(t.name==='qa'){const fm=t.form;$('.r9-own',fm).hidden=t.value!=='own';$('.r9-doc',fm).hidden=t.value!=='doc';$('#r9q-e').hidden=true;if(t.value==='own')fm.text.focus()}
 if(t.name==='capNone'){const c=$('#r9-cap');c.disabled=t.checked;if(t.checked)c.value=''}
 if(t.name==='chNeed'&&t.checked)$$('[name=ch]',t.form).forEach(x=>x.checked=false);if(t.name==='ch'&&t.checked){const n=t.form.chNeed;if(n)n.checked=false}
 if(t.dataset.need){const sk=$('[data-act="r9-next"]')&&$('[data-act="r9-next"]').dataset.sk;const P=ST.prep[sk];if(P){t.checked?P.need[t.dataset.need]=1:delete P.need[t.dataset.need];save()}}
 if(t.name==='r9e'){ST.empty=t.value==='empty';save();LP.route()}});

/* ══ панель прототипа ══ */
function proto9(){const b=$('#proto-b');if(LP.p10||!b||$('#r9-proto',b))return;b.insertAdjacentHTML('beforeend',T(`<fieldset id="r9-proto"><legend>Research (демо)</legend><label><input type="radio" name="r9e" value="demo"${ST.empty?'':' checked'}>Исследования из демо-данных</label><label><input type="radio" name="r9e" value="empty"${ST.empty?' checked':''}>Пустой список исследований</label><button class="btn btn-s sm" type="button" data-act="r9-reset">Сбросить демо Research</button></fieldset>`))}
LP.ACT['r9-reset']=()=>{clearInterval(tmr);ST={runs:seed(),empty:false,hist:[],prep:{}};save();const i=$('#r9-proto input[value=demo]');if(i)i.checked=true;LP.toast&&LP.toast('na','Демо Research сброшено');location.hash='#/research'};

/* ══ маршрут ══ */
function view(html){$('#view').innerHTML=T(html);LP.mountCharts&&LP.mountCharts($('#view'))}
LP.p9={DEMO,res,claims};
const _r8=LP.route;
let first=true;
LP.route=function(){_r8();if(S.view!=='user')return;const fr0=first;const r=LP.parse(),p=r.p;let m,fresh=false;shell9(r);
 if(LP.p10&&LP.p10(r)){first=false;return}
 if(p==='/research'){view(home(r.q));fresh=true}
 else if(p==='/research/lots'){view(LP.rsEntry());fixLots();fresh=true}
 else if(p==='/research/new'){view(prep(r.q));fresh=true}
 else if(m=p.match(/^\/research\/(R-[A-Z0-9-]+)(?:\/(report|memo))?$/)){const rr=ST.runs.find(x=>x.id===m[1]);if(DIRECT[m[1]]&&(!rr||ST.empty&&!runOf(m[1])||(first&&FRESH&&!['done','part'].includes(rr.st))))finalize(m[1]);view(m[2]?report(m[1],m[2]):runPage(m[1]));fresh=true}
 else if(/^\/research\/BT-0\d$/.test(p)){fixLots();if(p==='/research/BT-01')lotPatch()}
 else if(p==='/'||p==='')dashPatch();
 else if(p.startsWith('/p/'))cardPatch(p.slice(3));
 proto9();
 first=false;void fr0;
 const back=retRestore();
 if(fresh&&!back){scrollTo(0,0);const h=$('#view h1');if(h){h.tabIndex=-1;h.focus({preventScroll:true})}}};
arm();LP.route();
})();
